-- Boundary Review v6.99.79 — Tier 3 collision guard residual fixes (10 entities)
-- Discovered by boundary_collision_guard.py super_group_alerts check

BEGIN;

-- ARAKAN (Burma coastal) — 2 different dynasties
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/arakan-fix] Replaced shared Arakan polygon with 150km circle. Dhaññavati (~580 BCE - 370 CE) was the earliest Arakan kingdom in modern Rakhine State (Burma), Pyu/Indianized culture; founding chapter of Arakanese history; succeeded by Vesali.' WHERE id = 873;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/arakan-fix] Replaced shared Arakan polygon with 150km circle. Vesali (370-818 CE) was a Mahayana Buddhist kingdom in Arakan, capital Vesali (modern Mrauk-U area); coin minting + maritime trade with Bengal + Bay of Bengal.' WHERE id = 874;

-- NABATEAN/THAMUD — different N Arabian peoples
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/thamud-fix] Replaced shared Nabatean polygon with 200km circle. 𐪉𐪃𐪙𐪕 = Thamud (~800 BCE - 300 CE) was an Ancient N Arabian people/tribal federation in Hejaz (modern Saudi Arabia NW), distinct from Nabataeans; mentioned in Mesopotamian + Quranic sources; their rock-cut tombs at Mada''in Salih are UNESCO heritage.' WHERE id = 801;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/nabataean-fix] Replaced shared Nabatean polygon with 300km circle around Petra. Nabataean Kingdom (مملكة الأنباط, 312 BCE - 106 CE) was an Arab incense-trade kingdom centered on Petra (Jordan); annexed by Trajan as Arabia Petraea; famous rock-cut architecture.' WHERE id = 179;

-- NAZCA + HUARPA — different Peruvian cultures
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/nazca-fix] Replaced shared Nazca polygon with 200km circle. Nazca (~100 BCE - 800 CE) was a S coastal Peruvian Andean culture, famous for Nazca Lines geoglyphs + polychrome pottery + underground aqueducts (puquios); centered on Cahuachi ceremonial complex.' WHERE id = 638;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/huarpa-fix] Replaced shared Nazca polygon with 100km circle. Huarpa (200-550 CE) was an Ayacucho-area Andean highland culture, direct predecessor of Wari empire; bridge between Nazca + Wari traditions.' WHERE id = 969;

-- QATABAN + HADHRAMAUT — different S Arabian kingdoms
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/hadhramaut-fix] Replaced shared Qataban polygon with 300km circle. حضرموت Hadhramaut (~800 BCE - 300 CE) was an ancient S Arabian kingdom in modern E Yemen + Oman Dhofar coast; controlled frankincense trade (Wadi Hadhramaut + coastal ports); capital Shabwa.' WHERE id = 628;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/qataban-fix] Replaced shared Qataban polygon with 200km circle. قتبان Qataban (400 BCE - 200 CE) was an ancient S Arabian kingdom (W of Hadhramaut, S of Sabaean); capital Tamna; controlled Wadi Bayhan; spice + frankincense trade; absorbed by Hadhramaut.' WHERE id = 627;

-- MITANNI + URARTU — Bronze Age vs Iron Age different states
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/mitanni-fix] Replaced shared Urartu polygon with 400km circle. Mitanni (~1550-1260 BCE) was a Hurrian-Indo-Aryan elite kingdom of N Mesopotamia + N Syria, capital Washukanni; rival of Egypt + Hittites (Amarna correspondence); destroyed by Hittites + Assyrians.' WHERE id = 182;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/urartu-fix] Replaced shared Urartu polygon with 300km circle around Tushpa (Van). 𒌨𒀀𒊒𒂗 Urartu (860-590 BCE) was an Iron Age kingdom in Armenian highlands (Lake Van basin + S Caucasus + E Anatolia); capital Tushpa; conflict with Assyria; absorbed into Median Empire 590 BCE; ancestor culture of Armenians.' WHERE id = 183;

SELECT COUNT(*) FROM geo_entities WHERE id IN (873, 874, 801, 179, 638, 969, 628, 627, 182, 183);

COMMIT;
