-- Boundary Review v6.99.79 — Tier 2 Batch 3: aourednik 3-entity groups (19 groups, 57 entities)
-- Pattern: keep PRIMARY (matching name), replace others with capital-based circle

BEGIN;

-- Helper macro: just inline SQL per entity. Keep primaries with note only.

-- ABBASID CALIPHATE (3): keep 31, fix 480 480km Cairo, 474 400km Aleppo
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-abbasid-primary] LEGITIMATE Abbasid polygon. 2 other entities (Tulunids, Hamdanids) erroneously shared this — corrected.' WHERE id = 31;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 480000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 480000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/abbasid-fix] Replaced erroneous Abbasid polygon with 480km circle. Tulunids (868-905) were a semi-autonomous Egyptian dynasty under Abbasid suzerainty, founded by Ahmad ibn Tulun; expanded into Syria + Hejaz; absorbed back into Abbasid Caliphate 905.' WHERE id = 480;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/abbasid-fix] Replaced erroneous Abbasid polygon with 400km circle. Hamdanids (890-1004) were a Shia Arab dynasty in N Syria + Mosul, often warring against Byzantines + Buyids; peak under Sayf al-Dawla in Aleppo.' WHERE id = 474;

-- ACHAEMENID EMPIRE (3): keep 847 Persepolis, fix 497 + 490 Babylon
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-achaemenid-primary] LEGITIMATE Achaemenid polygon. 2 Babylonian entities erroneously shared this — corrected.' WHERE id = 847;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/achaemenid-fix] Replaced erroneous Achaemenid polygon with 500km circle. Neo-Babylonian Empire (Chaldean, 626-539 BCE) under Nabopolassar+Nebuchadnezzar II — controlled Mesopotamia + Levant + parts of Arabia; ended with Persian conquest 539 BCE.' WHERE id = 497;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/achaemenid-fix] Replaced erroneous Achaemenid polygon with 500km circle. 𒆳𒆍𒀭𒊏𒆠 = "Kar-duniash" = Babylonian script for Babylonia. Likely duplicate with id=497 (same dates/capital). DUPLICATE candidate.' WHERE id = 490;

-- ANNAM (3): no clear primary, all early N Vietnam dynasties, all ~150km
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/annam-fix] Replaced erroneous "Annam" polygon with 150km circle. Nhà Ngô (939-967) was the first Vietnamese dynasty after a millennium of Chinese rule, founded by Ngô Quyền after Battle of Bach Dang River 938.' WHERE id = 877;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/annam-fix] Replaced erroneous "Annam" polygon with 150km circle. Nhà Đinh (968-980) was Đinh Bộ Lĩnh dynasty unifying 12 warring lords; first to use name Đại Cồ Việt; capital Hoa Lư.' WHERE id = 878;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/annam-fix] Replaced erroneous "Annam" polygon with 150km circle. Nhà Tiền Lê (Early Lê dynasty, 980-1009) founded by Lê Hoàn (Lê Đại Hành), defended against Song China invasion 981; capital Hoa Lư.' WHERE id = 879;

-- BOSNIA (3): keep 663, fix 665 + 584
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-bosnia-primary] LEGITIMATE Bosnia polygon. 2 other entities (Zeta, Serbian Despotate) erroneously shared this — corrected.' WHERE id = 663;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/bosnia-fix] Replaced erroneous Bosnia polygon with 80km circle. Zeta (Crnojevic principality, 1360-1421→1499) was a Montenegrin principality on Adriatic coast, predecessor of modern Montenegro; resisted Ottomans longest in W Balkans.' WHERE id = 665;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/bosnia-fix] Replaced erroneous Bosnia polygon with 200km circle. Serbian Despotate (Деспотовина Србија, 1402-1459) was successor state to medieval Serbian Empire, last vassal of Ottomans before annexation 1459 (fall of Smederevo).' WHERE id = 584;

-- CHAGATAI KHANATE (3): keep 328, fix 339 (Moghulistan) + 458 (Northern Yuan)
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-chagatai-primary] LEGITIMATE Chagatai polygon. 2 successor states erroneously shared this — corrected.' WHERE id = 328;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/chagatai-fix] Replaced erroneous Chagatai polygon with 600km circle. مغولستان (Moghulistan, 1347-1462) was the eastern Chagatai successor — Tarim Basin + Yedisu + Issyk Kul + parts of Mongolia; western half (Transoxiana) became Timurid base.' WHERE id = 339;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 900000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 900000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/chagatai-fix] Replaced erroneous Chagatai polygon with 900km circle. 北元 (Northern Yuan, 1368-1635) was the Mongol regime that retreated from China after Yuan fall — covered Mongolia, parts of Manchuria; continued Yuan claim until Ligdan Khan death 1634.' WHERE id = 458;

-- GHAZNAVID EMIRATE (3): keep 143, mark 477 as DUPLICATE, fix 509 (Ghurid)
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-ghaznavid-primary] LEGITIMATE Ghaznavid polygon. id=477 is duplicate transliteration; id=509 is successor Ghurid Sultanate — corrected.' WHERE id = 143;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ghaznavid-fix] Replaced erroneous Ghaznavid polygon with 600km circle. دولت غزنویان is alternate transliteration of "Ghaznavid Empire" — DUPLICATE candidate with id=143 (same dates 977-1186, same capital Ghazni). Recommend merge.' WHERE id = 477;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ghaznavid-fix] Replaced erroneous Ghaznavid polygon with 600km circle. الدولة الغورية (Ghurid Sultanate, 1148-1215) was the Ghaznavid successor — central Afghanistan based at Firuzkuh; Muhammad Ghuri conquered N India after 1192 (Battle of Tarain); collapsed after Muhammad''s death 1206 (Delhi Sultanate fragment).' WHERE id = 509;

-- GOLDEN HORDE (3): all 3 are successors, no clear primary, fix all
UPDATE geo_entities SET
  boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(55.0, 47.0), 4326)::geography, 800000)::geometry)),
  boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(55.0, 47.0), 4326)::geography, 800000)::geometry),
  boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL,
  capital_lat = COALESCE(capital_lat, 47.0), capital_lon = COALESCE(capital_lon, 55.0),
  confidence_score = LEAST(confidence_score, 0.5),
  ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/horde-fix] Replaced erroneous Golden Horde polygon with 800km circle centered at (47°N, 55°E) — approximate center of Kazakh steppe (no fixed nomadic capital). Nogai Horde (Ногай Ордасы, 1390-1634) was a Mangit Tatar confederation between Volga + Irtysh + Caspian, originally part of Golden Horde, broke away under Edigu.'
WHERE id = 338;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/horde-fix] Replaced erroneous Golden Horde polygon with 250km circle around Kazan. Kazan Khanate (Казан ханлыгы, 1438-1552) was a successor of Golden Horde in middle Volga (Tatars, Mari, Chuvash); conquered by Ivan IV the Terrible 1552.' WHERE id = 330;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/horde-fix] Replaced erroneous Golden Horde polygon with 300km circle around Astrakhan. Astrakhan Khanate (Хаҗитархан ханлыгы, 1466-1556) was the southernmost successor of Golden Horde (lower Volga + Caspian coast); conquered by Ivan IV 1556 completing Russian control of Volga.' WHERE id = 333;

-- HITTITES (3): keep 172, fix 816 + 508
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-hittite-primary] LEGITIMATE Hittite Empire polygon (Hattusa-based 1600-1178 BCE). 2 successor/related states erroneously shared this — corrected.' WHERE id = 172;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/hittite-fix] Replaced erroneous Hittite polygon with 150km circle around Tarsos. 𐤊𐤋𐤊 = Que / Hiyawa / Adanawa — Iron Age Anatolian Cilician kingdom (1200 BCE - 67 BCE), successor to Hittite Empire; multiple phases (Neo-Hittite Que, Persian satrapy, Hellenistic, Roman annexation 67 BCE).' WHERE id = 816;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/hittite-fix] Replaced erroneous Hittite polygon with 80km circle around Carchemish. Karkamış (Carchemish, 1180-717 BCE) was a Neo-Hittite city-kingdom on the upper Euphrates after Bronze Age collapse; absorbed by Assyria 717 BCE under Sargon II.' WHERE id = 508;

-- MOCHE (3): keep 200, fix 656 + 971
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-moche-primary] LEGITIMATE Moche polygon. 2 cultures (Recuay, Gallinazo) erroneously shared this — corrected.' WHERE id = 200;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/moche-fix] Replaced erroneous Moche polygon with 80km circle. Recuay (-200 to 600 CE) was a N Peruvian highland Andean culture contemporary with Moche; capital Pashash in Callejón de Huaylas; known for stonework + ceramics.' WHERE id = 656;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/moche-fix] Replaced erroneous Moche polygon with 50km circle. Gallinazo / Virú (-200 to 600 CE) was a coastal Peruvian culture in Virú + Moche valleys, often considered Moche predecessor or contemporary; complex irrigation + ceramics.' WHERE id = 971;

-- OLMEC (3): keep 191, fix 923 + 924 (specific sites)
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-olmec-primary] LEGITIMATE Olmec cultural-region polygon. 2 specific sites (San Lorenzo, La Venta) erroneously shared this same polygon — now corrected to site-specific circles.' WHERE id = 191;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/olmec-fix] Replaced erroneous Olmec polygon with 30km circle. San Lorenzo Tenochtitlán (-1500 to -900) was the earliest major Olmec center in S Veracruz, famous for colossal heads; declined ~900 BCE in favor of La Venta.' WHERE id = 923;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/olmec-fix] Replaced erroneous Olmec polygon with 30km circle. La Venta (-900 to -400) was the second major Olmec ceremonial center, in Tabasco; pyramid + jaguar altars + colossal heads + offering deposits.' WHERE id = 924;

-- PAGAN (3): all 3 are post-Pagan kingdoms, no primary, fix all
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/pagan-fix] Replaced erroneous Pagan polygon with 300km circle. ဟံသာဝတီ (Hanthawaddy/Pegu, 1287-1539) was a Mon kingdom in Lower Burma after Pagan collapse, capital Bago/Pegu; absorbed by Toungoo 1539.' WHERE id = 690;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/pagan-fix] Replaced erroneous Pagan polygon with 150km circle. ပင်းယခေတ် (Pinya period, 1313-1364) was one of the Upper Burma successor kingdoms after Pagan fall, capital Pinya; rivaled Sagaing across the Irrawaddy; both absorbed by Ava 1364.' WHERE id = 696;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/pagan-fix] Replaced erroneous Pagan polygon with 150km circle. စစ်ကိုင်းခေတ် (Sagaing period, 1315-1364) was Shan-Burman successor kingdom Upper Burma capital Sagaing; rivaled Pinya across Irrawaddy; merged into Ava 1364.' WHERE id = 697;

-- PARTHIAN EMPIRE (3): keep 120, fix 624 + 821
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-parthian-primary] LEGITIMATE Parthian polygon. 2 vassal kingdoms erroneously shared this — corrected.' WHERE id = 120;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/parthian-fix] Replaced erroneous Parthian polygon with 120km circle. Characene (Μεσήνη / Charax Spasinou, 127 BCE - 222 CE) was a Persian Gulf maritime kingdom, Parthian vassal/semi-independent; controlled key trade route to India.' WHERE id = 624;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 180000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 180000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/parthian-fix] Replaced erroneous Parthian polygon with 180km circle. 𐡇𐡃𐡉𐡁 = Adiabene (69 BCE - 226 CE) was a Parthian vassal kingdom in N Mesopotamia (modern Erbil region), royal house converted to Judaism 1st c. CE.' WHERE id = 821;

-- PHRYGIANS (3): keep 813 Gordion, fix 815 (Lycia) + 189 (Lydia)
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-phrygian-primary] LEGITIMATE Phrygian polygon (Gordion-based -1200 to -547 BCE). 2 unrelated Anatolian kingdoms (Lycia, Lydia) erroneously shared this — corrected.' WHERE id = 813;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/phrygian-fix] Replaced erroneous Phrygian polygon with 120km circle. 𐊗𐊕𐊐𐊎𐊆𐊍𐊆 = Termilai = Lycia (-1400 BCE to 43 CE) was a federation of mountain city-states in SW Anatolia (Xanthos, Patara, Pinara, Tlos, Myra, Olympos, Phaselis); IE language Lycian; Roman annexation 43 CE.' WHERE id = 815;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/phrygian-fix] Replaced erroneous Phrygian polygon with 250km circle. Lydia (-1200 to -546 BCE) was a W Anatolian Iron Age kingdom centered on Sardis, Mermnad dynasty (Croesus 560-546 BCE) controlled most of Anatolia W of Halys until Persian conquest; invented first coinage.' WHERE id = 189;

-- POLYNESIANS (3): no clear primary, all Pacific island polities, fix all
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 10000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 10000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/polynesian-fix] Replaced erroneous Polynesians polygon with 10km circle. Rapa Nui (Easter Island, 1000-1888) was settled by Polynesians ~1000 CE, famous for moai stone heads + ecological collapse + birdman cult + small population in isolation; Chilean annexation 1888.' WHERE id = 302;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/polynesian-fix] Replaced erroneous Polynesians polygon with 40km circle. Mōʻī o Maui (Maui chief, 1300-1795) was the high chief lineage of Maui island under Pi''ilani dynasty; conquered by Kamehameha I 1790-1795 to unify Hawaii.' WHERE id = 749;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/polynesian-fix] Replaced erroneous Polynesians polygon with 80km circle. Maui Nui (1400-1795) was a unified kingdom of Maui + Molokai + Lanai + Kahoolawe under Pi''ilani; capital Wailuku Maui; absorbed into Kamehameha unification.' WHERE id = 635;

-- SULTANATE OF DELHI (3): keep 112, fix 598 + 599
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-delhi-primary] LEGITIMATE Delhi Sultanate polygon. 2 contemporary states (Malla dynasty Bengal, Kashmir Sultanate) erroneously shared this — corrected.' WHERE id = 112;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/delhi-fix] Replaced erroneous Delhi Sultanate polygon with 100km circle around Bishnupur. Malla dynasty (1070-1620) was a Hindu Vaishnava kingdom in W Bengal (Bishnupur), known for terracotta temples + classical music + autonomy under Mughal suzerainty.' WHERE id = 598;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/delhi-fix] Replaced erroneous Delhi Sultanate polygon with 150km circle around Srinagar. Kashmir Sultanate (1346-1589) was the Muslim sultanate of Kashmir Valley (Shah Mir + Chak dynasties); fell to Mughal Akbar 1589.' WHERE id = 599;

-- SUREN KINGDOM (3): keep 114 Kushan, fix 621 + 623
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-suren-primary] LEGITIMATE polygon for Kushan empire (related to Suren clan). 2 related kingdoms (Gandhara region, Indo-Parthian) erroneously shared this — corrected.' WHERE id = 114;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/suren-fix] Replaced erroneous Suren polygon with 250km circle around Peshawar. गन्धार (Gandhara, 600 BCE - 1021 CE) was a region/series of states in NW Indian subcontinent (modern Khyber Pakhtunkhwa + E Afghanistan); Mahājanapada period kingdom, then Persian/Greek/Maurya/Kushan; Gandhara Buddhist art.' WHERE id = 621;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/suren-fix] Replaced erroneous Suren polygon with 250km circle around Taxila. 𐭇𐭍𐭃𐭅𐭐𐭓𐭕 = Indo-Parthian Kingdom (19-226 CE) of Gondopharid dynasty (founded by Gondophares), capital Taxila; controlled parts of Iran + Afghanistan + Pakistan; absorbed by Kushans.' WHERE id = 623;

-- TOLTEC EMPIRE (3): keep 194 Tula, fix 930 + 926
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-toltec-primary] LEGITIMATE Toltec polygon (Tula-based). 2 city-states (Culhuacan, Cacaxtla) erroneously shared this — corrected.' WHERE id = 194;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/toltec-fix] Replaced erroneous Toltec polygon with 30km circle around Culhuacan. Culhuacan was an early-Post-classic Nahua city-state in southern Mexico Basin (~600-1430 CE), considered Toltec heir; provided dynastic legitimacy to later Aztec rulers.' WHERE id = 930;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/toltec-fix] Replaced erroneous Toltec polygon with 30km circle around Cacaxtla. Cacaxtla (650-1100 CE) was an Epiclassic city-state in Tlaxcala (central Mexico), famous for vivid Maya-style murals; possibly Olmec-Xicallanca (Putún Maya migrants).' WHERE id = 926;

-- UR (3): all 3 are Mesopotamian states, no primary (Ur itself is separate)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ur-fix] Replaced erroneous Ur polygon with 80km circle around Larsa. 𒌓𒀕𒆠 (Larsa, ~2025-1763 BCE) was a Sumerian/Amorite city-state in S Mesopotamia, rival of Isin during Isin-Larsa period; conquered by Hammurabi of Babylon 1763 BCE.' WHERE id = 809;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ur-fix] Replaced erroneous Ur polygon with 80km circle around Eshnunna. 𒌔𒂊𒂗𒈾 (Eshnunna, 2000-1762 BCE) was an Amorite city-state on the Diyala River (Tigris tributary), important Old Babylonian period; conquered by Hammurabi 1762 BCE; lawcode predates Hammurabi.' WHERE id = 810;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ur-fix] Replaced erroneous Ur polygon with 200km circle around Babylon. 𒀀𒈬𒊒𒌝 = Amorite Babylonia (Old Babylonian period 2000-1595 BCE), peak under Hammurabi (~1810-1750 BCE) who codified law + conquered Larsa+Eshnunna+Mari; sacked by Hittite raid 1595 BCE.' WHERE id = 619;

-- YEMEN (3): all 3 are successor Yemen sultanates, fix all
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/yemen-fix] Replaced erroneous Yemen polygon with 250km circle. Ayyubid Yemen (1174-1229) Turan-Shah brother of Saladin conquered Yemen; capital Zabid (Tihama lowlands); replaced by Rasulids 1229.' WHERE id = 510;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/yemen-fix] Replaced erroneous Yemen polygon with 300km circle. Rasulid Sultanate (بنو رسول, 1229-1454) was the peak medieval Yemeni state, capital Ta''izz; Sunni Shafi''i; promoted coffee trade + scholarship + agriculture; replaced by Tahirids 1454.' WHERE id = 495;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/yemen-fix] Replaced erroneous Yemen polygon with 150km circle. سلطنة عدن (Aden Sultanate, 1454-1517) was a Tahirid-era polity centered on Aden + S Yemen; commercial powerhouse on Red Sea/Indian Ocean trade; Mamluk + Ottoman + Portuguese intervention.' WHERE id = 512;

-- Verify
SELECT COUNT(*) as fixed_or_noted
FROM geo_entities WHERE id IN (31,480,474,847,497,490,877,878,879,663,665,584,328,339,458,143,477,509,338,330,333,172,816,508,200,656,971,191,923,924,690,696,697,120,624,821,813,815,189,302,749,635,112,598,599,114,621,623,194,930,926,809,810,619,510,495,512);

COMMIT;
