-- Boundary Review v6.99.79 — Tier 2 Batch 5: Remaining 2-entity collisions (40 entities)

BEGIN;

-- Polish-Lithuanian + Cossack Hetmanate (62/678)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/plc-fix] Polish-Lithuanian Commonwealth (1569 Union of Lublin - 1795 Third Partition) — peak ~1M km² covered modern Poland + Lithuania + Belarus + most of Ukraine + parts of Latvia + Estonia + Russia. Replaced shared polygon with 800km circle around Warsaw.' WHERE id = 62;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/hetmanate-fix] Cossack Hetmanate (Гетьманщина, 1649-1764) was a Ukrainian Cossack state founded by Bohdan Khmelnytsky after Khmelnytsky Uprising; Pereiaslav Agreement 1654 made it Russian protectorate; abolished by Catherine II 1764.' WHERE id = 678;

-- Seljuk + Crusader Edessa (122/473)
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-seljuk-note] LEGITIMATE Great Seljuk polygon. 473 Edessa (Crusader) erroneously shared this — corrected.' WHERE id = 122;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/edessa-fix] County of Edessa (Comitatus Edessanus, 1098-1144) was the first Crusader state, founded by Baldwin of Boulogne in Upper Mesopotamia; fell to Zengid Imad ad-Din 1144 triggering Second Crusade.' WHERE id = 473;

-- Ancestral Puebloans + Pueblo (204/223) — same culture different periods
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/puebloan-fix] Ancestral Puebloans (Anasazi tradition, 100 CE - 1280) covered Four Corners region of US Southwest, peak under Chaco Canyon + Mesa Verde phenomena. NOTE: same culture as Pueblo (id=223) but different period — duplicate consolidation candidate.' WHERE id = 204;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/pueblo-fix] Pueblo (-750 to present) Basketmaker through Pueblo IV phases of US Southwest indigenous peoples (Hopi, Zuni, Acoma, Tewa, Tiwa, Towa, Keres). Same continuous culture as Ancestral Puebloans (id=204); recommend merge.' WHERE id = 223;

-- Virreinato del Peru DUPLICATES (206/709)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/peru-fix] Viceroyalty of Peru (1542-1824) initial scope covered most of Spanish South America until subdivision into Río de la Plata (1776) + New Granada (1739). NOTE: id=709 is DUPLICATE (same dates/capital, just without Spanish accents).' WHERE id = 206;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/peru-fix] DUPLICATE of id=206 — recommend merge.' WHERE id = 709;

-- Virreinato Rio de la Plata DUPLICATES (213/710)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/rdp-fix] Viceroyalty of Río de la Plata (1776-1814) covered Argentina + Uruguay + Paraguay + Bolivia + parts of Brazil — created by Bourbon reforms separating from Peru. NOTE: id=710 is DUPLICATE (no accent variant).' WHERE id = 213;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/rdp-fix] DUPLICATE of id=213 — recommend merge.' WHERE id = 710;

-- Patagonia "Kingdom" + Mapuche (228/537)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.4), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/araucania-fix] Reino de la Araucanía y Patagonia (Kingdom of Araucanía & Patagonia, 1860-1862) was an unrecognized state proclaimed by French adventurer Antoine de Tounens with claimed Mapuche/Tehuelche support — never controlled territory; never internationally recognized. DISPUTED status; very low confidence.' WHERE id = 228;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/mapuche-fix] Reche / Mapuche people of S central Chile + SW Argentina (since at least -500 BCE) — held off Inca + Spanish conquest for ~350 years (1536-1883 Pacification of Araucanía). Heterogeneous confederations rather than unified state; ETHICS: dispossession ongoing.' WHERE id = 537;

-- Iran modern (251/252)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1000000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1000000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.85), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/pahlavi-fix] Pahlavi Iran (1925-1979) — Reza Shah modernization + Mohammad Reza Shah White Revolution; overthrown by Iranian Revolution 1979. Note: id=252 (Islamic Republic) shares same modern Iran polygon; different period.' WHERE id = 251;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1000000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1000000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.85), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/iri-fix] Islamic Republic of Iran (1979-present) — Khomeini-led theocratic republic; same modern Iran polygon as Pahlavi predecessor.' WHERE id = 252;

-- German East Africa + Karagwe (260/733)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/dse-fix] Deutsch-Ostafrika (German East Africa, 1885-1918) — covered modern Tanzania + Rwanda + Burundi + part of Mozambique; ETHICS: violent suppression of Maji Maji rebellion 1905-07 (75-300k African deaths); divided after WWI between British Tanganyika + Belgian Ruanda-Urundi.' WHERE id = 260;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/karagwe-fix] Karagwe was a kingdom of the Haya in NW Tanzania (Kagera region) on shore of Lake Victoria, founded around 1400 by Hinda dynasty; trading hub for ivory + iron + cattle; absorbed into German East Africa late 19th c.' WHERE id = 733;

-- Khazars duplicate (323/611)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/khazar-fix] Khazars Khaganate (650-969) — Turkic empire in Pontic-Caspian steppe; capital Atil; controlled Volga + Don + Crimea + parts of Caucasus; elite converted to Judaism 8th-9th c.; defeated by Sviatoslav I of Kiev 969. NOTE: id=611 is duplicate variant.' WHERE id = 323;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/khazar-fix] DUPLICATE of id=323 in Mongolian script — recommend merge.' WHERE id = 611;

-- Afghanistan successors (344/346)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/durrani-fix] Durrani Empire (1747-1823) founded by Ahmad Shah Durrani at Kandahar — peak under Ahmad Shah included Afghanistan + parts of Iran + Punjab + Kashmir + Sind; fragmented after his death; transformed into Emirate of Afghanistan 1823.' WHERE id = 344;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/afghanemir-fix] Emirate of Afghanistan (1823-1926, Kabul capital from 1776) — Barakzai dynasty; Anglo-Afghan Wars (1839-42, 1878-80, 1919); "Great Game" between Russia + Britain; transformed into Kingdom 1926.' WHERE id = 346;

-- Buyid duplicates (475/494)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/buyid-fix] Buyid dynasty (آل بویه, 934-1062) — Shia Iranian Daylamite dynasty controlling Iran + Iraq from Persian Gulf coast to Caspian; held Abbasid Caliphs as puppets in Baghdad 945-1055; conquered by Seljuks. NOTE: id=494 is duplicate (Arabic script variant آل بويه vs Persian آل بویه).' WHERE id = 475;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/buyid-fix] DUPLICATE of id=475 — recommend merge.' WHERE id = 494;

-- Maghreb dynasties (478/987, 483/484, 486/487)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/idrisid-fix] Idrisid dynasty (788-974) — first Shia Islamic dynasty in Morocco, founded by Idris I after escape from Abbasid persecution; capital Fez; absorbed by Fatimids + Umayyads of Cordoba.' WHERE id = 478;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/barghawata-fix] Barghawata Confederation (744-1058) — Berber heterodox Islamic confederation on Moroccan Atlantic coast; own scripture + prophet Salih ibn Tarif; eventually absorbed by Almoravids.' WHERE id = 987;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/hafsid-fix] Hafsid dynasty (1229-1574) — Tunisian dynasty initially Almohad governors, declared independence after Almohad collapse; covered Ifriqiya (Tunisia + E Algeria + Tripolitania); peak 14th c.; ended by Ottoman conquest 1574.' WHERE id = 483;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/zayyanid-fix] Zayyanid dynasty (1235-1556, also Abdalwadid) — Zenata Berber dynasty of central Maghreb (modern W Algeria), capital Tlemcen; squeezed between Hafsids + Marinids; eventually conquered by Ottomans.' WHERE id = 484;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/cordoba-fix] Caliphate of Cordoba (929-1031) — Umayyad caliphate of Al-Andalus declared by Abd al-Rahman III, peak Iberian Muslim state; cultural + scientific golden age; fragmented into Taifa kingdoms 1031.' WHERE id = 486;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/taifa-fix] Taifa Kingdoms (ملوك الطوائف, 1009-1110) — fragmented successor states of Caliphate of Cordoba (Sevilla, Granada, Toledo, Zaragoza, Badajoz, Valencia, etc.); cultural flourishing + political weakness invited Almoravid invasion 1086-90.' WHERE id = 487;

-- Hashemite Hijaz duplicate (489/500)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/hijaz-fix] Hashemite Kingdom of Hijaz (1916-1925) — Sharif Hussein bin Ali declared independence from Ottoman Empire during Arab Revolt (WWI); covered Hijaz coast + Mecca + Medina + Jeddah; conquered by Ibn Saud 1925 (Saudi Arabia). NOTE: id=500 is duplicate variant (word order).' WHERE id = 489;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/hijaz-fix] DUPLICATE of id=489 — recommend merge.' WHERE id = 500;

-- Sahel (555 Bagirmi, 841 Teda)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/bagirmi-fix] Bagirmi was a Sahelian Islamic kingdom (1522-1897) in modern Chad, between Lake Chad + Chari River; capital Massenya then Bakara; conquered by Rabih az-Zubayr 1893, then French 1897.' WHERE id = 555;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/teda-fix] Teda (Tubu) confederation — Nilo-Saharan speakers of Tibesti Mountains + Borkou + Ennedi (N Chad + S Libya); pastoral nomadic confederation with caravan trade; never unified into single state; later targets of French/Italian colonialism.' WHERE id = 841;

-- Indian (588/589)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/chalukya-fix] Western Chalukya Empire (Kalyani Chalukyas, 973-1189) — Karnataka-based Deccan empire successor to Rashtrakutas; capital Manyakheta then Kalyani; conflict with Cholas + Hoysalas; literature in Kannada flourished.' WHERE id = 588;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/yadava-fix] Seuna Yadava dynasty (850-1334) — Marathi Deccan empire, capital Devagiri (modern Daulatabad); peak 13th c. controlled most of modern Maharashtra + N Karnataka + S Gujarat + parts of MP/AP; conquered by Delhi Sultanate (Khilji).' WHERE id = 589;

-- W African (851 Oyo, 852 Sokoto)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/oyo-fix] Oyo Empire (1300-1896) — Yoruba empire in SW Nigeria, peak 17th-18th c.; major slave-trade participant; capital Oyo-Ile; civil war + Fulani jihad caused decline; British annexation 1896.' WHERE id = 851;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/sokoto-fix] Sokoto Caliphate (Daular Usmaniyya, 1804-1903) — Fulani jihad state founded by Uthman dan Fodio; covered most of N Nigeria + parts of Cameroon, Niger, Burkina Faso; sub-emirates; largest African state of 19th c.; conquered by British 1903.' WHERE id = 852;

-- Andean (970 Salinar coast, 972 Tiahuanaco highland) — different geographies
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/salinar-fix] Salinar culture (-400 to 200 CE) was a N Peruvian coastal Andean culture (Virú+Chicama+Moche valleys), Early Intermediate Period predecessor to Moche; iron-rich Salinar pottery; absorbed by Moche.' WHERE id = 970;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/yayamama-fix] Tiahuanaco-Chiripa-Pukara (Yaya-Mama horizon, ~800-200 BCE) was a religious tradition around Lake Titicaca (Bolivia + Peru highlands), predecessor of Tiwanaku state; stone stelae with feline/serpent/anthropomorphic iconography.' WHERE id = 972;

-- W African (983/984)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/kaabu-fix] Kaabu Empire (Nsiiw, 1200-1867) was a Mandinka kingdom in modern Guinea-Bissau + Senegal + Gambia, founded as Mali Empire province; capital Kansala; ended by Fulani jihad (Kansala destroyed 1867).' WHERE id = 983;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/dyolof-fix] Dyolof / Jolof confederation (pre-1549) — Wolof confederation in N Senegal, founded ~14th c.; fragmented in 1549 (Battle of Danki) into independent Wolof kingdoms (Kayor, Saalum, Siin, etc.) — see ids 728,742,843,563.' WHERE id = 984;

-- Verify
SELECT COUNT(*) FROM geo_entities WHERE id IN (62,678,122,473,204,223,206,709,213,710,228,537,251,252,260,733,323,611,344,346,475,494,478,987,483,484,486,487,489,500,555,841,588,589,851,852,970,972,983,984);

COMMIT;
