-- Boundary Review v6.99.79 — Tier 3: Final outlier fixes
-- 9 high-certainty bugs (broad-culture/empire polygons mismatched to specific sub-entities)

BEGIN;

-- 795 Kuhikugu (Amazon urban settlement, not hunter-gatherer)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/kuhikugu-fix] Replaced erroneous "Amazon hunter-gatherers" cultural polygon (262 deg²) with 50km circle. Kuhikugu was an urban Upper Xingu site complex (1000-1500 CE) discovered by Heckenberger — pre-Columbian settlements with plazas, roads, agriculture. Not hunter-gatherer; sedentary garden urbanism.'  WHERE id = 795;

-- 992 Thulamela (Venda/Karanga chiefdom, not Mwenemutapa proper)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/thulamela-fix] Replaced erroneous Mwenemutapa polygon (42 deg²) with 30km circle. Thulamela (1240-1640) was a Karanga/Venda stone-walled hilltop site in modern Kruger National Park (NE South Africa); successor of Mapungubwe; trade with Swahili coast.' WHERE id = 992;

-- 504 الخمیون Lakhmids (Arab vassals of Sasanians, not the Empire)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/lakhmid-fix] Replaced erroneous Sasanian Empire polygon (339 deg²) with 250km circle around al-Hira. Lakhmids (300-602 CE) were an Arab Christian dynasty client of Sasanians, controlled lower Mesopotamia + N Arabian frontier; rival of Ghassanid Byzantine clients; capital al-Hira; abolished by Khosrow II 602.' WHERE id = 504;

-- 674 Theloal (US Southeast site, NOT entire "Eastern NA hunter-gatherers")
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/theloal-fix] Replaced erroneous "Eastern North American hunter-gatherers" polygon (376 deg²) with 100km circle. Theloal/Natchez chiefdom (700-1729 CE) was a Mississippian-derived hierarchical society on the lower Mississippi River; capital Grand Village near modern Natchez MS; destroyed by French 1729-31.' WHERE id = 674;

-- 1027 Yoruba early polities (specific kingdoms, NOT all West African farmers)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/yoruba-fix] Replaced erroneous "West African cereal farmers" cultural polygon (403 deg²) with 250km circle. Yoruba early polities (1000-1500 CE) refers to Ile-Ife + Oyo + Ondo + Ijesa + Owo + Ekiti city-states in SW Nigeria; sophisticated bronze + stone urban civilization with shared cosmology.' WHERE id = 1027;

-- 896 Qocho Uyghur (NW China, NOT Cuman-Kipchak!)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/qocho-fix] Replaced erroneous Cuman-Kipchak polygon (764 deg², in Eurasian steppe!) with 300km circle around Qocho/Karakhoja. قۇچۇ Qocho (Idiqut, 856-1335) was a Uyghur Buddhist kingdom in Turfan Basin (E Xinjiang) after Uyghur Khaganate collapse 840; Manichean+Buddhist+Nestorian; absorbed into Chagatai Khanate.' WHERE id = 896;

-- 468 Later Zhao (319-351, N China, NOT same as Jin)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/laterzhao-fix] Replaced erroneous Jin polygon with 600km circle. 後趙 Later Zhao (319-351 CE) was a Jie Xiongnu-founded Chinese kingdom (Shi Le→Shi Hu) during 16 Kingdoms period, controlled most of N China at peak; collapsed in succession wars.' WHERE id = 468;

-- 632 Cimmerians (nomadic, but bounded)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/cimmerian-fix] Replaced erroneous polygon with 600km circle around Crimea. Cimmerians (Κιμμέριοι, -1100 to -650 BCE) were nomadic Iranic/Indo-European steppe people of N Pontic-Caspian region; displaced southward by Scythians; raided Anatolia + Urartu + Phrygia; final defeats by Lydia + Assyria.' WHERE id = 632;

-- 541 Aonikenk Tehuelche (Patagonian nomads — keep large as semi-nomadic)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/tehuelche-fix] Replaced erroneous polygon with 700km circle. Aonikenk (Tehuelche, since ~8000 BCE) were indigenous semi-nomadic guanaco-hunting peoples of Patagonia from Río Negro to Tierra del Fuego; horse adoption 18th c. transformed culture; population devastated by 19th c. Argentine + Chilean Conquista del Desierto. ETHICS: ongoing land claims by descendants.' WHERE id = 541;

-- ETHICS RECORDS for type-mismatch entities (NOT changing polygon, just adding note)

-- 277 Harappa — civilization, not city-state
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-harappa-ethics] Entity_type "city-state" is HISTORICALLY INACCURATE — Indus Valley Civilization (-3300 to -1300 BCE) was a CIVILIZATION with 1000+ sites + 5M+ population at peak across 1.25M km² of modern Pakistan + NW India + parts of Afghanistan + Iran. Should be classified as "civilization" entity_type. Area 124 deg² polygon reflects actual extent but classification is wrong. Manual reclassification recommended.' WHERE id = 277;

-- 309 Aboriginal Australian Nations — 250+ separate nations, not single confederation
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-australia-ethics] Entity classification "Aboriginal Australian Nations" as single confederation is HISTORICALLY INACCURATE and ETHNOGRAPHICALLY PROBLEMATIC. Aboriginal Australians comprise 250+ distinct nations with separate languages, songlines, custodial relationships to country (Pintupi, Yolŋu, Noongar, Pitjantjatjara, Warlpiri, Arrernte, Eora, Wiradjuri, Murawari, etc.). ETHICS: representing them as one polygon erases this diversity. Some specific nations are tracked separately (Noongar id=771, Wiradjuri id=772, Yolŋu id=311, Kulin id=310, Torres Strait id=308). Polygon should remain as continental marker but specific nations need disaggregation. Manual review recommended.' WHERE id = 309;

-- Verify
SELECT COUNT(*) FROM geo_entities WHERE id IN (795, 992, 504, 674, 1027, 896, 468, 632, 541, 277, 309);

COMMIT;
