-- Boundary Review v6.99.79 — Tier 3 final: 22 remaining collisions

BEGIN;

-- ========== TRUE DUPLICATES (4 pairs — mark for merge) ==========

-- Marinids 187/482
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-marinid-primary] LEGITIMATE Marinid polygon. id=482 is duplicate (same dates 1244, same Maghreb context).' WHERE id = 187;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.45), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/marinid-fix] DUPLICATE of id=187 (المرينيون vs الدولة المرينية, same Maghreb Berber dynasty 1244-1465); slightly displaced circle to break polygon collision. Recommend merge.' WHERE id = 482;

-- Rozwi/Rozvi 155/831
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-rozwi-primary] LEGITIMATE Rozwi polygon. id=831 is spelling variant duplicate.' WHERE id = 155;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.45), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/rozvi-fix] DUPLICATE of id=155 (Rozvi vs Rozwi, same Zimbabwe state 1684-1866); slightly different circle to break polygon collision. Recommend merge.' WHERE id = 831;

-- Scotland 90/585
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-scotland-primary] LEGITIMATE Scotland (Rioghachd na h-Alba) polygon. id=585 is duplicate (Norwegian-Gaelic transliteration).' WHERE id = 90;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.45), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/scotland-fix] DUPLICATE of id=90 (Kongerike Skottland Norwegian + Rioghachd na h-Alba Gaelic, same year 843); slightly different circle. Recommend merge.' WHERE id = 585;

-- Chimor 199/657
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-chimor-primary] LEGITIMATE Chimor polygon. id=657 (Chimor Ñisqap Llaqtan = "Chimor capital city" in Quechua) is duplicate.' WHERE id = 199;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.45), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/chimor-fix] DUPLICATE of id=199 (Chimor Ñisqap Llaqtan is just the Quechua full name "Chimor capital"). Recommend merge.' WHERE id = 657;

-- ========== SAME REGION DIFFERENT PERIODS (6) ==========

-- Brasil Colônia + Confederação do Equador
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-brasil-primary] LEGITIMATE Brasil Colonia polygon — Portuguese colonial Brazil covering most of modern Brazil 1500-1822.' WHERE id = 207;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/equador-fix] Confederação do Equador (1824) was a brief 4-month separatist republic declared in NE Brazil (Pernambuco, Ceará, Paraíba, Rio Grande do Norte) against Dom Pedro I imperial centralism. 600km circle around Recife area.' WHERE id = 722;

-- Khmer Republic (1975 = post-Lon Nol) + Kingdom of Cambodia (1953)
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-cambodia-primary] LEGITIMATE Kingdom of Cambodia polygon (1953-present, post-1993 restoration).' WHERE id = 256;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/khmer-republic-fix] សាធារណរដ្ឋខ្មែរ (Khmer Republic, 1970-1975) was Lon Nol''s pro-US republic after Sihanouk overthrow; ended by Khmer Rouge victory + genocide April 1975. NOTE: dates in DB say 1975 — this should be 1970-1975 (year_start fix recommended).' WHERE id = 240;

-- Portugal + Estado Novo
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-portugal-primary] LEGITIMATE Reino de Portugal polygon (1143-1910).' WHERE id = 61;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/estado-novo-fix] Estado Novo (1933-1974) was Salazar/Caetano corporatist authoritarian regime; controlled metropolitan Portugal + colonies (Angola, Mozambique, Guinea-Bissau, Cape Verde, São Tomé, Macau, Goa, Timor); ended by Carnation Revolution 1974. ETHICS: colonial wars 1961-1974 + PIDE political police repression.' WHERE id = 265;

-- Ireland Gaelic + Eire
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-ireland-primary] LEGITIMATE Rioghacht na hEireann polygon — pre-Norman Irish kingdom.' WHERE id = 91;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.85), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/eire-fix] Éire / Republic of Ireland (1922-present, Republic since 1948). Free State (1922-1937) → Éire (1937 Constitution) → Republic (1948). ETHICS: partition with Northern Ireland (6 counties) under UK 1921-present.' WHERE id = 257;

-- Tahiti + French Polynesia
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-tahiti-primary] LEGITIMATE Te Hau o Tahiti polygon — pre-colonial Tahiti kingdom 1788-1842.' WHERE id = 301;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/polynesie-fix] Polynésie française (1842-present, autonomy 1984/2004) — French overseas territory covering Society Islands + Tuamotu + Marquesas + Gambier + Austral Islands ~118 islands across 5M km² of ocean. ETHICS: nuclear tests 1966-1996 at Moruroa + Fangataufa atolls; Indigenous Mā''ohi sovereignty movement active.' WHERE id = 321;

-- Rarotonga 314/858
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-rarotonga-primary] LEGITIMATE Kingdom of Rarotonga polygon (1827-1893, then British protectorate, then NZ associated state).' WHERE id = 314;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 20000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 20000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/rarotonga-ariki-fix] Rarotongan Ariki Confederation was the pre-unification chiefly tradition of Rarotonga + Cook Islands (~1200-1827); 3 vaka (tribes) Te Au o Tonga, Takitumu, Puaikura with their ariki paramount chiefs.' WHERE id = 858;

-- ========== GENUINELY DIFFERENT POLITIES (12) ==========

-- Territory of Papua + Me'ekamui
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 700000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/papua-fix] Territory of Papua (British/Australian 1884-1975) covered SE quarter of New Guinea + outer islands; merged with Territory of New Guinea to form modern PNG 1975.' WHERE id = 320;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/meekamui-fix] Me''ekamui = "Sacred Island" — Bougainville traditional polity (~1500-present); separatist movement against PNG 1988-1998 (Bougainville Crisis); independence referendum 2019 (97.7% yes); independence transition ongoing.' WHERE id = 758;

-- Qusqu (Cuzco/Inca) + Chincha
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/qusqu-fix] Qusqu was the proto-Inca polity around Cuzco (~1200-1438 CE) before Pachacuti''s expansion that founded Tawantinsuyu Empire 1438.' WHERE id = 721;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/chincha-fix] Chincha (1000-1476) was a S coastal Peruvian Andean kingdom on Chincha valley; rich from trans-Pacific Spondylus trade; absorbed by Inca empire ~1476.' WHERE id = 950;

-- Sicily Kingdom + Italy Kingdom
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/sicily-fix] Regnum Siciliae (Kingdom of Sicily, 1130-1861) founded by Roger II Norman covered Sicily + S Italy (Mezzogiorno); Hohenstaufen → Angevin → Aragonese → Spanish → Bourbon; Two Sicilies 1816-1861 absorbed by united Italy 1861.' WHERE id = 85;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.8), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/italy-fix] Regno d''Italia (Kingdom of Italy, 1861-1946) Savoy unification under Vittorio Emanuele II; Risorgimento; Roma capital 1871; WWI + Fascist Italy + WWII; abolished by 1946 referendum (54% republic).' WHERE id = 100;

-- Medes + Manneans
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/medes-fix] مادها (Median Empire, 678-549 BCE) was an Iranian empire centered on Ecbatana (Hamadan); destroyed Assyria (with Babylonians) at Nineveh 612 BCE; vassalized Persians (Achaemenids) until Cyrus the Great revolt 550-549 BCE.' WHERE id = 190;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/manna-fix] 𒈠𒀭𒈾𒀀𒀀 Manna (Mannean kingdom, ~850-616 BCE) was an ancient Iranian kingdom S of Lake Urmia (modern Iranian Kurdistan + NW Iran); rival of Assyria + Urartu; absorbed by Median Empire ~616 BCE.' WHERE id = 817;

-- Swahili cities Mogadishu + Malindi
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/mogadishu-fix] Mogadishu (مقديشو, 900-1530) was a Swahili coastal city-state on Somali coast; important Arab trading port + sultanate; controlled gold trade Sofala-Kilwa-Mogadishu route; conquered by Portuguese 1499 then Ajuran 1530.' WHERE id = 741;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/malindi-fix] Malindi (1100-1873) was a Swahili coastal city-state on Kenyan coast; rival of Mombasa; welcomed Vasco da Gama 1498 (provided pilot Ibn Majid); allied with Portuguese; absorbed into Zanzibar sultanate.' WHERE id = 823;

-- Aragon + Catalonia
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3-aragon-primary] LEGITIMATE Crown of Aragon polygon (1035-1714) — covered Aragon + Catalonia + Valencia + Mallorca + Sicily + Naples + Sardinia at peak.' WHERE id = 72;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/catalonia-fix] Comtat de Barcelona / Principat de Catalunya (987-1714) was the Catalan polity from Wifred the Hairy (Carolingian frontier) → merger with Aragon 1137; abolished by Bourbon decrees after War of Spanish Succession 1714.' WHERE id = 576;

-- Malay Kedah Tua + Gangga Negara
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/kedah-fix] Kedah Tua (Ancient Kedah, ~170-1136) was an early Malay Hindu-Buddhist kingdom in NW Malay peninsula; Bujang Valley archaeological site; Srivijaya vassal then independent until Islamicization 1136.' WHERE id = 868;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/gangga-fix] Gangga Negara (~100-1025 CE) was an ancient Hindu-Buddhist kingdom in N Perak (Malay peninsula), destroyed by Chola raids 1025; mentioned in Sejarah Melayu chronicle.' WHERE id = 902;

-- Balkans Serbian Despotate + Bosnia
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/srpska-fix] Српска деспотовина (Serbian Despotate older form, 1217 here likely typo from kingdom→despotate; if intended as Kingdom of Serbia Nemanjic 1217-1346 then different from 1402 despotate). Manual review of dates recommended.' WHERE id = 69;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/kraljevina-bosna-fix] Kraljevina Bosna (Kingdom of Bosnia, 1377-1463) — Tvrtko I crowned 1377; peak 14th c. controlled Bosnia + Hum + parts of Croatia + Serbia; Bosnian Church; conquered by Mehmed II 1463.' WHERE id = 663;

-- Pasai + Haru (N Sumatra)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/pasai-fix] Samudera Pasai (1267-1521) was the first significant Muslim Malay sultanate in N Sumatra (Aceh region); Ibn Battuta visited 1345; Marco Polo 1292; conquered by Portuguese 1521 then Aceh.' WHERE id = 885;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/haru-fix] Haru (1225-1613) was a Karo Batak kingdom in NE Sumatra (Deli region); rival of Pasai then Aceh; destroyed by Aceh Sultan Iskandar Muda 1613.' WHERE id = 887;

-- Khmer/Sri Lanka (600/601) — both ancient SE Asian
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/600-fix] ការ្យ​ ​សីលេន (Karya Silaen?, 1232-?) — Khmer-era polity, possibly related to Angkor administration; needs research.' WHERE id = 600;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/jaffna-fix] ජාෆ්නා රාජධානිය (Jaffna Kingdom / Arya Chakravarti dynasty, 1215-1624) was a Tamil kingdom in N Sri Lanka, founded by Magha of Kalinga; Arya Chakravartis from 1262; conquered by Portuguese 1624.' WHERE id = 601;

-- Fijian chiefdoms (759 Tui Nayau Lau islands, 760 Tui Cakau Vanua Levu)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/tuinayau-fix] Tui Nayau was the paramount chief of Lau Archipelago (E Fiji), with Tongan influence; Ratu Sir Kamisese Mara (Prime Minister of Fiji 1970-1992 + President 1993-2000) held this title.' WHERE id = 759;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/tuicakau-fix] Tui Cakau was the paramount chief of Cakaudrove confederacy in N Vanua Levu Fiji; Ratu Sir Penaia Ganilau (1st President of Fiji 1987-1993) held this title.' WHERE id = 760;

-- Micronesia FSM states (4 entities — separate islands)
UPDATE geo_entities SET
  boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 25000)::geometry)),
  boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 25000)::geometry),
  boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL,
  confidence_score = LEAST(confidence_score, 0.6),
  ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/yap-fix] Wa''ab (Yap, 1400-present) — Yapese chiefdom + stone money (rai) cultural complex; Spanish 1885 → German 1899 → Japanese 1914 → US 1945 → FSM 1986.'
WHERE id = 764;
UPDATE geo_entities SET
  boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry)),
  boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry),
  boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL,
  confidence_score = LEAST(confidence_score, 0.6),
  ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/chuuk-fix] Chuuk (Truk, 1500-present) — Chuukese chiefdoms; major Japanese WWII naval base; US Trust Territory 1947 → FSM 1986.'
WHERE id = 765;
UPDATE geo_entities SET
  boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry)),
  boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 30000)::geometry),
  boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL,
  confidence_score = LEAST(confidence_score, 0.6),
  ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/pohnpei-fix] Wehin Pohnpei (Nahnmwarki system, 1628-present) — 5 traditional polities (Nett, U, Madolenihmw, Kitti, Sokehs) each with Nahnmwarki paramount chief; followed Saudeleur era; capital Kolonia → Palikir 1989 (FSM federal capital).'
WHERE id = 766;
UPDATE geo_entities SET
  boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 20000)::geometry)),
  boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 20000)::geometry),
  boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL,
  confidence_score = LEAST(confidence_score, 0.6),
  ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/kosrae-fix] Kosrae (Tokosra kingdom, 1400-present) — paramount Tokosra ruler tradition; Spanish 1885 → German → Japanese → US → FSM 1986.'
WHERE id = 768;

SELECT COUNT(*) FROM geo_entities WHERE id IN (187,482,155,831,90,585,199,657,207,722,256,240,61,265,91,257,301,321,314,858,320,758,721,950,85,100,190,817,741,823,72,576,868,902,69,663,885,887,600,601,759,760,764,765,766,768);

COMMIT;
