-- Boundary Review v6.99.79 — Tier 2 Batch 4: small natural_earth + top 2-entity collisions

BEGIN;

-- ========== SMALL NATURAL_EARTH GROUPS ==========

-- BOHEMIA (97 Czech, 586 Danish "Bohemia" - dup, 680 Moravia)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/bohemia-fix] Replaced erroneous shared polygon with 200km circle around Praha. Kralovstvi ceske = Kingdom of Bohemia (Czech, 1198-1918) — HRE elector, peak under Premysl Otakar II + Charles IV (Luxembourg); part of Habsburg lands 1526; ended with WWI.' WHERE id = 97;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/bohemia-fix] Replaced erroneous shared polygon with 200km circle. Kongeriget Bohmen is DUPLICATE of id=97 (same dates/capital, just Danish-language transliteration). Recommend merge.' WHERE id = 586;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 100000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/bohemia-fix] Replaced erroneous shared polygon with 100km circle. Margraviate of Moravia (Markgrafschaft Maehren, 1182-1918) was a separate margraviate east of Bohemia, part of Lands of the Bohemian Crown; capital Brno; absorbed into Czechoslovakia 1918.' WHERE id = 680;

-- CENTRAL AMERICA (214, 711 dup, 724 Federal Republic)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ca-fix] Replaced erroneous shared polygon with 600km circle. Capitanía General de Guatemala (1609-1821) covered most of modern Central America (Guatemala, Honduras, El Salvador, Nicaragua, Costa Rica) + Chiapas; Spanish colonial administrative unit under Viceroyalty of New Spain.' WHERE id = 214;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ca-fix] Replaced erroneous shared polygon with 600km circle. DUPLICATE of id=214 (same dates 1609, same capital, just removed Spanish accents). Recommend merge.' WHERE id = 711;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ca-fix] Replaced erroneous shared polygon with 500km circle. Federal Republic of Central America (1823-1841) was the brief federation of Guatemala+El Salvador+Honduras+Nicaragua+Costa Rica after independence from Spain+Mexico; dissolved into separate republics through 1838-1841 civil war.' WHERE id = 724;

-- CONGO COAST KINGDOMS (645 Teke, 731 Loango, 838 Ngoyo)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/congo-coast-fix] Replaced erroneous shared polygon with 200km circle. Nsi a Teke (Teke kingdom, 1400-1880) was a Bateke Bantu kingdom on the plateau N of Stanley Pool (Congo River); famous for trade with Portuguese + later French colonial conflict; Brazza''s 1880 treaty.' WHERE id = 645;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/congo-coast-fix] Replaced erroneous shared polygon with 150km circle. Nsi a Luangu (Loango kingdom, 1550-1883) was a Vili kingdom N of Kingdom of Kongo, on Atlantic coast (modern Republic of Congo + Cabinda); maritime trade with Portuguese + Dutch + French.' WHERE id = 731;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/congo-coast-fix] Replaced erroneous shared polygon with 80km circle. Ngoyo (1600-1885) was a small Vili kingdom around modern Cabinda (Angola enclave); slave trade port; Portuguese protectorate 1885.' WHERE id = 838;

-- FIJI GROUP 1 (637 Mata-nitu, 761 Verata, 762 Rewa)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/fiji-fix] Replaced erroneous shared Fiji polygon with 80km circle around Bau. Mata-nitu o Viti (1200-1874) Bauan confederation of Fijian chiefdoms in E Viti Levu; capital Bau Island; pre-Cakobau era political alliance.' WHERE id = 637;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/fiji-fix] Replaced erroneous shared Fiji polygon with 40km circle. Vanua ko Verata (1500-1869) was a Fijian chiefdom on Tailevu coast (Viti Levu E coast); rival of Bau before Cakobau era.' WHERE id = 761;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/fiji-fix] Replaced erroneous shared Fiji polygon with 40km circle. Burebasaga / Rewa (1600-1874) was the Rewa chiefdom in S Viti Levu, one of the 3 major confederacies (matanitu) of pre-colonial Fiji; capital Lomanikoro.' WHERE id = 762;

-- FIJI GROUP 2 (299 Cakobau, 300 Bose Levu, 763 Nakauvadra)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/fiji-fix] Replaced erroneous shared polygon with 150km circle. Malo ni Viti (Kingdom of Fiji under Cakobau, 1815-1874) — Cakobau (Seru Epenisa) unified most of Fiji as Tui Viti; ceded to Britain 1874.' WHERE id = 299;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/fiji-fix] Replaced erroneous shared polygon with 250km circle. Bose Levu Vakaturaga (Great Council of Chiefs, 1874-2012) was the colonial-era + post-independence advisory body of Fijian chiefs; covered all Fiji; disestablished by Bainimarama government.' WHERE id = 300;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.5), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/fiji-fix] Replaced erroneous shared polygon with 40km circle. Nakauvadra is a mountain range in Ra Province (N Viti Levu), traditional homeland of Fijian gods + ancestors in Fijian cosmology — cultural-religious region rather than political polity.' WHERE id = 763;

-- ========== TOP 2-ENTITY COLLISIONS (most impactful, very different geographies) ==========

-- 211 Confederate States + 547 California Republic — both got USA polygon
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/csa-fix] Replaced erroneous USA polygon with 800km circle around Richmond. Confederate States of America (1861-1865) was 11 seceded slave states (SC, MS, FL, AL, GA, LA, TX, VA, AR, TN, NC) — fought Civil War to defend slavery; defeated; ETHICS: Confederacy''s explicit founding principle was preservation of chattel slavery (Cornerstone Speech, A.H. Stephens 1861).' WHERE id = 211;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.55), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/calirep-fix] Replaced erroneous USA polygon with 60km circle around Sonoma. California Republic (Bear Flag Republic, June-July 1846) was a 25-day unrecognized polity declared by American settlers in Sonoma during the Mexican-American War, before US Army arrival.' WHERE id = 547;

-- 238 PRC + 243 RoC — share modern China polygon. RoC after 1949 is just Taiwan
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-prc-note] LEGITIMATE PRC polygon (post-1949 mainland China). RoC (id=243) erroneously shares this — corrected.' WHERE id = 238;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 800000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/roc-fix] Replaced erroneous mainland-China polygon with 800km circle around Nanjing. 中華民國 = Republic of China (1912-present) — controlled mainland 1912-1949, then Taiwan + outlying islands. ETHICS: This entity spans both republican mainland China (1912-1949 Beijing/Nanjing govt) AND Taiwan-based ROC (1949-) — these have very different geographies. Consider splitting into two entities.' WHERE id = 243;

-- 454 Nanzhao (Yunnan) + 897 Ganzhou Uyghur (NW China) — TOTALLY different regions!
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/nanzhao-fix] Replaced erroneous shared polygon (id=454 and id=897 share polygon despite being in completely different regions) with 400km circle. 南詔 (Nanzhao, 738-902) was a Tibeto-Burman kingdom in Yunnan + adjacent Burma + N Vietnam + Laos; rival of Tang China; successor was Dali Kingdom.' WHERE id = 454;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ganzhou-fix] Replaced erroneous shared polygon (geography mismatch with id=454 Nanzhao in Yunnan) with 200km circle. 甘州回鶻 (Ganzhou Uyghur Kingdom, 848-1036) was a NW Chinese kingdom in Hexi Corridor (Gansu), founded by Uyghurs after Tang collapse; conquered by Western Xia 1036.' WHERE id = 897;

-- 78 Moscow Principality + 327 Golden Horde — VERY different geographies
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/moscow-fix] Replaced erroneous polygon (shared with Golden Horde despite different geography) with 250km circle. Великое княжество Московское (Grand Duchy of Moscow, 1263-1547) — initial appanage of Vladimir-Suzdal Rurikids, expanded under Ivan I-III; throwing off Tatar yoke 1480; transformed into Tsardom 1547.' WHERE id = 78;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 1500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/horde-fix] Replaced erroneous polygon with 1500km circle. Алтын Орда (Golden Horde, 1240s-1502) was the NW khanate of the Mongol Empire — controlled Russian principalities, Volga, Caucasus, much of Central Asia; capital Sarai (lower Volga). Use Sarai approximate at ~Astrakhan latitude.' WHERE id = 327;

-- 126 Ryukyu + 461 Ainu Mosir — TOTALLY different (Okinawa vs Hokkaido)
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 300000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ryukyu-fix] Replaced erroneous polygon (shared with Ainu Mosir of Hokkaido despite being in southern Japan!) with 300km circle. 琉球國 (Ryukyu Kingdom, 1429-1879) was an island kingdom in S Japan/Okinawa archipelago; tributary state of Ming/Qing China + Satsuma Japan vassal 1609; annexed by Meiji Japan 1879.' WHERE id = 126;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/ainu-fix] Replaced erroneous polygon (shared with Ryukyu Kingdom in southern Japan!) with 250km circle. アイヌモシㇼ (Ainu Mosir, "Ainu homeland") covered Hokkaido + S Sakhalin + Kuril Islands + N Honshu — Ainu indigenous peoples; gradually colonized by Yamato Japan from N Honshu southward over centuries; ETHICS: Ainu underwent forced assimilation policies under Meiji Japan (1868-).' WHERE id = 461;

-- 105 Tang + 451 Five Dynasties — different periods of Chinese history
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-tang-note] LEGITIMATE Tang Empire polygon (618-907). 5 Dynasties (id=451) erroneously shared this — corrected.' WHERE id = 105;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 600000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/fivedynasties-fix] Replaced erroneous Tang polygon with 600km circle. 五代 (Five Dynasties period, 907-960) was the interregnum between Tang and Song — 5 short-lived dynasties in N China (Liang/Tang/Jin/Han/Zhou) + 10 contemporary southern kingdoms; ended by Song unification.' WHERE id = 451;

-- 350 Bactria + 622 Greco-Indian Kingdom
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-bactria-note] LEGITIMATE Bactrian polygon (-250 to -125, Greco-Bactrian Kingdom). 622 Indo-Greek kingdom erroneously shared this — different (Indo-Greek was south of Hindu Kush).' WHERE id = 350;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/indogreek-fix] Replaced erroneous Bactrian polygon with 400km circle. Indo-Greek Kingdom (Ἑλληνικὴ Βασιλεία τῆς Ἰνδικῆς, -180 BCE to ~10 CE) was a Hellenistic state in NW Indian subcontinent (Punjab + Gandhara + Sind), peak under Menander I (Milinda); ended by Indo-Scythian + Indo-Parthian invasions.' WHERE id = 622;

-- 101 Shang + 102 Zhou
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-shang-note] LEGITIMATE Shang polygon. id=102 Zhou erroneously shared this — corrected.' WHERE id = 101;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/zhou-fix] Replaced erroneous Shang polygon with 500km circle. 周朝 (Zhou Dynasty, 1046-256 BCE) was the longest Chinese dynasty (W Zhou 1046-771, E Zhou 770-256); first iteration of "Mandate of Heaven"; Spring/Autumn + Warring States periods; ended by Qin.' WHERE id = 102;

-- 67 Prussia + 98 German Empire — successor states
UPDATE geo_entities SET ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2-prussia-note] LEGITIMATE Prussia polygon. German Empire 98 (1871-1918) erroneously shared this — corrected.' WHERE id = 67;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier2/germempire-fix] Replaced erroneous Prussia polygon with 500km circle. Deutsches Kaiserreich (German Empire, 1871-1918) was Bismarck-unified Germany under Prussian Hohenzollern Kaiser — covered modern Germany + Alsace-Lorraine + Polish provinces + Schleswig + Holstein + colonies (Africa, Pacific); ended with WWI defeat 1918.' WHERE id = 98;

-- Verify
SELECT COUNT(*) FROM geo_entities WHERE id IN (97, 586, 680, 214, 711, 724, 645, 731, 838, 637, 761, 762, 299, 300, 763, 211, 547, 238, 243, 454, 897, 78, 327, 126, 461, 105, 451, 350, 622, 101, 102, 67, 98);

COMMIT;
