-- Boundary Review v6.99.79 — Tier 3: 31 entities in 13 remaining collision groups
-- Different polities sharing same polygon. Each gets distinct circle.

BEGIN;

-- ========== JAPANESE PERIODS (444 Heian, 445 Kamakura, 447 Azuchi-Momoyama) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/japan-fix] Replaced shared Japan polygon with 350km circle around Heian-kyo. 平安時代 (Heian period 794-1185) was the classical Japanese era when imperial court flourished in Heian-kyo (Kyoto); Fujiwara regency + Genji-Heike conflicts; Tale of Genji literature.' WHERE id = 444;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/japan-fix] Replaced shared Japan polygon with 350km circle around Kamakura. 鎌倉幕府 (Kamakura Shogunate 1185-1333) first feudal military govt of Japan under Minamoto + Hojo regents; resisted 2 Mongol invasions (1274, 1281) with kamikaze typhoons; ended in Kemmu Restoration.' WHERE id = 445;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 350000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/japan-fix] Replaced shared Japan polygon with 350km circle. 安土桃山時代 (Azuchi-Momoyama period 1568-1600) was the brief Japanese unification era under Oda Nobunaga + Toyotomi Hideyoshi; Sengoku ended, Edo period began; Korean invasions 1592-98.' WHERE id = 447;

-- ========== MESOAMERICA (193 Teotihuacan, 928 Cholollan, 933 Teenek) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/teotihuacan-fix] Replaced shared polygon with 200km circle. Teotihuacan (-100 to 550 CE) was a major Mesoamerican city-state in Valley of Mexico, peak ~200 CE with population 125-200k; influenced cultures across Mesoamerica; collapsed mid-6th c. CE; pyramids of the Sun + Moon.' WHERE id = 193;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/cholollan-fix] Replaced shared polygon with 40km circle. Cholōllān/Huēi Cholōllān (-500 to 1519 CE) was a major Mesoamerican city in Puebla valley with continuous occupation ~2000 years; Great Pyramid of Cholula (largest pyramid by volume in world); Aztec subordinate; massacred by Cortés 1519.' WHERE id = 928;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/teenek-fix] Replaced shared polygon with 150km circle. Teenek/Huastec (1500 BCE - 1522 CE) was a Maya-language family confederation in NE Mexico Huasteca region (modern Veracruz + San Luis Potosi + Tamaulipas + Hidalgo); separated from main Maya by Olmec/Mexican languages; never unified; Aztec invasion + Spanish conquest 1522.' WHERE id = 933;

-- ========== SAMOA (303, 750, 856) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 60000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/samoa-fix] Replaced shared Samoa polygon with 60km circle. Ko e Pule''anga ''o Sāmoa was the Samoan kingdom / polity tradition (-1000 to 1900 CE) covering Western + American Samoa; Tui Manu''a, Tui ''Atua, Tui A''ana paramount titles; resisted Tongan domination ~1250 (Malietoa lineage); colonized by Germany+US 1899.' WHERE id = 303;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/samoa-fix] Replaced shared Samoa polygon with 50km circle. Tūmua ma Pule (1250-1899) was the Samoan paramount confederation tradition — Tumua orators of A''ana + Atua districts + Pule orators of Savai''i; ceremonial decisions of paramount titles like Malietoa, Tupua Tamasese, Mataafa.' WHERE id = 750;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 50000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/samoa-fix] Replaced shared Samoa polygon with 50km circle. Malo o Samoa (1250-1899) was the broader Samoan polity covering Savai''i + Upolu + Tutuila + Manu''a; intermittently unified under paramount titles; ended with German+US partition 1899.' WHERE id = 856;

-- ========== Wallachia + Moldavia (93+94) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/wallachia-fix] Replaced shared polygon with 250km circle. Țara Românească (Wallachia, 1330-1859) was a Romanian principality between S Carpathians + Danube, capital varied (Curtea de Argeș, Târgoviște, București); peak under Mircea cel Bătrân + Vlad Țepeș + Mihai Viteazul; Ottoman vassal 1417-1859.' WHERE id = 93;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/moldavia-fix] Replaced shared polygon with 200km circle. Principatul Moldovei (Moldavia, 1346-1859) was the Romanian principality E of Carpathians, capital varied (Baia, Suceava, Iași); peak under Ștefan cel Mare 1457-1504; Ottoman vassal; united with Wallachia 1859 to form Romania.' WHERE id = 94;

-- ========== Vijayanagara + Mysore (113+595) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/vijayanagara-fix] Replaced shared polygon with 500km circle around Vijayanagara/Hampi. విజయనగర సామ్రాజ్యం (Vijayanagara Empire, 1336-1646) was a S Indian Hindu empire founded by Sangama brothers; covered Karnataka + AP + Tamil + Kerala + Goa at peak (Krishnadevaraya); defeated by Deccan Sultanates Battle of Talikota 1565; ended 1646.' WHERE id = 113;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/mysore-fix] Replaced shared polygon with 250km circle around Mysore. ಮೈಸೂರು ಸಂಸ್ಥಾನ (Kingdom of Mysore, 1399-1947) Wadiyar dynasty founded under Vijayanagara suzerainty; transformed by Hyder Ali + Tipu Sultan (1761-1799); British Anglo-Mysore wars; absorbed into India 1947.' WHERE id = 595;

-- ========== Korean Three Kingdoms (115 Goguryeo, 116 Baekje) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 500000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/goguryeo-fix] Replaced shared polygon with 500km circle around Pyongyang. 고구려 (Goguryeo, 37 BCE - 668 CE) was the largest of Korean Three Kingdoms, covered N Korean peninsula + S Manchuria; capital varied (Jolbon → Gungnae → Pyongyang); ended by Silla-Tang alliance 668 CE.' WHERE id = 115;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/baekje-fix] Replaced shared polygon with 200km circle around Seoul. 백제 (Baekje, 18 BCE - 660 CE) was the SW Korean kingdom of Three Kingdoms era, capital varied (Wiryeseong → Ungjin/Gongju → Sabi/Buyeo); strong cultural/Buddhist ties with Japan; ended by Silla-Tang alliance 660 CE.' WHERE id = 116;

-- ========== Armenia + Caucasian Albania (288, 818) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 400000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.75), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/armenia-fix] Replaced shared polygon with 400km circle. Greater Armenia (Մեծ Հայք, 321 BCE - 428 CE) was an Armenian kingdom under Artaxiad, Arsacid + various dynasties, peak under Tigranes II (~85 BCE); first Christian state 301 CE under Tiridates III; partitioned between Rome+Persia 387; final fall 428.' WHERE id = 288;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/calbania-fix] Replaced shared polygon with 200km circle. 𐌀𐌋𐌖𐌀𐌍𐌊𐌀 Caucasian Albania (300 BCE - 705 CE) was an ancient Christianized kingdom in modern Azerbaijan + S Dagestan; vassal of Persians + Arabs; absorbed by Arab Caliphate 705; ancestors of modern Udi + Tat peoples.' WHERE id = 818;

-- ========== Hellenistic (613 Epirus, 614 Antigonid Macedonia) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/epirus-fix] Replaced shared polygon with 150km circle. Ἄπειρος (Hellenistic Epirus, 330-167 BCE) was a Hellenistic kingdom in NW Greece + Albania, peak under Pyrrhus (319-272 BCE) — fought against Romans in Italy (Pyrrhic victory); destroyed by Roman conquest 167 BCE.' WHERE id = 613;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/antigonid-fix] Replaced shared polygon with 250km circle. Antigonid Macedonia (Βασιλεία Ἀντιγονιδῶν, 306-168 BCE) was the Hellenistic kingdom centered on Macedonia + N Greece, founded by Antigonus I after Alexander; ended at Battle of Pydna 168 BCE (Roman conquest).' WHERE id = 614;

-- ========== Mesopotamian Bronze Age (805 Mari, 806 Ebla) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/mari-fix] Replaced shared polygon with 80km circle. 𒈠𒌷𒆠 Mari (~2900-1759 BCE) was an ancient Syrian city-state on the middle Euphrates, important trade hub between Mesopotamia + Levant; archives discovered with 25,000 cuneiform tablets; destroyed by Hammurabi of Babylon 1759.' WHERE id = 805;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 80000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/ebla-fix] Replaced shared polygon with 80km circle. 𒅁𒆷 Ebla (~3000-1600 BCE) was an ancient Bronze Age kingdom in N Syria, archives discovered 1974 with 17,000+ cuneiform tablets in Eblaite (oldest Semitic language attested); destroyed multiple times (Sargon of Akkad ~2240, Hittites ~1600).' WHERE id = 806;

-- ========== Mossi (159 Moose, 844 Yatenga) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 200000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/mossi-fix] Replaced shared polygon with 200km circle. Moose (Mossi Kingdoms of Burkina Faso, 1100-1896) — federation of 4-5 Mossi states (Ouagadougou, Yatenga, Tenkodogo, Fada N''Gourma, Riziam); resisted Mali + Songhai + jihad states; capital Ouagadougou; conquered by French 1896.' WHERE id = 159;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/yatenga-fix] Replaced shared polygon with 150km circle. Yatenga (1540-1895) was the northwestern Mossi kingdom in modern Burkina Faso; capital Ouahigouya from 1757; resisted Marka, Fulani, French; conquered by France 1895.' WHERE id = 844;

-- ========== Uganda (557 Bunyoro-Kitara, 734 Nkore) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 250000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.7), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/bunyoro-fix] Replaced shared polygon with 250km circle. Bunyoro-Kitara (1300-1967) was a major Bantu kingdom in W Uganda, ruled by Babito dynasty after Cwezi era; peak 16th-17th c. controlled half of Great Lakes region; declined after Buganda rise + British conquest 1894.' WHERE id = 557;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry), boundary_source = 'approximate_circle', boundary_ne_iso_a3 = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/nkore-fix] Replaced shared polygon with 120km circle. Nkore/Ankole (1400-1901) was a kingdom in SW Uganda Hima-Iru duality; capital Mbarara region; Mugabe (king) lineage; conquered/protected by British 1894; abolished as kingdom by Obote 1967.' WHERE id = 734;

-- ========== Mapungubwe + K2/Bambandyanalo (989+990) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 40000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/mapungubwe-fix] Replaced shared polygon with 40km circle. Mapungubwe (1075-1300 CE) was a S African Bantu kingdom at confluence of Shashe + Limpopo rivers; first social stratification + Zimbabwe/Khami tradition predecessor; golden rhino figurine; UNESCO site.' WHERE id = 989;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 25000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 25000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.6), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/k2-fix] Replaced shared polygon with 25km circle. K2 / Bambandyanalo (1000-1075 CE) was the immediate predecessor of Mapungubwe ~5km south; Leopard''s Kopje culture; transitioned to Mapungubwe ~1075; first significant social hierarchy in S African Iron Age.' WHERE id = 990;

-- ========== Cham (892 Indrapura, 893 Vijaya) ==========
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 120000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/indrapura-fix] Replaced shared polygon with 120km circle. Indrapura (875-982 CE) was a phase of Champa kingdom (central Vietnam) with capital at Indrapura (Đồng Dương); Hindu-Buddhist; raided by Đại Việt 982 forcing capital move to Vijaya.' WHERE id = 892;
UPDATE geo_entities SET boundary_geojson = ST_AsGeoJSON(ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry)), boundary_geom = ST_Multi(ST_Buffer(ST_SetSRID(ST_MakePoint(capital_lon, capital_lat), 4326)::geography, 150000)::geometry), boundary_source = 'approximate_circle', boundary_aourednik_name = NULL, boundary_aourednik_year = NULL, boundary_aourednik_precision = NULL, confidence_score = LEAST(confidence_score, 0.65), ethical_notes = COALESCE(ethical_notes, '') || E'\n\n[v6.99.79-tier3/vijaya-fix] Replaced shared polygon with 150km circle. Vijaya (1000-1471 CE) was the longest-lasting phase of Champa kingdom (central Vietnam), capital at Vijaya (Bình Định); fell to Đại Việt Lê Thánh Tông 1471 ending Champa as major power; remnants survived as Panduranga to 1832.' WHERE id = 893;

SELECT COUNT(*) FROM geo_entities WHERE id IN (444,445,447,193,928,933,303,750,856,93,94,113,595,115,116,288,818,613,614,805,806,159,844,557,734,989,990,892,893);

COMMIT;
