"""Apply an enrichment spec to the JSON source AND emit an idempotent prod SQL file.

Wave 2 Plan A (brief D) enrichment workflow, "prepare + commit, NO deploy" mode:
  * Updates data/entities/*.json in place: appends new sources (dedup by citation),
    sets confidence_score + status, appends the tagged ethical_notes paragraph.
  * Writes a prod SQL file (idempotent: INSERT ... WHERE NOT EXISTS + ethical_notes
    guarded by the [tag]) for Clirim to run on prod via SSH, then cra-deploy.

The JSON and the SQL apply the SAME target state, so prod and source stay in sync.
Match: JSON by name_original, prod by id. Idempotent on both sides.

Usage:
    python -m scripts.apply_enrichment data/fixes/enrichment_s51_eurasia.json --dry-run
    python -m scripts.apply_enrichment data/fixes/enrichment_s51_eurasia.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENTITIES_DIR = ROOT / "data" / "entities"


def _sq(s: str) -> str:
    """Escape a string for a single-quoted SQL literal."""
    return s.replace("'", "''")


def _gen_sql(spec: dict) -> str:
    lines = [
        "-- Enrichment prod SQL (idempotent) — generated by scripts/apply_enrichment.py",
        f"-- {spec['_meta']['session']} | {spec['_meta']['date']}",
        "-- Run on prod, then cra-deploy:",
        "--   ssh -i ~/.ssh/cra_vps root@77.81.229.242 \\",
        "--     \"docker exec -i cra-atlaspi-db psql -U atlaspi -d atlaspi\" < this_file.sql",
        "BEGIN;",
        "",
    ]
    for e in spec["entities"]:
        eid = e["id"]
        lines.append(f"-- id={eid} {e['label']} (conf->{e['confidence']})")
        for s in e["new_sources"]:
            cit, url, st = _sq(s["citation"]), s.get("url"), s["source_type"]
            url_sql = f"'{_sq(url)}'" if url else "NULL"
            lines.append(
                f"INSERT INTO sources (entity_id, citation, url, source_type) "
                f"SELECT {eid}, '{cit}', {url_sql}, '{st}' "
                f"WHERE NOT EXISTS (SELECT 1 FROM sources WHERE entity_id={eid} AND citation='{cit}');"
            )
        note = _sq(e["ethical_notes_append"])
        tag = e["ethical_notes_append"].split("]")[0] + "]"  # e.g. "[S51-enrich]"
        status_sql = f", status = '{_sq(e['status'])}'" if e.get("status") else ""
        lines.append(
            f"UPDATE geo_entities SET confidence_score = {e['confidence']}{status_sql}, "
            f"ethical_notes = CASE WHEN ethical_notes LIKE '%{_sq(tag)}%' THEN ethical_notes "
            f"ELSE COALESCE(ethical_notes, '') || E'\\n\\n' || '{note}' END "
            f"WHERE id = {eid};"
        )
        lines.append("")
    lines.append("SELECT id, name_original, confidence_score, status, "
                 "(SELECT count(*) FROM sources s WHERE s.entity_id = geo_entities.id) AS n_sources")
    ids = ",".join(str(e["id"]) for e in spec["entities"])
    lines.append(f"FROM geo_entities WHERE id IN ({ids}) ORDER BY id;")
    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


def _apply_json(spec: dict, dry_run: bool) -> dict:
    by_name = {e["name_original"]: e for e in spec["entities"]}
    files = sorted(p for p in ENTITIES_DIR.glob("*.json") if not p.name.endswith(".bak"))
    stats = {"matched": set(), "files_changed": set(), "sources_added": 0, "notes_appended": 0}
    parsed: dict[Path, list] = {}
    for path in files:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        parsed[path] = data
        for ent in data:
            spec_e = by_name.get(ent.get("name_original"))
            if not spec_e:
                continue
            stats["matched"].add(spec_e["name_original"])
            changed = False
            # sources: append new, dedup by citation
            existing = {s.get("citation") for s in ent.get("sources", [])}
            for s in spec_e["new_sources"]:
                if s["citation"] not in existing:
                    ent.setdefault("sources", []).append(
                        {"citation": s["citation"], "url": s.get("url"), "source_type": s["source_type"]}
                    )
                    existing.add(s["citation"])
                    stats["sources_added"] += 1
                    changed = True
            # confidence + status
            if ent.get("confidence_score") != spec_e["confidence"]:
                ent["confidence_score"] = spec_e["confidence"]
                changed = True
            if spec_e.get("status") and ent.get("status") != spec_e["status"]:
                ent["status"] = spec_e["status"]
                changed = True
            # ethical_notes append (idempotent via tag)
            tag = spec_e["ethical_notes_append"].split("]")[0] + "]"
            cur = ent.get("ethical_notes") or ""
            if tag not in cur:
                ent["ethical_notes"] = (cur + ("\n\n" if cur else "") + spec_e["ethical_notes_append"])
                stats["notes_appended"] += 1
                changed = True
            if changed:
                stats["files_changed"].add(path)
    missing = set(by_name) - stats["matched"]
    if missing:
        print("ERROR: spec entities not found in data/entities/*.json by name_original:")
        for m in sorted(missing):
            print("   ", repr(m))
        sys.exit(2)
    if not dry_run:
        for path in stats["files_changed"]:
            text = json.dumps(parsed[path], ensure_ascii=False, indent=2).replace("\n", "\r\n")
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(text)
    return stats


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Apply enrichment spec to JSON + emit prod SQL.")
    ap.add_argument("spec", help="path to enrichment spec JSON")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, ValueError):
        pass

    spec = json.load(open(args.spec, encoding="utf-8"))
    sql = _gen_sql(spec)
    sql_path = Path(args.spec).with_suffix(".sql")

    stats = _apply_json(spec, dry_run=args.dry_run)
    print(f"Entities matched in JSON: {len(stats['matched'])}/{len(spec['entities'])}")
    print(f"Sources added: {stats['sources_added']}  | ethical_notes appended: {stats['notes_appended']}"
          f"  | files changed: {len(stats['files_changed'])}")

    if args.dry_run:
        print(f"\nDRY-RUN: would write {sql_path.name} ({sql.count('INSERT')} INSERTs, {len(spec['entities'])} UPDATEs).")
        return 0

    with open(sql_path, "w", encoding="utf-8", newline="") as fh:
        fh.write(sql)
    print(f"\nWrote prod SQL: {sql_path}")
    print(f"Wrote {len(stats['files_changed'])} entity JSON files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
