"""Fix antimeridian bug for id 754 (Sau o Futuna) and 307 (Lapita).

# ETHICS: v6.99.82 Wave 1.2 — antimeridian data fix. Entrambe le entità erano
# in MANUALLY_CURATED_IDS (skip dell'auto-fix) ma il polygon attuale ha
# bbox 359°/358° lon span. È un artifact di wrap-around (vertici a ±179.98).
# Sostituiamo con cerchi storicamente realistici attorno alle capitali:
# - Sau o Futuna: r=10km (isola Futuna+Alofi, ~64 km² totali)
# - Lapita: r=1000km (sfera culturale core Bismarcks-Vanuatu-Fiji)
#   ETHICS-007: la cultura Lapita si estendeva ulteriormente est fino a
#   Tonga/Samoa attraversando l'antimeridian. È un construct archeologico,
#   non un polity unitario — già documentato in ethical_notes originali.
# Usage:
#   python -m scripts.fix_anti_754_307 > data/fixes/v6.99.82_antimeridian.sql
"""
import argparse
import json
import sys
from pathlib import Path

# Re-use circle generator from existing fix script (already PostGIS-validated)
from src.ingestion.fix_antimeridian_and_wrong_polygons import _generate_circle


FIXES = [
    {
        "id": 754,
        "name": "Sau o Futuna",
        "capital_lat": -14.30,
        "capital_lon": -178.16,
        "radius_km": 10,
        "note": (
            "[v6.99.82 antimeridian fix] Polygon precedente (bbox 359.97° "
            "lon span, area ~125k km²) era un artifact di wrap-around "
            "(vertici a ±179.98). Sostituito con cerchio 10km attorno alla "
            "capitale storica Sigave/Alo (Futuna island). NB: il cerchio "
            "(~314 km²) è una SCHEMATIC MARITIME/ISLAND APPROXIMATION; le "
            "isole Futuna+Alofi sommano ~64 km² di terra emersa, il resto "
            "rappresenta la zona marittima territoriale di pertinenza dei "
            "due regni. Vedi note originali sui due regni Sau."
        ),
    },
    {
        "id": 307,
        "name": "Lapita",
        "capital_lat": -17.7333,
        "capital_lon": 168.3167,
        "radius_km": 1000,
        "note": (
            "[v6.99.82 antimeridian fix] Polygon precedente (bbox 358.5° "
            "lon span, area 6.19M km²) era un artifact di wrap-around. "
            "Sostituito con cerchio 1000km centrato su Vanuatu (Efate), "
            "che rappresenta INTENZIONALMENTE solo il core area "
            "Bismarcks-Solomon-Vanuatu-Fiji come WESTERN/CORE PROXY. "
            "La sfera culturale Lapita storicamente attestata si estendeva "
            "ulteriormente est fino a Tonga/Samoa (~-175°W), MA è esclusa "
            "da questo polygon per limiti di rendering antimeridiano "
            "(MultiPolygon antimeridian-safe come follow-up). Vedi "
            "ETHICS-007: Lapita è un archaeological construct (dentate-"
            "stamped pottery tradition), NON un polity unitario."
        ),
    },
]


def _sql_escape(s: str) -> str:
    """Escape single quotes for SQL string literal."""
    return s.replace("'", "''")


def generate_sql() -> str:
    parts = [
        "-- v6.99.82 Wave 1.2 — antimeridian data fix for id 754 + 307",
        "-- Generated by scripts/fix_anti_754_307.py",
        "-- Run with: psql -U atlaspi -d atlaspi -f this_file.sql",
        "",
        "BEGIN;",
        "",
    ]
    for fix in FIXES:
        geom = _generate_circle(
            fix["capital_lat"], fix["capital_lon"], fix["radius_km"]
        )
        gjson = json.dumps(geom, separators=(",", ":"))
        note_sql = _sql_escape(fix["note"])
        # Compute bbox sanity check on output: lon span < 180
        coords = geom["coordinates"][0]
        lons = [c[0] for c in coords]
        lon_span = max(lons) - min(lons)
        assert lon_span < 180, f"Generated polygon for id={fix['id']} still crosses antimeridian (lon_span={lon_span}°)"

        sql = f"""-- id={fix['id']} {fix['name']}
-- circle r={fix['radius_km']}km centered at ({fix['capital_lat']}, {fix['capital_lon']})
-- new bbox lon_span = {lon_span:.4f}° (well under 180° threshold)
-- Idempotent: WHERE clause skips if v6.99.82 fix already applied.
UPDATE geo_entities
SET boundary_geojson = '{gjson}',
    boundary_geom = ST_SetSRID(ST_GeomFromGeoJSON('{gjson}'), 4326),
    boundary_source = 'historical_approximation',
    ethical_notes = CASE
        WHEN COALESCE(NULLIF(ethical_notes, ''), '') = ''
            THEN '{note_sql}'
        ELSE ethical_notes || E'\\n\\n{note_sql}'
    END
WHERE id = {fix['id']}
  AND COALESCE(ethical_notes, '') NOT LIKE '%[v6.99.82 antimeridian fix]%';
"""
        parts.append(sql)
    parts.append("-- Verify post-fix:")
    parts.append("""SELECT id, name_original,
       (ST_XMax(boundary_geom::geometry) - ST_XMin(boundary_geom::geometry)) AS lon_span_deg,
       ST_Area(boundary_geom::geography)/1e6 AS area_km2,
       ST_IsValid(boundary_geom) AS is_valid
FROM geo_entities WHERE id IN (754, 307);""")
    parts.append("")
    parts.append("COMMIT;")
    return "\n".join(parts)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", default="-", help="Output file (- for stdout)")
    args = p.parse_args()
    sql = generate_sql()
    if args.out == "-":
        print(sql)
    else:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(sql, encoding="utf-8")
        print(f"Wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
