-- v6.99.120 (M1/ETHICS-020) — 11 entità-sblocco + estensioni catene.
-- Generato da scripts/apply_m1_unlock.py — NON editare a mano.
-- Dual-write: JSON = data/entities/batch_37_m1_unlock.json + data/chains/*.
-- Backup pg_dump PRIMA. Applicare con psql -v ON_ERROR_STOP=1.
BEGIN;

-- guard: nessuna delle entità nuove esiste già
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM geo_entities WHERE name_original IN (
    'កម្ពុជា (Longvek-Oudong)', 'សាធារណរដ្ឋខ្មែរ', 'Кнежевина Србија', 'Краљевина Срба, Хрвата и Словенаца', 'إمارة الدرعية', 'إمارة نجد', 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल', 'Mthwakazi'
  )) THEN RAISE EXCEPTION 'entità M1 già presenti — script già applicato?'; END IF;
END $$;

-- ── cambodia_post_angkor ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('កម្ពុជា (Longvek-Oudong)', 'km', 'kingdom', 1431, 1863,
        'Oudong (ឧដុង្គ)', 11.8239, 104.7425, '{"type": "Polygon","coordinates": [[[103,10.9],[104.5,10.4],[106,10.8],[106.5,12],[106.2,13.4],[105,14.2],[103.2,14],[102.6,13.2],[102.9,12],[103,10.9]]]}', 'historical_approximation',
        0.7, 'confirmed', 'ETHICS-002: The period opened and closed with violence and coercion. Ayutthaya (Siam) sacked the Khmer capital Yasodharapura (Angkor) around 1431, and on 3 January 1594 King Naresuan of Ayutthaya stormed and looted the capital Longvek, deporting much of its population — remembered in Khmer tradition as a national catastrophe. ETHICS-002: The Nguyen lords of Vietnam progressively annexed Kampuchea Krom (the Mekong Delta): in 1698 Nguyen Huu Canh administratively detached Prey Nokor (renamed Sai Gon) from Cambodia, and by 1757 the entire delta was absorbed, leaving the Khmer Krom a dispossessed minority under Vietnamese rule to this day. ETHICS-002: In 1834-1841 Emperor Minh Mang annexed Cambodia outright as the Vietnamese province of Tran Tay, installed Queen Ang Mey as a puppet and imposed forced Vietnamization, until a Khmer rebellion and Siamese intervention restored King Ang Duong under joint Siamese-Vietnamese suzerainty (formalized 1845-1847); Siam separately seized Battambang and Siem Reap provinces in 1794. ETHICS-002: The 11 August 1863 ''protection'' treaty with France was signed by King Norodom under French naval-diplomatic pressure and as an escape from Siamese-Vietnamese domination — a colonial protectorate, not a partnership of equals. ETHICS-001: The primary name is the attested Khmer endonym កម្ពុជា (Kampuchea, attested since the Baksei Chamkrong inscription, 947 CE, and throughout the Middle Period); ''Cambodia'', ''Camboja'' and ''Cambodge'' are European exonyms kept in name_variants. The ''Dark Age'' framing (reflected in the Khmer Wikidata label យុគអន្ធកាលនៃកម្ពុជា) is contested historiography — Vickery and later scholarship show an era of reorientation toward maritime trade, not simple decay.', 'Q4919413',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[103,10.9],[104.5,10.4],[106,10.8],[106.5,12],[106.2,13.4],[105,14.2],[103.2,14],[102.6,13.2],[102.9,12],[103,10.9]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Post-Angkor Cambodia', 'en', 1431, 1863, 'modern historiographical term (Wikidata Q4919413)', 'Wikidata Q4919413; Chandler 2008');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Middle Period Cambodia', 'en', 1431, 1863, 'alternative historiographical term used by Chandler and Vickery', 'Chandler, A History of Cambodia (2008)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Kampuchea (Longvek-Oudong)', 'km-Latn', 1431, 1863, 'romanization of the Khmer endonym កម្ពុជា with DB disambiguator (modern Kingdom of Cambodia holds the unqualified name)', 'Names of Cambodia (endonym attested from 947 CE inscription onward)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'ស្រុកខ្មែរ (Srok Khmer)', 'km', NULL, NULL, 'colloquial endonym, ''land of the Khmers''', 'Names of Cambodia');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Camboja', 'pt', 1500, 1700, '16th-17th-century Iberian exonym used by Portuguese and Spanish visitors to Longvek', NULL);
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Cambodge', 'fr', 1863, NULL, 'French exonym, official under the 1863 protectorate', 'Treaty of 11 August 1863');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 1431, 'Angkor (Yasodharapura) and northwest heartland', 'CONQUEST_MILITARY', 'Ayutthaya (Siam) captured and sacked the Khmer capital Yasodharapura (Angkor); the royal court shifted south to Chaktomuk (Phnom Penh), founding the Middle Period. Conventional date — the exact nature and year of the Siamese intervention are debated (Vickery 1977), and Angkor''s abandonment was gradual.', NULL, 0.6);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 1594, 'Longvek (capital, Tonle Sap west bank)', 'CONQUEST_MILITARY', 'King Naresuan of Ayutthaya stormed, looted and destroyed the capital Longvek on 3 January 1594, ending the Siamese-Cambodian War of 1591-1594; population deported, Cambodia reduced to intermittent Siamese vassalage. Court later re-established at Oudong (1618).', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 1698, 'Kampuchea Krom / Mekong Delta (Prey Nokor-Saigon)', 'CESSION_FORCED', 'The Nguyen lords commissioned Nguyen Huu Canh to organize Prey Nokor (renamed Sai Gon) under Vietnamese administration, de facto detaching it from Cambodia; by 1757 the whole delta (Psar Dek/Sa Dec, Moat Chrouk/Chau Doc) was absorbed into Vietnam, dispossessing the Khmer Krom.', NULL, 0.75);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 1863, 'Entire kingdom', 'TREATY', 'King Norodom signed the French protectorate treaty on 11 August 1863 under French naval-diplomatic pressure, ending the Siamese-Vietnamese dual vassalage; the monarchy survived but power passed to a French resident. Successor chain leads into French Indochina (federation formed 1887).', NULL, 0.95);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'David Chandler, A History of Cambodia, 4th ed. (Boulder: Westview Press, 2008)', 'https://www.routledge.com/A-History-of-Cambodia/Chandler/p/book/9780813343631', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Mak Phoeun, Histoire du Cambodge de la fin du XVIe siècle au début du XVIIIe siècle (Paris: École française d''Extrême-Orient, 1995)', 'https://angkordatabase.asia/books/histoire-du-cambodge-de-la-fin-du-xvie-au-xviiieme-siecle', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Khin Sok, Le Cambodge entre le Siam et le Viêtnam (de 1775 à 1860) (Paris: École française d''Extrême-Orient, 1991)', 'https://publications.efeo.fr/en/livres/192_le-cambodge-entre-le-siam-et-le-vietnam-de-1775-a-1860', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 'Michael Vickery, Cambodia After Angkor: The Chronicular Evidence for the Fourteenth to Sixteenth Centuries (PhD dissertation, Yale University, 1977)', 'http://michaelvickery.org/', 'academic');

-- ── khmer_republic ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('សាធារណរដ្ឋខ្មែរ', 'km', 'republic', 1970, 1975,
        'Phnom Penh (ភ្នំពេញ)', 11.5564, 104.9282, '{"type": "Polygon","coordinates": [[[102.35,13.55],[102.75,11.65],[103.55,10.55],[104.45,10.42],[105.35,10.85],[106.2,10.95],[106,11.75],[107.55,12.35],[107.5,14.45],[105.9,14.15],[104.6,14.4],[103.1,14.3],[102.35,13.55]]]}', 'historical_approximation',
        0.85, 'confirmed', 'ETHICS-002: The United States (Nixon administration, US Air Force) bombed the Cambodian countryside in Operations Menu (1969-70) and Freedom Deal (1970 to 15 August 1973), killing an estimated 50,000-150,000 Cambodian civilians per Kiernan and Owen — the toll is disputed, and the underlying tonnage data were themselves revised (c. 2.76 million tons claimed in their 2006 analysis, corrected to roughly 500,000 tons for 1969-73 in their 2015 re-analysis). Shawcross, Chandler and Kiernan all argue the bombing devastated rural society and materially aided Khmer Rouge recruitment. ETHICS-002: In April 1970 the Lon Nol government organized and tolerated pogroms against Cambodia''s c. 400,000-strong ethnic Vietnamese minority: army, police and mobs massacred thousands of civilians, whose bodies floated down the Mekong into South Vietnam, and most of the surviving community fled or was expelled. The Khmer Republic was a US-backed military dictatorship whose 1972 presidential election of Lon Nol was widely regarded as rigged, and which survived only on US military and economic aid until the Khmer Rouge took Phnom Penh on 17 April 1975. ETHICS-001: the primary name is the attested Khmer form សាធារណរដ្ឋខ្មែរ (Sathearonaroat Khmae); the French co-official name République khmère is recorded as a variant. This record fills the 1970-75 gap created by the ETHICS-019 correction, under which the Democratic Kampuchea record (#240) had wrongly carried this state''s name.', 'Q1054184',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[102.35,13.55],[102.75,11.65],[103.55,10.55],[104.45,10.42],[105.35,10.85],[106.2,10.95],[106,11.75],[107.55,12.35],[107.5,14.45],[105.9,14.15],[104.6,14.4],[103.1,14.3],[102.35,13.55]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'Khmer Republic', 'en', 1970, 1975, 'English name', 'Wikidata Q1054184');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'Sathearonaroat Khmae', 'km-Latn', 1970, 1975, 'romanization of សាធារណរដ្ឋខ្មែរ', 'en.wikipedia.org/wiki/Khmer_Republic');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'République khmère', 'fr', 1970, 1975, 'official name in French, co-official language of the republic', 'en.wikipedia.org/wiki/Khmer_Republic');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 1970, 'Phnom Penh / nationwide', 'REVOLUTION', '18 March 1970: National Assembly vote led by Prime Minister Lon Nol and Sisowath Sirik Matak deposed head of state Norodom Sihanouk while he was abroad; the monarchy was abolished and the Khmer Republic formally proclaimed on 9 October 1970. Sihanouk formed the GRUNK government-in-exile allied with the Khmer Rouge, starting full-scale civil war.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 1970, 'Phnom Penh and Mekong lowlands', 'ETHNIC_CLEANSING', 'April 1970: pogroms against Cambodia''s c. 400,000-strong ethnic Vietnamese minority, organized and tolerated by the Lon Nol government — army and police rounded up, interned and massacred thousands of civilians (bodies floated down the Mekong into South Vietnam); most of the surviving community fled or was expelled to South Vietnam.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 1973, 'rural Cambodia (countryside)', 'CONQUEST_MILITARY', 'By the US Congress-mandated bombing halt of 15 August 1973 (end of Operation Freedom Deal), CPK/Khmer Rouge and GRUNK forces controlled most of the countryside; the Republic was reduced to Phnom Penh, provincial capitals and supply corridors. US bombing 1969-73 killed an estimated 50,000-150,000 Cambodian civilians (Kiernan & Owen; disputed range).', NULL, 0.75);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 1975, 'Phnom Penh', 'CONQUEST_MILITARY', '17 April 1975: the Khmer Rouge captured Phnom Penh after a siege; the Khmer Republic collapsed and was succeeded by the CPK regime (Democratic Kampuchea). The last government outpost, Preah Vihear temple, fell on 22 May 1975.', NULL, 0.9);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'William Shawcross, Sideshow: Kissinger, Nixon and the Destruction of Cambodia, Simon & Schuster, 1979 (rev. ed. Cooper Square Press, 2002)', 'https://books.google.com/books/about/Sideshow.html?id=bjtvQgAACAAJ', 'secondary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'David P. Chandler, The Tragedy of Cambodian History: Politics, War, and Revolution since 1945, Yale University Press, 1991', 'https://yalebooks.yale.edu/book/9780300057522/the-tragedy-of-cambodian-history/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'Justin J. Corfield, Khmers Stand Up! A History of the Cambodian Government 1970-1975, Monash Papers on Southeast Asia No. 32, Centre of Southeast Asian Studies, Monash University, 1994', 'https://catalogue.nla.gov.au/catalog/662024', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'Taylor Owen and Ben Kiernan, ''Bombs over Cambodia'', The Walrus, October 2006', 'https://thewalrus.ca/2006-10-history/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'សាធារណរដ្ឋខ្មែរ'), 'Ben Kiernan and Taylor Owen, ''Making More Enemies than We Kill? Calculating US Bomb Tonnages Dropped on Laos and Cambodia, and Weighing Their Implications'', The Asia-Pacific Journal: Japan Focus, vol. 13, issue 16, no. 3, 2015', 'https://apjjf.org/ben-kiernan/4313', 'academic');

-- ── serbia_1815_1918 ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('Кнежевина Србија', 'sr', 'principality', 1815, 1918,
        'Belgrade (Београд)', 44.8176, 20.4569, '{"type": "Polygon","coordinates": [[[19.35,44.9],[19.7,44.77],[20.2,44.66],[20.45,44.82],[20.95,44.67],[21.4,44.78],[21.63,44.66],[22.15,44.47],[22.45,44.67],[22.68,44.55],[22.67,44.21],[22.4,43.85],[22.55,43.45],[23,43.18],[22.55,42.85],[22.35,42.55],[21.7,42.32],[21.45,42.75],[21,43.1],[20.85,43.25],[20.6,43.32],[20.1,43.45],[19.63,43.58],[19.48,43.75],[19.4,43.98],[19.35,44.2],[19.2,44.55],[19.35,44.9]]]}', 'historical_approximation',
        0.9, 'confirmed', 'ETHICS-002-relevant events, perpetrators named. (1) 1862 Belgrade crisis: after the Cukur Fountain killing of a Serb boy by Ottoman soldiers, the Ottoman garrison bombarded civilian Belgrade from the fortress (~50 killed, hundreds of houses damaged) — perpetrator: Ottoman garrison. The subsequent Great-Power Kanlica conference (1862) mandated the removal of the Muslim civilian population from Serbian towns; roughly 10,000 Muslims left the six Serbian garrison towns in the 1862-1867 wave (about 2,100 of them from Belgrade) — a state- and Great-Power-sanctioned population removal benefiting the Serbian state, recorded as ETHNIC_CLEANSING with dual agency (Ottoman bombardment; Serbian/Great-Power removal). (2) 1877-78: during and after the Serbian army''s conquest of the Nis and Toplica sanjaks, the Muslim population — majority Albanian in the countryside, Turkish in towns, roughly one third of the region''s population — was expelled or fled under military pressure; Serbian forces under Prince Milan Obrenovic burned villages and blocked return. Best academic estimates: ~49,000 Albanians among at least 71,000 Muslims (Jagodic 1998; Stefanovic 2005); Albanian historiography cites higher figures. Recorded as ETHNIC_CLEANSING, perpetrator the Serbian army/state. The refugees (muhaxhire) resettled in Kosovo, seeding long-term Serb-Albanian conflict. (3) Balkan Wars 1912-13: Serbian (and Montenegrin) forces conquering Kosovo and Vardar Macedonia committed massacres of Albanian civilians, village burnings and forced conversions, documented contemporaneously by the Carnegie Endowment''s 1914 International Commission report — which found grave violations by ALL belligerents (Serbian, Bulgarian, Greek, Ottoman, Montenegrin); Albanians and Macedonian Slavs passed under Serbian rule without consent, under a regime of military administration. (4) WWI 1914-18: Austria-Hungary invaded (perpetrating documented mass executions of civilians in Macva/Sabac in 1914); the 1915 Central Powers conquest was followed by harsh Austro-Hungarian and Bulgarian occupation regimes (internment, forced Bulgarianization in the east, suppression of the 1917 Toplica uprising with mass reprisals); the winter 1915-16 retreat through Albania killed tens of thousands of soldiers and civilians. Serbia''s total war losses: 16-28% of the pre-war population depending on methodology (~25% is a common mid-range figure) — among the highest per-capita losses of any WWI belligerent. Serbia in this entry is BOTH perpetrator (1862 removals, 1878 expulsions, 1912-13 conquests) and victim (1862 bombardment, 1914-18 invasion and occupation): both are stated without hierarchy.', 'Q684030',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[19.35,44.9],[19.7,44.77],[20.2,44.66],[20.45,44.82],[20.95,44.67],[21.4,44.78],[21.63,44.66],[22.15,44.47],[22.45,44.67],[22.68,44.55],[22.67,44.21],[22.4,43.85],[22.55,43.45],[23,43.18],[22.55,42.85],[22.35,42.55],[21.7,42.32],[21.45,42.75],[21,43.1],[20.85,43.25],[20.6,43.32],[20.1,43.45],[19.63,43.58],[19.48,43.75],[19.4,43.98],[19.35,44.2],[19.2,44.55],[19.35,44.9]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Кнежевина Србија', 'sr-Cyrl', 1815, 1882, 'Founding form (modern standard Serbian orthography), chosen as primary per founding-form convention', 'Standard Serbian historiography');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Књажество Србија', 'sr-Cyrl', 1830, 1882, 'Attested official 19th-century orthography, e.g. the 1869 constitution ''Устав за Књажество Србију''', 'Constitution of 1869');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Краљевина Србија', 'sr-Cyrl', 1882, 1918, 'Kingdom proclaimed 6 March 1882 under Milan I Obrenovic; period variant of the same continuous state', 'Proclamation of the Kingdom, 1882');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Kneževina Srbija', 'sr-Latn', 1815, 1882, 'Serbian Latin script', NULL);
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Kraljevina Srbija', 'sr-Latn', 1882, 1918, 'Serbian Latin script, kingdom phase', NULL);
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Principality of Serbia', 'en', 1815, 1882, 'English exonym', NULL);
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Kingdom of Serbia', 'en', 1882, 1918, 'English exonym, kingdom phase', NULL);
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Principauté de Serbie', 'fr', 1830, 1882, 'French, diplomatic language of the era (Treaty of Berlin drafted in French)', 'Treaty of Berlin, 1878');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1815, 'Pashalik of Belgrade (Sumadija / Morava valley core)', 'REVOLUTION', 'Second Serbian Uprising under Milos Obrenovic (from April 1815, Takovo); negotiated settlement with Marashli Ali Pasha gave Serbs de facto self-rule within the Pashalik of Belgrade while remaining under Ottoman suzerainty.', NULL, 0.95);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1830, 'Autonomous Principality (Belgrade pashalik core)', 'TREATY', 'Ottoman hatt-i sharif of 1830 (following the Akkerman Convention 1826 and Treaty of Adrianople 1829) recognized Serbia as an autonomous, tribute-paying hereditary principality under Milos Obrenovic; Ottoman garrisons remained in the fortress towns.', NULL, 0.95);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1833, 'Six nahiyes (Krajina, Crna Reka, Banja/Aleksinac, Krusevac, Stari Vlah, Jadar-Radjevina)', 'TREATY', 'Supplementary hatt-i sharif of 1833 confirmed the annexation of six contested nahiyes claimed since the First Uprising, enlarging the principality to its 1833-1878 extent.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1862, 'Belgrade and Serbian fortress towns', 'ETHNIC_CLEANSING', 'Cukur Fountain incident: Ottoman soldiers killed a Serb apprentice boy; riots followed and the Ottoman garrison bombarded civilian Belgrade from the fortress (~50 killed). The Great-Power Kanlica conference then mandated the departure of the Muslim civilian population from Serbian towns; roughly 10,000 Muslims left the six Serbian garrison towns in the 1862-1867 wave (about 2,100 of them from Belgrade). Dual agency: Ottoman garrison (bombardment); Serbian state and Great Powers (sanctioned population removal).', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1867, 'Fortresses of Belgrade, Sabac, Smederevo, Kladovo', 'TREATY', 'Ottoman garrisons withdrew from all remaining fortresses; keys of Belgrade fortress ceremonially handed to Prince Mihailo Obrenovic on Kalemegdan (April 1867), ending the Ottoman military presence while nominal suzerainty continued.', NULL, 0.95);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1878, 'Nis, Pirot, Toplica and Vranje districts', 'TREATY', 'Treaty of Berlin (13 July 1878) recognized Serbia''s full independence from the Ottoman Empire and its annexation of four southeastern districts (Nis, Pirot, Toplica, Vranje) taken in the 1876-78 Serbo-Ottoman wars.', NULL, 0.95);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1878, 'Nis and Toplica sanjaks (newly annexed districts)', 'ETHNIC_CLEANSING', 'During and after the 1877-78 war the Serbian army under Prince Milan Obrenovic expelled the Muslim population of the annexed regions — majority Albanian in the countryside, Turkish in the towns, about one third of the regional population. Academic estimates: ~49,000 Albanians among at least 71,000 Muslims expelled or fled without return (Jagodic 1998; Stefanovic 2005); Albanian historiography cites higher figures. Refugees (muhaxhire) resettled largely in Ottoman Kosovo.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1912, 'Kosovo and Vardar Macedonia', 'CONQUEST_MILITARY', 'First Balkan War (October-November 1912): Serbian army conquered Kosovo and Vardar Macedonia from the Ottoman Empire. The Carnegie Endowment''s 1914 International Commission documented massacres of Albanian civilians, village burnings and forced conversions by Serbian forces, alongside grave violations by all belligerents. Albanian and Macedonian populations passed under Serbian military rule without consent.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1913, 'Kosovo, Vardar Macedonia, eastern Sandzak of Novi Pazar', 'TREATY', 'Treaties of London (May 1913) and Bucharest (August 1913) after the Second Balkan War confirmed Serbia''s possession of Kosovo, most of Vardar Macedonia (disputed with Bulgaria) and the eastern Sandzak (partitioned with Montenegro), nearly doubling the state''s territory. Rule remained contested and militarized until 1915.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1915, 'Entire state territory', 'CONQUEST_MILITARY', 'TERRITORIAL LOSS: combined Austro-Hungarian, German and Bulgarian offensive (October-November 1915) conquered all of Serbia; the country was partitioned into Austro-Hungarian and Bulgarian occupation zones (internment, forced Bulgarianization, bloody suppression of the 1917 Toplica uprising). The Serbian army and tens of thousands of civilians retreated through the Albanian mountains in winter 1915-16 with mass deaths from cold, hunger and disease; the army was evacuated to Corfu.', NULL, 0.95);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 1918, 'Entire state territory', 'LIBERATION', 'Salonika front breakthrough (September 1918) led to the liberation of Serbia by Serbian and Allied forces (Belgrade retaken 1 November 1918). On 1 December 1918 the Kingdom of Serbia merged into the newly proclaimed Kingdom of Serbs, Croats and Slovenes, ending its separate statehood. Serbia''s WWI losses were among the highest per-capita of any belligerent (16-28% of pre-war population depending on methodology).', NULL, 0.95);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Jagodic, Milos. ''The Emigration of Muslims from the New Serbian Regions 1877/1878''. Balkanologie, Vol. II, no. 2 (1998).', 'https://journals.openedition.org/balkanologie/265', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Report of the International Commission to Inquire into the Causes and Conduct of the Balkan Wars. Washington D.C.: Carnegie Endowment for International Peace, 1914.', 'https://archive.org/details/reportofinternat00inteuoft', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Radivojevic, Biljana and Goran Penev. ''Demographic Losses of Serbia in the First World War and Their Long-Term Consequences''. Economic Annals, Vol. 59, no. 203 (2014), pp. 29-54.', 'https://ea.ekof.bg.ac.rs/index.php/economicannals/article/view/181', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Stefanovic, Djordje. ''Seeing the Albanians through Serbian Eyes: The Inventors of the Tradition of Intolerance and their Critics, 1804-1939''. European History Quarterly, Vol. 35, no. 3 (2005), pp. 465-492.', NULL, 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Jelavich, Barbara. History of the Balkans: Eighteenth and Nineteenth Centuries (Vol. 1) and Twentieth Century (Vol. 2). Cambridge: Cambridge University Press, 1983.', NULL, 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 'Hatt-i Sharif of 1830 (Ottoman imperial decree recognizing the autonomous hereditary Principality of Serbia) and Treaty of Berlin, 13 July 1878, Articles XXXIV-XLII (independence and borders of Serbia).', NULL, 'primary');

-- ── kingdom_shs_yugoslavia ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('Краљевина Срба, Хрвата и Словенаца', 'sr', 'kingdom', 1918, 1941,
        'Београд (Belgrade)', 44.8167, 20.4667, '{"type": "Polygon","coordinates": [[[13.9,45.45],[16.5,43.3],[19.35,41.87],[20.55,41.4],[20.98,40.86],[22.93,41.34],[22.98,43.1],[22.68,44.22],[21.2,45.3],[20.1,46.05],[18.9,45.92],[16.4,46.85],[14.45,46.44],[13.9,45.45]]]}', 'historical_approximation',
        0.75, 'confirmed', 'ETHICS-002: Montenegro''s entry into the new state was not a free union: the Podgorica Assembly (24-29 November 1918), convened under Serbian military presence with an irregular electoral procedure, deposed King Nikola I and proclaimed unconditional union with Serbia, and the Greens'' Christmas Uprising (January 1919) was suppressed by the Serbian army and pro-union White militias, with executions, house-burnings and guerrilla fighting into the mid-1920s; Montenegrin historiography (Pavlović 2008) documents this as annexation, Serbian unification historiography as voluntary union — both readings are recorded, not arbitrated. ETHICS-002: On 6 January 1929 King Aleksandar I Karađorđević abolished the constitution, dissolved parliament and banned national and ethnic parties (the 6 January Dictatorship), months after Croat Peasant Party leader Stjepan Radić was fatally shot by a Serb deputy inside the Belgrade parliament (June 1928); the 1929 renaming to Yugoslavia imposed a unitary identity that suppressed Croat, Macedonian and Albanian national expression — Vardar Macedonia was administered as ''South Serbia'' and interwar agrarian colonization settled Serb colonists on lands of Albanians and Turks in Kosovo and Macedonia. ETHICS-002: The state ended through external violence: Nazi Germany, with Italy, Hungary and Bulgaria, invaded on 6 April 1941, opening with the Luftwaffe terror bombing of Belgrade that killed thousands of civilians; after the capitulation of 17 April 1941 the invaders partitioned the country and installed the Ustaša Independent State of Croatia, which carried out genocide against Serbs, Roma and Jews. ETHICS-001: the primary name is the attested founding Serbian-Cyrillic form; the 1918-1920 proclamation form ''Краљевство Срба, Хрвата и Словенаца'' and the 1929 ''Краљевина Југославија'' are recorded as period variants rather than replacing it.', 'Q191077',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[13.9,45.45],[16.5,43.3],[19.35,41.87],[20.55,41.4],[20.98,40.86],[22.93,41.34],[22.98,43.1],[22.68,44.22],[21.2,45.3],[20.1,46.05],[18.9,45.92],[16.4,46.85],[14.45,46.44],[13.9,45.45]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Kraljevina Srba, Hrvata i Slovenaca', 'sh', 1918, 1929, 'Serbo-Croatian Latin script, official alongside Cyrillic; also romanization of the primary name', 'sr.wikipedia; Srpska enciklopedija');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Kingdom of Serbs, Croats and Slovenes', 'en', 1918, 1929, 'English name of the founding period', 'Banac 1984; Lampe 2000');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Краљевство Срба, Хрвата и Словенаца', 'sr', 1918, 1920, 'Form used in the 1 December 1918 unification proclamation (''Kraljevstvo''); changed to ''Kraljevina'' by decision of the Provisional National Representation on 15 July 1920', 'Srpska enciklopedija; sr.wikipedia');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Краљевина Југославија', 'sr', 1929, 1941, 'Official name from 3 October 1929 (royal decree of Aleksandar I)', 'Wikidata Q191077 (verified); Djokić 2007');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Kraljevina Jugoslavija', 'sh', 1929, 1941, 'Latin-script form (identical in Slovene)', 'sr.wikipedia');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Kingdom of Yugoslavia', 'en', 1929, 1941, 'English name after the 1929 renaming', 'Lampe 2000; Tomasevich 2001');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 1918, 'Montenegro', 'CESSION_FORCED', 'The Podgorica Assembly (in session 24-29 November 1918), convened under Serbian army presence with an irregular electoral procedure, deposed King Nikola I Petrović-Njegoš and proclaimed unconditional union with Serbia. The Greens'' Christmas Uprising against the annexation (Cetinje, 7 January 1919, led by Krsto Popović) was crushed by Serbian troops and pro-union White militias; guerrilla resistance and reprisals continued into the mid-1920s. Montenegrin and part of Western historiography (Pavlović 2008) call this an annexation; Serbian unification historiography calls it a voluntary union.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 1918, 'All South Slav lands (Serbia, Montenegro, former Habsburg South Slav territories)', 'TREATY', '1 December 1918: Regent Aleksandar Karađorđević proclaimed the Kingdom of Serbs, Croats and Slovenes, uniting the Kingdom of Serbia (with newly absorbed Montenegro) and the State of Slovenes, Croats and Serbs formed from the collapsed Austria-Hungary — a negotiated unification (Corfu Declaration 1917, National Council address), not a treaty in the strict sense.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 1920, 'Istria, Zadar and Adriatic islands', 'TREATY', 'Treaty of Rapallo (12 November 1920): the Kingdom ceded Istria, Zadar and several islands to Italy; roughly half a million South Slavs (Slovenes, Croats) came under Italian rule and subsequent forced Italianization. Rijeka went to Italy by the 1924 Treaty of Rome, with Sušak remaining Yugoslav.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 1941, 'Entire kingdom', 'CONQUEST_MILITARY', 'Axis invasion from 6 April 1941, opened by Nazi Germany''s terror bombing of Belgrade that killed thousands of civilians; unconditional surrender on 17 April 1941. Nazi Germany, Fascist Italy, Hungary and Bulgaria partitioned the country, installing the Ustaša-run Independent State of Croatia (10 April 1941), occupied Serbia, the Italian Governorate of Montenegro and the Province of Ljubljana.', NULL, 0.9);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Ivo Banac, The National Question in Yugoslavia: Origins, History, Politics, Cornell University Press, 1984.', 'https://www.cornellpress.cornell.edu/book/9780801494932/the-national-question-in-yugoslavia/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'John R. Lampe, Yugoslavia as History: Twice There Was a Country, 2nd ed., Cambridge University Press, 2000.', 'https://www.cambridge.org/9780521774017', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Dejan Djokić, Elusive Compromise: A History of Interwar Yugoslavia, Hurst / Columbia University Press, 2007.', 'https://muse.jhu.edu/article/817674/summary', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Srdja Pavlović, Balkan Anschluss: The Annexation of Montenegro and the Creation of the Common South Slavic State, Purdue University Press, 2008.', 'https://www.press.purdue.edu/9781557534651/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 'Jozo Tomasevich, War and Revolution in Yugoslavia, 1941-1945: Occupation and Collaboration, Stanford University Press, 2001.', 'https://www.sup.org/books/history/war-and-revolution-yugoslavia-1941-1945', 'academic');

-- ── diriyah_emirate ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('إمارة الدرعية', 'ar', 'emirate', 1744, 1818,
        'Diriyah (ad-Dirʿiyyah)', 24.7333, 46.5756, '{"type": "Polygon","coordinates": [[[42.5,20.5],[45.5,19.8],[47.5,21.5],[48.5,24.5],[48,26.5],[46.5,27.8],[43.5,27.5],[41.8,25.5],[42,22.5],[42.5,20.5]]]}', 'historical_approximation',
        0.65, 'confirmed', 'ETHICS-002: The state''s expansion was overwhelmingly military and accompanied by explicit religious violence. On 21 April 1802 (date disputed, possibly 1801) roughly 12,000 Wahhabi raiders from Najd, sent under Emir Abdulaziz bin Muhammad Al Saud, sacked the Shia holy city of Karbala in Ottoman Iraq, killed an estimated 2,000-5,000 inhabitants, plundered the shrine of Imam Husayn and destroyed its dome — an atrocity still central to Shia collective memory. In 1803 Saudi forces massacred inhabitants of Taif, and after taking Mecca (1803) and Medina (1804-05) they demolished the venerated tombs of al-Baqi cemetery and Jannat al-Mualla in 1806, destruction condemned across much of the Muslim world. The state itself was destroyed by comparable violence: the Ottoman-Egyptian army of Ibrahim Pasha besieged Diriyah for months in 1818, razed the city in 1819, and beheaded the captured Imam Abdullah bin Saud in Istanbul. ETHICS-001: the primary name is the attested Arabic إمارة الدرعية; "First Saudi State" (الدولة السعودية الأولى) is a retrospective label, and the 2022 Saudi royal decree moving the official founding from the 1744 Wahhabi pact back to Muhammad ibn Saud''s 1727 accession is a politicized modern re-dating that de-emphasizes the state''s Wahhabi origins — both dates are documented here rather than arbitrated. Non-Western historiography is represented via the contemporary Najdi chronicle of Ibn Bishr; Shia accounts of Karbala provide the victims'' perspective against Najdi court chronicles that celebrate the raid.', 'Q146871',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[42.5,20.5],[45.5,19.8],[47.5,21.5],[48.5,24.5],[48,26.5],[46.5,27.8],[43.5,27.5],[41.8,25.5],[42,22.5],[42.5,20.5]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'Emirate of Diriyah', 'en', 1744, 1818, 'English name emphasizing the capital; common in historiography', 'Wikipedia / Rentz 2004');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'First Saudi State', 'en', 1744, 1818, 'Retrospective English label used in Saudi and Western historiography', 'Al-Rasheed 2002; Wikidata Q146871');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'ʾImārat ad-Dirʿiyya', 'ar-Latn', 1744, 1818, 'Romanization of the attested Arabic name إِمَارَةُ الدِّرْعِيَّة', 'Wikipedia (attested form)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'الدولة السعودية الأولى', 'ar', NULL, NULL, 'ad-Dawla as-Suʿūdiyya al-ʾŪlā — retrospective official Arabic designation used in Saudi historiography and state commemoration', 'Wikidata Q146871 Arabic label; Saudipedia');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'ad-Dawla as-Suʿūdiyya al-ʾŪlā', 'ar-Latn', NULL, NULL, 'Romanization of the retrospective Arabic designation', 'Wikipedia');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 1744, 'Diriyah (central Najd)', 'TREATY', 'Pact between Emir Muhammad ibn Saud (ruler of Diriyah since 1727) and the preacher Muhammad ibn Abd al-Wahhab fused Al Saud political power with the Wahhabi religious mission, founding the expansionist emirate.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 1773, 'Riyadh and Najd', 'CONQUEST_MILITARY', 'Abdulaziz bin Muhammad captured Riyadh after a long war against Dahham ibn Dawwas, consolidating Saudi-Wahhabi military control over central Najd; al-Hasa on the Gulf coast followed by 1795.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 1803, 'Hejaz (Taif, Mecca; Medina 1804-05)', 'CONQUEST_MILITARY', 'Saudi forces under Saud bin Abdulaziz took Taif (with a massacre of inhabitants), then Mecca in 1803 and Medina by 1804-05; in 1806 they demolished the domed tombs of al-Baqi cemetery in Medina and Jannat al-Mualla in Mecca (including the tomb of Khadijah) as idolatrous. The 21 April 1802 sack of Shia Karbala (2,000-5,000 killed, shrine of Imam Husayn plundered) preceded this campaign.', NULL, 0.75);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 1818, 'Diriyah and all Saudi territories', 'CONQUEST_MILITARY', 'Ottoman-Egyptian army under Ibrahim Pasha, son of Muhammad Ali of Egypt, ended the Ottoman-Saudi (Wahhabi) War of 1811-1818: after a months-long siege, Imam Abdullah bin Saud surrendered on 9 September 1818; Diriyah was razed in 1819 and Abdullah was beheaded in Istanbul.', NULL, 0.85);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'Madawi Al-Rasheed, A History of Saudi Arabia, Cambridge University Press, 2002 (2nd ed. 2010)', 'https://www.cambridge.org/core/books/history-of-saudi-arabia/3B0C42E92B2A83F79E85D28083D2D223', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'Alexei Vassiliev, The History of Saudi Arabia, Saqi Books, London, 1998 (US ed. New York University Press, 2000)', 'https://search.worldcat.org/title/39641842', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'George S. Rentz, The Birth of the Islamic Reform Movement in Saudi Arabia: Muhammad ibn ''Abd al-Wahhab (1703/4-1792) and the Beginnings of Unitarian Empire in Arabia, Arabian Publishing, London, 2004', 'https://arabian-publishing.com/product/the-birth-of-the-islamic-reform-movement-in-saudi-arabia', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 'Uthman ibn Abdullah ibn Bishr, ''Unwan al-majd fi tarikh Najd (The Mark of Glory in the History of Najd), 19th-century Najdi chronicle covering 1745-1850, 2 vols.', 'https://search.worldcat.org/title/''Unwan-al-majd-fi-tarikh-Najd/oclc/476235996', 'primary');

-- ── najd_emirate ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('إمارة نجد', 'ar', 'emirate', 1824, 1891,
        'Riyadh (الرياض)', 24.6333, 46.7167, '{"type": "Polygon","coordinates": [[[44,20.8],[46.5,20.5],[48.5,21.8],[50.2,24],[50.1,26.6],[48.8,27.3],[46.8,27.2],[43.5,26.8],[43.2,24.5],[43.8,22.3],[44,20.8]]]}', 'historical_approximation',
        0.65, 'confirmed', 'ETHICS-001: The primary name Imarat Najd (Emirate of Najd) is the attested contemporary designation; "Second Saudi State" (al-Dawla al-Su''udiyya al-Thaniya) is a retrospective label of modern Saudi historiography and is kept as a variant, not the primary name. ETHICS-002: The state was founded and ended by military violence, perpetrators named: Turki ibn Abdullah''s forces besieged and expelled the Egyptian garrison of Muhammad Ali''s occupation army from Riyadh in 1824, six years after Ibrahim Pasha''s Ottoman-Egyptian army razed Diriyah (1818) and had Imam Abdullah bin Saud executed in Istanbul. ETHICS-002: The 1830 reconquest of al-Hasa and Qatif placed the region''s large Twelver Shia population under a Wahhabi-legitimated state that treated them as tributary subjects with discriminatory taxation. Dynastic violence was chronic and is stated plainly: Turki was assassinated in 1834 by his cousin Mishari bin Abdul Rahman (executed in turn by Faisal bin Turki); Egypt''s Khurshid Pasha re-invaded in 1838, deporting Imam Faisal to Cairo and installing Khalid bin Saud as vassal until Faisal''s return in 1843. After Faisal''s death (1865) the fratricidal civil war between his sons Abdullah and Saud devastated Najd, and Abdullah''s 1871 appeal to Ottoman governor Midhat Pasha ended in betrayal — the Ottomans annexed al-Hasa for themselves instead of helping him. The state was destroyed at the Battle of Mulayda (21 January 1891) by Muhammad bin Abdullah Al Rashid of Jabal Shammar, and the Al Saud under Abdul Rahman bin Faisal fled into exile in Kuwait. Non-Western historiography is foregrounded via the contemporary Najdi chronicle of Ibn Bishr.', 'Q146862',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[44,20.8],[46.5,20.5],[48.5,21.8],[50.2,24],[50.1,26.6],[48.8,27.3],[46.8,27.2],[43.5,26.8],[43.2,24.5],[43.8,22.3],[44,20.8]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'Emirate of Najd', 'en', 1824, 1891, 'official designation, attested in English-language historiography', 'en.wikipedia.org/wiki/Second_Saudi_state');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'Emirate of Nejd', 'en', 1824, 1891, 'alternative English spelling', NULL);
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'Second Saudi State', 'en', NULL, NULL, 'retrospective historiographic name (ETHICS-001: modern Saudi periodization, not contemporary usage)', 'Madawi al-Rasheed, A History of Saudi Arabia (2002)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'الدولة السعودية الثانية', 'ar', NULL, NULL, 'al-Dawla al-Su''udiyya al-Thaniya — retrospective Arabic historiographic name', 'ar.wikipedia.org; saudipedia.com');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'Imārat Najd', 'ar-Latn', 1824, 1891, 'romanization of the primary name', NULL);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 1824, 'Riyadh and central Najd', 'CONQUEST_MILITARY', 'Turki ibn Abdullah Al Saud besieged and expelled the Egyptian garrison (Muhammad Ali''s occupation forces) from Riyadh, restoring Al Saud rule six years after the Ottoman-Egyptian destruction of Diriyah; Riyadh made the new capital.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 1830, 'al-Hasa and Qatif (Eastern Arabia)', 'CONQUEST_MILITARY', 'Turki ibn Abdullah reconquered al-Hasa, Qatif and Saihat, extending Saudi rule to the Gulf coast; the region''s Shia population became tributary subjects of the Wahhabi-legitimated state.', NULL, 0.75);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 1871, 'al-Hasa and Qatif', 'CONQUEST_MILITARY', 'Ottoman al-Hasa Expedition under Baghdad governor Midhat Pasha: invited by Imam Abdullah bin Faisal against his brother Saud during the Saudi civil war, the Ottomans instead annexed al-Hasa outright (held until 1913), stripping the emirate of its eastern province.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 1891, 'Najd (entire state)', 'CONQUEST_MILITARY', 'Battle of Mulayda (21 January 1891): Muhammad bin Abdullah Al Rashid of the Emirate of Jabal Shammar defeated the last imam Abdul Rahman bin Faisal; the state ceased to exist and the Al Saud went into exile in Kuwait.', NULL, 0.9);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'R. Bayly Winder, Saudi Arabia in the Nineteenth Century, London: Macmillan / New York: St. Martin''s Press, 1965 (xiv+312 pp.) — the standard monograph on the second Saudi state.', 'https://link.springer.com/book/10.1007/978-1-349-81723-8', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'Madawi al-Rasheed, A History of Saudi Arabia, Cambridge: Cambridge University Press, 2002 (2nd ed. 2010) — history by a Saudi-born scholar, critical of official dynastic narratives.', 'https://www.cambridge.org/core/books/history-of-saudi-arabia/1C499DA74EC7147305236A70C1F7C7DB', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'Alexei Vassiliev, The History of Saudi Arabia, London: Saqi Books, 1998 (576 pp., ISBN 0-86356-935-8) — Russian-school historiography drawing on Arabic, Turkish and Russian sources.', 'https://saqibooks.com/books/saqi/the-history-of-saudi-arabia/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 'ʿUthmān ibn ʿAbd Allāh Ibn Bishr, ʿUnwān al-majd fī tārīkh Najd [The Sign of Glory in the History of Najd], vol. 2 completed 1270 AH / 1853-54 CE — contemporary Najdi chronicle covering the first and second Saudi states to 1854.', 'https://onlinebooks.library.upenn.edu/webbin/book/lookupid?key=ha001866084', 'primary');

-- ── nepal_republic ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल', 'ne', 'republic', 2008, NULL,
        'Kathmandu (काठमाडौँ)', 27.7172, 85.324, '{"type": "Polygon","coordinates": [[[80.1,28.7],[81.6,28.1],[83,27.4],[85,26.9],[86.5,26.55],[88.15,26.4],[88.2,27.1],[88,27.9],[86.5,28.1],[84.2,29.3],[82.2,30.2],[80.4,29.9],[80.1,28.7]]]}', 'historical_approximation',
        0.85, 'confirmed', 'ETHICS-002: The republic was born from the 1996-2006 civil war launched by the Communist Party of Nepal (Maoist) against the Kingdom of Nepal: approximately 13,000 deaths documented by OHCHR (Nepal Conflict Report, 2012), with Nepal government figures reaching ~17,000; INSEC data attribute the majority of documented killings to state security forces (Royal Nepal Army and police, 8,200+ killed 1996-2005) versus 4,000+ killed by the Maoists — both perpetrators named explicitly. ETHICS-002: Over 1,300 people were forcibly disappeared during the war, most by state forces, with Tharu victims of Bardiya district grossly overrepresented; transitional justice (TRC and Commission on Enforced Disappearances) has delivered near-total impunity to date. ETHICS-002: During the September 2015 constitution promulgation, more than 50 people died in the Terai unrest overall (Aug 2015-Feb 2016) - protesters, mostly Madhesi and Tharu, killed by police, and at least 9 police killed by protesters; Human Rights Watch (''Like We Are Not Nepali'', 2015) documented unlawful killings on both sides including excessive police force; no senior official held accountable, and the subsequent 135-day border blockade (Madhesi groups, partially supported by India) caused a humanitarian fuel and medicine crisis. ETHICS-003: Madhesi, Tharu, Janajati and Dalit communities contest the 2015 federal province boundaries and citizenship clauses as perpetuating historic domination by hill high-caste (Khas Arya) elites; this record documents the dispute without arbitrating it. ETHICS-001: the primary name is the attested Nepali Devanagari form; note the 2015 Constitution (Art. 4) formally names the state simply ''Nepal'', while the full republican formula remains in official and international use since 2008. ETHICS-003: the Kalapani-Lipulekh-Limpiyadhura territory (~335-372 km2) is claimed by Nepal (2020 constitutional map amendment) but administered by India — both versions are noted, neither endorsed.', 'Q837',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[80.1,28.7],[81.6,28.1],[83,27.4],[85,26.9],[86.5,26.55],[88.15,26.4],[88.2,27.1],[88,27.9],[86.5,28.1],[84.2,29.3],[82.2,30.2],[80.4,29.9],[80.1,28.7]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'Federal Democratic Republic of Nepal', 'en', 2008, NULL, 'Official English long-form name since the 28 May 2008 republic declaration', 'Wikidata Q837; Constituent Assembly declaration 2008');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'Saṅghīya Loktāntrik Gaṇatantra Nepāl', 'ne-Latn', 2008, NULL, 'IAST-style romanization of the Nepali official name', 'Romanization of attested Devanagari form');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'नेपाल', 'ne', 2015, NULL, 'Constitutional short name: Constitution of Nepal 2015, Art. 4, names the state ''Nepal''; a Nov 2020 government directive limited letterhead use of the full republican formula', 'Constitution of Nepal 2015 (Nepal Law Commission)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'Nepal', 'en', 2008, NULL, 'Common short name', 'Wikidata Q837');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 2008, 'Entire state (former Kingdom of Nepal)', 'REVOLUTION', 'On 28 May 2008 the 1st Constituent Assembly, elected on 10 April 2008 under the Comprehensive Peace Accord (21 Nov 2006), abolished the 240-year Shah monarchy by a 560-4 vote and declared the Federal Democratic Republic. The peaceful vote was the direct outcome of the 1996-2006 Maoist civil war (~13,000-17,000 dead; state forces the larger documented killer) and the April 2006 Jana Andolan II mass uprising, in which royal security forces killed ~18-25 protesters before King Gyanendra capitulated.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 2020, 'Kalapani-Lipulekh-Limpiyadhura (far-west, ~335-372 km2)', 'UNKNOWN', 'Constitutional amendment (June 2020) added the India-administered Kalapani-Lipulekh-Limpiyadhura triangle to Nepal''s official map and coat of arms. This is a cartographic-legal claim only: India continues to administer the territory and rejects the claim. No change of actual control occurred; the dispute remains open.', NULL, 0.75);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'John Whelpton, A History of Nepal, Cambridge University Press, 2005.', 'https://www.cambridge.org/core/books/history-of-nepal/340C4E78125368B8D0623201D61E5A9E', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'Sebastian von Einsiedel, David M. Malone and Suman Pradhan (eds.), Nepal in Transition: From People''s War to Fragile Peace, Cambridge University Press, 2012.', 'https://www.cambridge.org/core/books/nepal-in-transition/FAA071F9BDF58C731109296F59C86F4A', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'Prashant Jha, Battles of the New Republic: A Contemporary History of Nepal, Hurst & Company, 2014. (Nepali/South Asian author — non-Western historiography per ETHICS values)', 'https://www.hurstpublishers.com/book/battles-new-republic/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'OHCHR, Nepal Conflict Report: An analysis of conflict-related violations of international human rights law and international humanitarian law between February 1996 and 21 November 2006, United Nations Office of the High Commissioner for Human Rights, 2012.', 'https://www.ohchr.org/en/documents/country-reports/nepal-conflict-report', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'Constitution of Nepal, 2015 (नेपालको संविधान), Nepal Law Commission, promulgated 20 September 2015.', 'https://lawcommission.gov.np/content/13437/nepal-s-constitution/', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 'Human Rights Watch, "Like We Are Not Nepali": Protest and Police Crackdown in the Terai Region of Nepal, HRW, 2015.', 'https://www.hrw.org/report/2015/10/16/we-are-not-nepali/protest-and-police-crackdown-terai-region-nepal', 'primary');

-- ── ndebele_kingdom ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
                          capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
                          confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('Mthwakazi', 'nd', 'kingdom', 1838, 1893,
        'koBulawayo', -20.3023, 28.6264, '{"type": "Polygon","coordinates": [[[27.2,-21.5],[28.5,-21.8],[29.8,-21],[30,-20],[29.5,-19],[28.5,-18.5],[27,-19],[26.5,-20.3],[27.2,-21.5]]]}', 'historical_approximation',
        0.65, 'confirmed', 'ETHICS-002: The kingdom was destroyed by Cecil Rhodes''s British South Africa Company in the First Matabele War (October 1893 - January 1894): company Maxim guns, used here in battle for the first time, killed roughly 1,500 Ndebele at the Shangani (25 Oct 1893) and about 2,500 at Bembesi (1 Nov 1893) against single-digit company battle deaths; koBulawayo was occupied on 4 November 1893, Lobengula died in flight in January 1894, and the company''s Victoria Agreement ''loot'' terms promised each volunteer about 6,000 acres of seized Ndebele land plus a share of confiscated cattle. ETHICS-002: The 1888 Rudd Concession was obtained by deception - missionary interpreter Charles Helm mistranslated the text, and the verbal assurances given to Lobengula (no more than ten diggers, subject to Ndebele law) were deliberately omitted from the written English version; Lobengula repudiated the concession and protested to Queen Victoria, and was ignored, while Rhodes used it to secure the BSAC royal charter in 1889. ETHICS-002: The Ndebele state itself was built by conquest: Mzilikazi''s forces subjugated the Rozvi remnants (c. 1838-1840) and extracted tribute, cattle and captives from western Shona and Kalanga communities, incorporated at the bottom of a three-tier status hierarchy (abeZansi, abeNhla, amaHole). ETHICS-003: the ''predatory raiding state'' image is contested - Julian Cobbing and Zimbabwean historians such as Ndlovu-Gatsheni argue it was inflated by BSAC propaganda to justify the 1893 invasion, and this record reports both the violence and the dispute. ETHICS-001: the primary name Mthwakazi is the attested endonym; ''Matabele'' is a Sotho-Tswana-mediated exonym adopted by the British and kept only as a variant.', 'Q1193853',
        ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[27.2,-21.5],[28.5,-21.8],[29.8,-21],[30,-20],[29.5,-19],[28.5,-18.5],[27,-19],[26.5,-20.3],[27.2,-21.5]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Mthwakazi', 'nd', 1838, NULL, 'Attested endonym; per Ndebele tradition the name Mzilikazi gave his nation (''something which became big at conception''). Latin script is native for isiNdebele.', 'Wikidata Q1193853; Ndlovu-Gatsheni, The Ndebele Nation (2009)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Ndebele Kingdom', 'en', NULL, NULL, 'Modern English scholarly name (also ''Northern Ndebele Kingdom'' to distinguish from the Southern/Transvaal Ndebele)', 'Rasmussen 1978; Cobbing 1976');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Matabele Kingdom', 'en', 1838, 1893, '19th-century British colonial name, from the Sotho-Tswana exonym ''Matebele'' transmitted to British travellers; not the endonym', 'Wikipedia, Northern Ndebele people');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Matabeleland', 'en', 1838, NULL, 'British name for the territory; retained as a Rhodesian and then Zimbabwean regional name after the conquest', 'Wikidata Q1266775 (modern region)');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 1838, 'Matabeleland highveld (southwestern Zimbabwean plateau)', 'CONQUEST_MILITARY', 'After defeats by Voortrekker commandos in the Transvaal (Vegkop 1836, Mosega/eGabeni 1837), Mzilikazi''s Khumalo-led Ndebele crossed the Limpopo and settled the southwestern Zimbabwean plateau (c. 1838-1840), displacing and forcibly incorporating local Kalanga and Rozvi-Shona communities.', NULL, 0.75);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 1840, 'Former Rozvi heartland (Danamombe, Insiza-Mberengwa belt)', 'CONQUEST_MILITARY', 'Ndebele forces defeated the Rozvi Mutinhima house; the remaining Rozvi royal houses, leaderless since Nyamazana''s Ngoni sacked Danamombe and killed Changamire Chirisamhuru c. 1835, submitted one by one c. 1839-1840 and were reduced to tributary status.', NULL, 0.6);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 1888, 'Mineral rights over Matabeleland, Mashonaland and adjoining territories', 'TREATY', 'Rudd Concession (30 Oct 1888): Lobengula granted exclusive mineral rights to Cecil Rhodes''s agents Charles Rudd, Rochfort Maguire and Francis Thompson for 100 pounds per lunar month, 1,000 Martini-Henry rifles, 100,000 cartridges and a Zambezi steamboat. Interpreter Charles Helm''s mistranslation and the exclusion of verbal assurances (max ten diggers, subject to Ndebele law) from the written English text made it fraudulent; Lobengula repudiated it and protested to Queen Victoria without effect. It became the legal basis of the British South Africa Company''s royal charter (Oct 1889) and the 1890 Pioneer Column occupation of Mashonaland.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 1893, 'Entire kingdom', 'CONQUEST_MILITARY', 'First Matabele War: British South Africa Company columns using Maxim guns killed roughly 1,500 Ndebele at the Shangani (25 Oct 1893) and about 2,500 at Bembesi (1 Nov 1893) against single-digit company battle deaths; Lobengula burned koBulawayo and fled north; the BSAC occupied Bulawayo on 4 Nov 1893 and seized Ndebele land and cattle. Lobengula died in flight, probably of smallpox, on 22/23 Jan 1894.', NULL, 0.85);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'R. Kent Rasmussen, Migrant Kingdom: Mzilikazi''s Ndebele in South Africa, London: Rex Collings / Cape Town: David Philip, 1978', 'https://books.google.com/books/about/Migrant_Kingdom.html?id=M2QfAAAAMAAJ', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Julian R. D. Cobbing, The Ndebele under the Khumalos, 1820-1896, PhD thesis, University of Lancaster, 1976', 'https://search.worldcat.org/title/ndebele-under-the-khumalos-1820-1896/oclc/733067611', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Sabelo J. Ndlovu-Gatsheni, The Ndebele Nation: Reflections on Hegemony, Memory and Historiography, Amsterdam: Rozenberg / Pretoria: UNISA Press, 2009', 'https://rozenbergquarterly.com/the-ndebele-nation/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Julian Cobbing, ''The Absent Priesthood: Another Look at the Rhodesian Risings of 1896-1897'', Journal of African History 18(1), 1977, Cambridge University Press', 'https://www.cambridge.org/core/journals/journal-of-african-history/article/abs/absent-priesthood-another-look-at-the-rhodesian-risings-of-189618971/0E41064A88F519A8F45F2FBDC8428DFC', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Mthwakazi'), 'Rudd Concession, original text granted by Lobengula to Rudd, Maguire and Thompson, 30 October 1888 (South African History Online archive)', 'https://sahistory.org.za/archive/rudd-concession-king-lobengula-matabeleland-1888', 'primary');

-- ── rename nativo #128: ล้านช้าง (thai, lang=lo mismatch) → forma lao attestata ──
UPDATE geo_entities SET name_original = 'ອານາຈັກລ້ານຊ້າງ' WHERE id = 128 AND name_original = 'ล้านช้าง';
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source)
SELECT 128, 'ล้านช้าง', 'th', 1354, 1707, 'forma in script thai (era erroneamente il nome primario con lang=lo fino al rename ETHICS-001 in v6.99.120)', 'storiografia thai; ETHICS-020'
WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 128 AND name = 'ล้านช้าง');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source)
SELECT 128, 'ລ້ານຊ້າງຮົ່ມຂາວ (Lan Xang Hom Khao)', 'lo', 1354, 1707, 'nome cerimoniale completo attestato dato da Fa Ngum', 'Cronache lao (Nithan Khun Borom); Stuart-Fox 1998'
WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 128 AND name = 'ລ້ານຊ້າງຮົ່ມຂາວ (Lan Xang Hom Khao)');

-- ── catene lao 123/124/125: prepend Lan Xang (#128) ──
UPDATE chain_links SET sequence_order = sequence_order + 1 WHERE chain_id = 123;
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (123, 128, 0, NULL, NULL, false, 'Lan Xang (1354-1707), the unified Lao kingdom of the middle Mekong founded by Fa Ngum with Khmer military backing; capitals Luang Prabang (1354-1560) and Vientiane (1560-1707); partitioned in 1707 after the succession crisis that followed Sourigna Vongsa''s death (1694).', NULL);
UPDATE chain_links SET transition_year = 1707, transition_type = 'PARTITION', is_violent = false, ethical_notes = 'The 1707 partition was a negotiated division between Kingkitsarat (Luang Prabang) and Sai Ong Hue (Vientiane) after an armed standoff.'
WHERE chain_id = 123 AND sequence_order = 1 AND entity_id = 693 AND transition_type IS NULL;

UPDATE chain_links SET sequence_order = sequence_order + 1 WHERE chain_id = 124;
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (124, 128, 0, NULL, NULL, false, 'Lan Xang (1354-1707), the unified Lao kingdom of the middle Mekong founded by Fa Ngum with Khmer military backing; capitals Luang Prabang (1354-1560) and Vientiane (1560-1707); partitioned in 1707 after the succession crisis that followed Sourigna Vongsa''s death (1694).', NULL);
UPDATE chain_links SET transition_year = 1707, transition_type = 'PARTITION', is_violent = false, ethical_notes = 'Northern successor of the 1707 partition, under Kingkitsarat (crowned rival king at Luang Prabang in 1705).'
WHERE chain_id = 124 AND sequence_order = 1 AND entity_id = 364 AND transition_type IS NULL;

UPDATE chain_links SET sequence_order = sequence_order + 1 WHERE chain_id = 125;
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (125, 128, 0, NULL, NULL, false, 'Lan Xang (1354-1707), the unified Lao kingdom of the middle Mekong founded by Fa Ngum with Khmer military backing; capitals Luang Prabang (1354-1560) and Vientiane (1560-1707); partitioned in 1707 after the succession crisis that followed Sourigna Vongsa''s death (1694).', NULL);
UPDATE chain_links SET transition_year = 1713, transition_type = 'PARTITION', is_violent = false, ethical_notes = 'Champasak separated from the Vientiane sphere in 1713 after a southern secession, completing the three-way division of Lan Xang.'
WHERE chain_id = 125 AND sequence_order = 1 AND entity_id = 363 AND transition_type IS NULL;

UPDATE dynasty_chains SET name = 'Lan Xang partition — Vientiane line: ອານາຈັກລ້ານຊ້າງ → ອານາຈັກວຽງຈັນ → Siam' WHERE id = 123;
UPDATE dynasty_chains SET name = 'Lan Xang partition — Luang Prabang line: ອານາຈັກລ້ານຊ້າງ → ອານາຈັກຫລວງພະບາງ → French Indochina' WHERE id = 124;
UPDATE dynasty_chains SET name = 'Lan Xang partition — Champasak line: ອານາຈັກລ້ານຊ້າງ → ອານາຈັກຈຳປາສັກ → French Indochina' WHERE id = 125;

-- ── catena cambogiana 126: prepend Khmer Empire (#19) + post-Angkor ──
UPDATE chain_links SET sequence_order = sequence_order + 2 WHERE chain_id = 126;
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (126, 19, 0, NULL, NULL, false, 'The Khmer Empire (802-1431), the Angkorian state whose capital Yasodharapura was the region''s hegemon for six centuries.', 'Also heads the Thai/Khmer Southeast Asian trunk chain; both successions are real (Ayutthaya absorbed much of the empire''s west; the Khmer royal line continued south-east).');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (126, (SELECT id FROM geo_entities WHERE name_original = 'កម្ពុជា (Longvek-Oudong)'), 1, 1431, 'SUCCESSION', true, 'After Ayutthaya sacked Yasodharapura/Angkor (~1431), the Khmer court relocated south-east (Chaktomuk, then Longvek, then Oudong): the same royal polity relocated, not a new state - typed SUCCESSION with is_violent=true because the trigger was the Ayutthayan conquest.', 'Perpetrator of the 1431 sack named: Ayutthaya (Siam). Longvek fell to Naresuan of Ayutthaya on 3 January 1594 with mass deportations - see the entity record.');
UPDATE chain_links SET transition_year = 1863, transition_type = 'ANNEXATION', is_violent = false WHERE chain_id = 126 AND sequence_order = 2 AND entity_id = 261 AND transition_type IS NULL;
UPDATE dynasty_chains SET name = 'Cambodian state: អាណាចក្រខ្មែរ → កម្ពុជា (Longvek-Oudong) → Indochine française → Kingdom of Cambodia' WHERE id = 126;

-- ── catena serba 34: append Србија → СХС → СФРЈ ──
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (34, (SELECT id FROM geo_entities WHERE name_original = 'Кнежевина Србија'), 4, 1815, 'DECOLONIZATION', true, 'Serbian self-rule re-emerged from the Ottoman Empire through the uprisings of 1804-1815: de facto autonomy from the Second Uprising settlement (1815), hereditary autonomous principality by hatt-i sharif (1830), full international independence at the Treaty of Berlin (1878), kingdom from 1882.', 'The transition was a violent decolonization (two uprisings, 1804-13 and 1815). ETHICS-002: the consolidating Serbian state was also a perpetrator - the 1862-67 removal of the Muslim population from the garrison towns and the 1878 expulsions from the Nis/Toplica sanjaks (~49,000 Albanians among at least 71,000 Muslims) are recorded on the entity.');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (34, (SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 5, 1918, 'UNIFICATION', false, 'On 1 December 1918 the Kingdom of Serbia merged with the State of Slovenes, Croats and Serbs (and, via the contested Podgorica Assembly, with Montenegro) into the Kingdom of Serbs, Croats and Slovenes, renamed Yugoslavia in 1929.', 'The Serbia-side unification was negotiated and peaceful; the Montenegrin absorption was contested and its aftermath violent (Christmas Uprising 1919) - see the Montenegrin chain, where that link is typed ANNEXATION.');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (34, 231, 6, 1945, 'REVOLUTION', true, 'The Axis invasion (April 1941) destroyed the kingdom; after four years of occupation, partition, genocide (NDH camps, Jasenovac) and multi-sided war, the communist Partisans established the Federal People''s Republic (AVNOJ 1943; monarchy abolished 29 November 1945).', 'The 1941-45 period saw occupation, the Holocaust and the Ustasa genocide of Serbs, Roma and Jews, and civil war among resistance movements - the socialist state emerged from that violence, not from a peaceful succession.');
UPDATE dynasty_chains SET name = 'Serbian state trunk: Raska → Srpsko Carstvo → Српска деспотовина → Ottoman → Кнежевина Србија → Југославија (СХС → СФРЈ)' WHERE id = 34;

-- ── catena montenegrina 130: append СХС ──
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (130, (SELECT id FROM geo_entities WHERE name_original = 'Краљевина Срба, Хрвата и Словенаца'), 2, 1918, 'ANNEXATION', true, 'With King Nikola I in exile and the country under Serbian military occupation, the Podgorica Assembly (24-29 November 1918), elected under conditions controlled by unionist forces, deposed the king and declared unconditional union with Serbia; the Greens'' Christmas Uprising (January 1919, Cetinje) was suppressed by the Serbian army and pro-union militias, with guerrilla resistance into the mid-1920s.', 'Montenegrin historiography (Pavlović, ''Balkan Anschluss'') reads the union as annexation; Serbian unionist historiography as voluntary unification - both readings recorded, not arbitrated (no-single-version principle). Typed ANNEXATION with is_violent=true for the armed suppression that followed.');
UPDATE dynasty_chains SET name = 'Montenegrin state: Зета → Црна Гора → Краљевина СХС' WHERE id = 130;

-- ── 3 catene NUOVE ──
INSERT INTO dynasty_chains (name, name_lang, chain_type, region, description, confidence_score, status, ethical_notes, sources)
VALUES ('Saudi dynastic states: إمارة الدرعية → إمارة نجد → المملكة العربية السعودية', 'en', 'DYNASTY', 'Arabian Peninsula / Najd', 'The three Saudi-Wahhabi states of the Al Saud: the Emirate of Diriyah (1744-1818, destroyed by the Ottoman-Egyptian expedition), the Emirate of Najd (1824-1891, ended by the Rashidi conquest at Mulayda), and the Kingdom of Saudi Arabia (proclaimed 1932 after Ibn Saud''s 1902-1932 reconquest and unification).', 0.8, 'confirmed', 'ETHICS-002: every transition in this chain is violent and is recorded as such. The chain is DYNASTIC (same Al Saud house), not an unbroken state: two interregna (1818-1824 under Egyptian occupation after Ibrahim Pasha razed Diriyah and had Imam Abdullah bin Saud executed; 1891-1902 under Rashidi rule with the Al Saud exiled in Kuwait) are documented on the links, not papered over. The third state''s unification was by conquest: Riyadh 1902, Ha''il 1921, the Hejaz 1924-25 (including the Ta''if massacre of 1924, ~300-400 civilians killed by the Ikhwan) - per the cross-check, the 1932 transition is typed UNIFICATION (conquest-built), not ''restoration''. The state-sponsored 2022 re-dating of the first state''s founding to 1727 is treated as politicized periodization (see the Diriyah entity record).', '[{"citation": "Madawi Al-Rasheed, A History of Saudi Arabia, Cambridge University Press, 2002 (2nd ed. 2010)", "url": null, "source_type": "academic"}, {"citation": "Alexei Vassiliev, The History of Saudi Arabia, Saqi Books, 1998", "url": null, "source_type": "academic"}, {"citation": "R. Bayly Winder, Saudi Arabia in the Nineteenth Century, Macmillan, 1965", "url": null, "source_type": "academic"}]');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Saudi dynastic states: إمارة الدرعية → إمارة نجد → المملكة العربية السعودية'), (SELECT id FROM geo_entities WHERE name_original = 'إمارة الدرعية'), 0, NULL, NULL, false, 'The first Saudi state: the 1744 pact between Muhammad ibn Saud and Muhammad ibn Abd al-Wahhab turned the Diriyah town emirate into an expansionist religious-political state that conquered Najd, al-Hasa and the Hejaz.', NULL);
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Saudi dynastic states: إمارة الدرعية → إمارة نجد → المملكة العربية السعودية'), (SELECT id FROM geo_entities WHERE name_original = 'إمارة نجد'), 1, 1824, 'RESTORATION', true, 'Al Saud restoration after a six-year interregnum (1818-1824): Ibrahim Pasha''s Ottoman-Egyptian army had razed Diriyah (1818) and executed Imam Abdullah bin Saud in Istanbul; in 1824 Turki ibn Abdullah retook Riyadh from the Egyptian garrison by siege and made it the new capital.', 'The 1818-1824 gap (Egyptian occupation, failed risings of Mishari bin Saud 1819-20 and Turki 1821-23) is real and documented - the chain records a dynastic restoration, not state continuity.');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Saudi dynastic states: إمارة الدرعية → إمارة نجد → المملكة العربية السعودية'), 253, 2, 1932, 'UNIFICATION', true, 'After the Rashidi conquest of Najd (Mulayda 1891) and Al Saud exile in Kuwait, Abdulaziz Ibn Saud retook Riyadh in 1902 and unified the peninsula by conquest over three decades: Ha''il and the Rashidi emirate (1921), the Hejaz (1924-25), proclamation of the Kingdom of Saudi Arabia on 23 September 1932.', 'Typed UNIFICATION (not ''restoration'') per cross-check: the third state was conquest-built. The conquest of the Hejaz included the Ta''if massacre (September 1924, ~300-400 civilians killed by the Ikhwan); the Ikhwan themselves were crushed by Ibn Saud at Sabilla (1929) when they pressed to continue raiding.');

INSERT INTO dynasty_chains (name, name_lang, chain_type, region, description, confidence_score, status, ethical_notes, sources)
VALUES ('Nepalese state: गोर्खा राज्य → सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल', 'en', 'SUCCESSION', 'South Asia / Himalaya', 'The Nepalese state from the Gorkha conquest-founded Shah kingdom (1768) to the Federal Democratic Republic declared on 28 May 2008 by the 1st Constituent Assembly, which abolished the 240-year monarchy.', 0.9, 'confirmed', 'ETHICS-002: the 2008 transition is typed REVOLUTION with is_violent=true - the abolition vote itself (560-4) was peaceful and King Gyanendra left the palace without resistance, but the republic was the direct outcome of the 1996-2006 civil war (~13,000 deaths documented by OHCHR, Nepali government figures to ~17,000; the majority of documented killings attributed to state security forces per INSEC) and of the April 2006 Jana Andolan II uprising (~18-25 protesters killed by royal security forces). Marking it non-violent would erase the war that produced it.', '[{"citation": "John Whelpton, A History of Nepal, Cambridge University Press, 2005", "url": null, "source_type": "academic"}, {"citation": "OHCHR, Nepal Conflict Report, 2012", "url": "https://www.ohchr.org/en/documents/reports/nepal-conflict-report", "source_type": "primary"}, {"citation": "Sebastian von Einsiedel, David M. Malone, Suman Pradhan (eds.), Nepal in Transition: From People''s War to Fragile Peace, Cambridge University Press, 2012", "url": null, "source_type": "academic"}]');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Nepalese state: गोर्खा राज्य → सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 399, 0, NULL, NULL, false, 'The Shah kingdom founded by Prithvi Narayan Shah''s conquest of the Kathmandu valley (1768-69), expanded through the Anglo-Nepalese war (1814-16, Sugauli treaty), ruled 1846-1951 by the hereditary Rana premiership, and ended by the 2006-08 peace process.', NULL);
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Nepalese state: गोर्खा राज्य → सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), (SELECT id FROM geo_entities WHERE name_original = 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल'), 1, 2008, 'REVOLUTION', true, 'On 28 May 2008 the newly elected Constituent Assembly abolished the monarchy (560-4) and declared a federal democratic republic; Gyanendra Shah left Narayanhiti palace peacefully on 11 June 2008.', 'is_violent=true refers to the revolutionary process (1996-2006 people''s war, ~13,000-17,000 dead; 2006 Jana Andolan II), not to the final vote, which was peaceful - see chain-level note.');

INSERT INTO dynasty_chains (name, name_lang, chain_type, region, description, confidence_score, status, ethical_notes, sources)
VALUES ('Taqali and the Mahdiyya: مملكة تقلي → الدولة المهدية', 'en', 'SUCCESSION', 'Northeast Africa / Sudan (Nuba mountains)', 'The Nuba-mountains kingdom of Taqali, independent for over three centuries, conquered by the Mahdist state: invaded from 1883, its ruler Makk Adam captured in July 1884 (he died in Mahdist captivity); the Mahdiyya itself was destroyed by the British-led Anglo-Egyptian reconquest in 1898-99.', 0.7, 'confirmed', 'ETHICS-002: the transition is a violent conquest and is recorded as such. Taqali''s resistance in the hills was never fully broken - Mahdist control of the Nuba mountains remained contested, and a Taqali lineage re-emerged as a client under the Anglo-Egyptian Condominium; the chain records the 1884 destruction of the independent kingdom, not a total erasure of the Taqali polity''s people. The successor''s own end (Omdurman 1898, ~10,000-12,000 Sudanese dead to Maxim guns and artillery against 48 British-led casualties; Condominium agreement 1899) is colonial violence, perpetrator named on the Mahdist entity record.', '[{"citation": "Janet J. Ewald, Soldiers, Traders, and Slaves: State Formation and Economic Transformation in the Greater Nile Valley, 1700-1885, University of Wisconsin Press, 1990", "url": null, "source_type": "academic"}, {"citation": "P. M. Holt, The Mahdist State in the Sudan, 1881-1898, 2nd ed., Clarendon Press, 1970", "url": null, "source_type": "academic"}]');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Taqali and the Mahdiyya: مملكة تقلي → الدولة المهدية'), 411, 0, NULL, NULL, false, 'The kingdom of Taqali in the Nuba mountains (from ~1570), a hill state that preserved independence from Sennar and from Turco-Egyptian Sudan through tribute diplomacy and mountain warfare.', NULL);
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Taqali and the Mahdiyya: مملكة تقلي → الدولة المهدية'), 736, 1, 1884, 'CONQUEST', true, 'Mahdist forces invaded Taqali from 1883; Makk Adam was captured in July 1884 and died in Mahdist captivity. Resistance in the hills continued through the Mahdist period.', 'Violent conquest, perpetrator named (Mahdist state). Taqali''s entity record ends 1884 with this conquest.');

-- ── validazione finale ──
DO $$
DECLARE n_ent int; bad int;
BEGIN
  SELECT count(*) INTO n_ent FROM geo_entities WHERE name_original IN (
    'កម្ពុជា (Longvek-Oudong)', 'សាធារណរដ្ឋខ្មែរ', 'Кнежевина Србија', 'Краљевина Срба, Хрвата и Словенаца', 'إمارة الدرعية', 'إمارة نجد', 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल', 'Mthwakazi');
  IF n_ent <> 8 THEN RAISE EXCEPTION 'attese 8 entità nuove, trovate %', n_ent; END IF;
  -- contiguità sequence_order per le catene toccate
  SELECT count(*) INTO bad FROM (
    SELECT chain_id FROM chain_links WHERE chain_id IN (34, 123, 124, 125, 126, 130)
    GROUP BY chain_id
    HAVING count(*) <> max(sequence_order) + 1 OR min(sequence_order) <> 0
  ) t;
  IF bad <> 0 THEN RAISE EXCEPTION 'sequence_order non contigui su % catene', bad; END IF;
  -- ogni link non-primo ha transition_type
  SELECT count(*) INTO bad FROM chain_links WHERE chain_id IN (34, 123, 124, 125, 126, 130)
    AND sequence_order > 0 AND transition_type IS NULL;
  IF bad <> 0 THEN RAISE EXCEPTION '% link non-primi senza transition_type', bad; END IF;
  -- antimeridian guard sui boundary nuovi (CLAUDE.md geometric check)
  SELECT count(*) INTO bad FROM geo_entities WHERE name_original IN (
    'កម្ពុជា (Longvek-Oudong)', 'សាធារណរដ្ឋខ្មែរ', 'Кнежевина Србија', 'Краљевина Срба, Хрвата и Словенаца', 'إمارة الدرعية', 'إمارة نجد', 'सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल', 'Mthwakazi')
    AND (ST_XMax(boundary_geom) - ST_XMin(boundary_geom)) >= 180;
  IF bad <> 0 THEN RAISE EXCEPTION '% boundary attraversano l''antimeridiano', bad; END IF;
  RAISE NOTICE 'M1 v6.99.120 OK: 11 entità + catene 34/123/124/125/126/130 + 3 nuove';
END $$;

COMMIT;
