-- v6.99.130 (Task 2c / ETHICS-025) — Serbia moderna: FRY + S&M + Republic of Serbia + catena 34.
-- Backup PRIMA. ON_ERROR_STOP=1. Confini approximate_generated.
BEGIN;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM geo_entities WHERE name_original IN ('Савезна Република Југославија', 'Државна заједница Србија и Црна Гора', 'Република Србија')) THEN
    RAISE EXCEPTION 'entità Serbia moderna già presenti'; END IF;
END $$;

-- ── Савезна Република Југославија ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
  capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
  confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('Савезна Република Југославија', 'sr-Cyrl', 'federation', 1992, 2003,
  'Belgrade', 44.8125, 20.4612, '{"type": "Polygon", "coordinates": [[[22.8717, 44.8125], [23.1828, 46.0015], [21.4221, 46.0272], [20.4612, 47.1132], [19.6086, 45.8308], [18.0171, 45.8535], [18.1016, 44.8125], [18.6914, 44.1108], [19.3974, 43.5481], [20.4612, 42.8894], [21.6076, 43.4024], [22.5173, 43.828], [22.8717, 44.8125]]]}', 'approximate_generated',
  0.92, 'confirmed', 'Il regime di Slobodan Milošević a Belgrado orchestrò la pulizia etnica in Bosnia e, nel 1998-99, in Kosovo: forze militari e di polizia serbe/jugoslave espulsero con la forza circa 863.000 albanesi del Kosovo tra marzo e giugno 1999 e ne uccisero migliaia (l''ICTY incriminò Milošević per crimini di guerra e contro l''umanità). Vanno però registrate entrambe le storiografie senza arbitrarle: i bombardamenti NATO dell''operazione Allied Force (24 marzo–9 giugno 1999), condotti senza mandato del Consiglio di Sicurezza ONU, uccisero secondo Human Rights Watch circa 500 civili (la FRY dichiarò 1.200–5.700), e la questione della legittimità dell''intervento e dello status del Kosovo resta contesa. Sul versante opposto, l''UÇK (Esercito di Liberazione del Kosovo) commise a sua volta rappresaglie e sfollamenti di serbi e rom. Le cifre demografiche qui riportate sono attribuite alle fonti (HRW, studio Lancet, censimento FRY 1991) e non vanno presentate come definitive.', 'Q838261',
  ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon", "coordinates": [[[22.8717, 44.8125], [23.1828, 46.0015], [21.4221, 46.0272], [20.4612, 47.1132], [19.6086, 45.8308], [18.0171, 45.8535], [18.1016, 44.8125], [18.6914, 44.1108], [19.3974, 43.5481], [20.4612, 42.8894], [21.6076, 43.4024], [22.5173, 43.828], [22.8717, 44.8125]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'Savezna Republika Jugoslavija', 'sr-Latn', NULL, NULL, 'Serbian Latin-script romanization of the constitutional name', 'en.wikipedia.org/wiki/Serbia_and_Montenegro');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'Federal Republic of Yugoslavia', 'en', NULL, NULL, 'Standard English designation (FRY) used by the UN, ICTY and Western governments 1992–2003', 'ICTY, icty.org/en/about/what-former-yugoslavia');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'Savezna Republika Jugoslavija (Савезна Република Југославија)', 'hbs', NULL, NULL, 'Same name in the shared Serbo-Croatian/Bosnian standard used across the former Yugoslavia', 'Wikidata Q37024');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'Трећа Југославија (Treća Jugoslavija)', 'sr', NULL, NULL, 'Denominazione informale ''Terza Jugoslavia'' (dopo il Regno e la SFRJ); lang sr.', 'Britannica, britannica.com/place/Yugoslavia-former-federated-nation-1929-2003');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 1992, 'Serbia and Montenegro', 'FOUNDING', 'On 27 April 1992 the Assembly in Belgrade adopted the FRY constitution, constituting a two-republic federation (Serbia incl. the autonomous provinces of Kosovo and Vojvodina, plus Montenegro) as the self-declared continuation of SFR Yugoslavia. The UN Security Council (Res. 777/1992) rejected automatic continuity and required reapplication for membership.', 10394026, 0.92);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 1992, 'International / Bosnia-Herzegovina', 'REFORM', 'UN Security Council Resolution 757 (30 May 1992) imposed a near-total trade embargo, financial and air-traffic sanctions on the FRY for Belgrade''s role in arming and directing Bosnian Serb forces during the Bosnian War; sanctions crippled the economy through the 1990s.', NULL, 0.92);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 1999, 'Kosovo', 'OCCUPATION', 'During the Kosovo War, Yugoslav/Serbian forces under Milošević forcibly expelled roughly 863,000 Kosovo Albanians (Mar–Jun 1999); NATO''s Operation Allied Force bombed the FRY 24 Mar–9 Jun 1999, after which UNSC Res. 1244 placed Kosovo under UN administration (UNMIK/KFOR), removing it from effective Belgrade control.', 863000, 0.92);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 2003, 'Serbia and Montenegro', 'REFORM', 'On 4 February 2003 the Federal Assembly promulgated the Constitutional Charter, abolishing the name ''Federal Republic of Yugoslavia'' and reconstituting the polity as the looser State Union of Serbia and Montenegro, ending the Yugoslav state name after 74 years.', NULL, 0.92);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'International Criminal Tribunal for the former Yugoslavia (ICTY), "What is the former Yugoslavia?" — official background on the SFRY/FRY and the wars of the 1990s.', 'https://www.icty.org/en/about/what-former-yugoslavia', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'United Nations Security Council Resolution 757 (S/RES/757, 30 May 1992), imposing comprehensive sanctions on the Federal Republic of Yugoslavia (Serbia and Montenegro).', 'https://digitallibrary.un.org/record/142881', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'Human Rights Watch, "Under Orders: War Crimes in Kosovo" (2001) — documentation of forced expulsions and killings by Serbian/Yugoslav forces and of civilian deaths from NATO bombing.', 'https://www.hrw.org/reports/2001/kosovo/', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'Spiegel PB & Salama P, "War and mortality in Kosovo, 1998–99: an epidemiological testimony," The Lancet 355 (2000): 2204–2209 — CDC-linked mortality estimate (~12,000 war-related deaths).', 'https://www.thelancet.com/pdfs/journals/lancet/PIIS0140673600024041.pdf', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 'Encyclopaedia Britannica, "Yugoslavia (former federated nation, 1929–2003)" and "Serbia and Montenegro" — standard reference for the 27 April 1992 founding, 4 February 2003 renaming, and Belgrade capital.', 'https://www.britannica.com/place/Yugoslavia-former-federated-nation-1929-2003', 'secondary');

-- ── Државна заједница Србија и Црна Гора ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
  capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
  confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('Државна заједница Србија и Црна Гора', 'sr-Cyrl', 'federation', 2003, 2006,
  'Belgrade', 44.8125, 20.4612, '{"type": "Polygon", "coordinates": [[[22.5187, 44.8125], [23.0018, 45.7921], [21.837, 46.2527], [20.4612, 46.6559], [18.8049, 46.6558], [18.8399, 45.6351], [17.5618, 44.8125], [18.4593, 43.9037], [19.4331, 43.5373], [20.4612, 43.0713], [21.6589, 43.4056], [22.9163, 43.8102], [22.5187, 44.8125]]]}', 'approximate_generated',
  0.9, 'confirmed', 'Il quesito dell''unione tra Serbia e Montenegro ammette due letture storiografiche che il record non arbitra (ETHICS-003). Lettura pro-indipendenza: l''unione statale del 2003 fu un contenitore lasco mediato dall''Occidente (in particolare dall''inviato UE Javier Solana, da cui il soprannome ''Solania'') per rinviare la separazione, e il referendum del 21 maggio 2006 completò l''autodeterminazione montenegrina. Lettura pro-unionista/serba: la soglia del 55% fissata dall''UE fu imposta dall''esterno e l''esito (55,5%) fu talmente stretto da restare contestato. Entrambe vanno registrate con attribuzione. Va inoltre esplicitato che durante tutta l''esistenza dell''unione il Kosovo restò de iure parte della Serbia ma sotto amministrazione ONU (UNMIK) in base alla Risoluzione 1244 del Consiglio di Sicurezza (1999), conseguenza dei bombardamenti NATO e del conflitto del 1998-99; questo status irrisolto non è edulcorato ma non altera i confini nominali dell''entità.', 'Q37024',
  ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon", "coordinates": [[[22.5187, 44.8125], [23.0018, 45.7921], [21.837, 46.2527], [20.4612, 46.6559], [18.8049, 46.6558], [18.8399, 45.6351], [17.5618, 44.8125], [18.4593, 43.9037], [19.4331, 43.5373], [20.4612, 43.0713], [21.6589, 43.4056], [22.9163, 43.8102], [22.5187, 44.8125]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'Србија и Црна Гора', 'sr-Cyrl', NULL, NULL, 'Short/common name of the state union in Serbian Cyrillic, as used on the Serbian Wikipedia and in the Constitutional Charter', 'sr.wikipedia.org/wiki/Србија_и_Црна_Гора');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'Državna zajednica Srbija i Crna Gora', 'sr-Latn', NULL, NULL, 'Official name in Serbian Latin script (co-official); rendered by Wikidata as the official name statement', 'Wikidata Q37024 (official name)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'Serbia and Montenegro', 'en', NULL, NULL, 'Standard English name of the state union (2003-2006)', 'en.wikipedia.org/wiki/Serbia_and_Montenegro');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'Crna Gora', 'cnr', NULL, NULL, 'Montenegrin form of the co-constituent republic''s name; Montenegrin is now recognized as a distinct standard', 'en.wikipedia.org/wiki/Constitutional_Charter_of_Serbia_and_Montenegro');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 2002, 'Serbia and Montenegro', 'REFORM', 'Belgrade Agreement (Accord on Principles in Relations between Serbia and Montenegro), signed March 2002 by the Serbian, Montenegrin and FRY governments under EU mediation (Javier Solana), framing the restructuring of the FRY into a loose state union.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 2003, 'Federal Republic of Yugoslavia / Serbia and Montenegro', 'REFORM', 'Constitutional Charter came into force 4 February 2003, transforming the Federal Republic of Yugoslavia into the confederal State Union of Serbia and Montenegro and retiring the name ''Yugoslavia''.', 10825900, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 2006, 'Montenegro', 'SECESSION', 'Montenegrin independence referendum of 21 May 2006 (55.5% in favour, EU/Venice Commission threshold 55%); Montenegro''s parliament declared independence 3 June 2006, ending the union.', 620000, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 2006, 'Serbia and Montenegro', 'DISSOLUTION', 'Serbia''s parliament declared Serbia the legal successor to the State Union on 5 June 2006, dissolving Serbia and Montenegro into two independent states.', 10832545, 0.9);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'Constitutional Charter of the State Union of Serbia and Montenegro, adopted by the Federal Assembly, 4 February 2003.', 'https://www.worldstatesmen.org/SerbMont_Const_2003.pdf', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), '''Serbia and Montenegro'', Wikidata item Q37024 (labels, official name, inception, dissolved 4 June 2006, capitals Belgrade and Podgorica, replaces Federal Republic of Yugoslavia Q838261).', 'https://www.wikidata.org/wiki/Q37024', 'secondary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'Florian Bieber (ed.), Montenegro in Transition: Problems of Identity and Statehood, Nomos Verlag, 2003.', NULL, 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'European Commission for Democracy through Law (Venice Commission), Opinion on the Compatibility of the Existing Legislation in Montenegro concerning the Organisation of Referendums with Applicable International Standards, CDL-AD(2005)041, 2005 (55% threshold).', 'https://www.venice.coe.int/webforms/documents/?pdf=CDL-AD(2005)041-e', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 'U.S. Department of State, Background Note: Serbia and Montenegro / Serbia (Bureau of European and Eurasian Affairs), 2003-2008.', 'https://2009-2017.state.gov/outofdate/bgn/serbiaandmontenegro/28187.htm', 'secondary');

-- ── Република Србија ──
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end,
  capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source,
  confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('Република Србија', 'sr-Cyrl', 'republic', 2006, NULL,
  'Belgrade', 44.8125, 20.4612, '{"type": "Polygon", "coordinates": [[[23.1963, 44.8125], [22.4063, 45.5786], [21.4743, 46.1761], [20.4612, 46.4925], [19.7218, 45.9085], [19.2384, 45.2973], [18.7777, 44.8125], [18.5749, 44.0369], [19.3521, 43.5214], [20.4612, 43.0456], [21.7403, 43.3673], [22.16, 44.1051], [23.1963, 44.8125]]]}', 'approximate_generated',
  0.9, 'confirmed', 'Il conflitto del Kosovo del 1998-1999 va nominato per primo (ETHICS-002): le forze serbo-jugoslave dell''era di Slobodan Milošević condussero una pulizia etnica su larga scala (circa 850.000 albanesi kosovari espulsi e migliaia di uccisi), che innescò l''intervento aereo NATO (marzo-giugno 1999) e l''amministrazione ONU del Kosovo (UNMIK, Ris. CdS 1244). Su questo sfondo si colloca la disputa successiva sullo status. Il record documenta senza arbitrare la disputa sul Kosovo, il territorio più contestato dello Stato. Lettura serba: la Costituzione del 2006 sancisce nel preambolo il Kosovo e Metohija come parte integrante e inalienabile della Serbia; Belgrado considera la dichiarazione unilaterale d''indipendenza del Kosovo (17 febbraio 2008) illegittima e non la riconosce. Lettura kosovara/di parte della comunità internazionale: il Kosovo esercita controllo statale de facto e il parere consultivo della Corte Internazionale di Giustizia del 22 luglio 2010 stabilì (10 voti contro 4) che la dichiarazione non violava il diritto internazionale; il numero di Stati riconoscenti è a sua volta conteso (il Kosovo rivendica ~120 riconoscimenti, la Serbia ne conta ~84-85 dopo la propria campagna di de-riconoscimento avviata dal 2017-2020). Entrambe le letture sono registrate senza risoluzione. La secessione del Montenegro (2006) fu pacifica e frutto di referendum, non di violenza.', 'Q403',
  ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon", "coordinates": [[[23.1963, 44.8125], [22.4063, 45.5786], [21.4743, 46.1761], [20.4612, 46.4925], [19.7218, 45.9085], [19.2384, 45.2973], [18.7777, 44.8125], [18.5749, 44.0369], [19.3521, 43.5214], [20.4612, 43.0456], [21.7403, 43.3673], [22.16, 44.1051], [23.1963, 44.8125]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'Republika Srbija', 'sr-Latn', NULL, NULL, 'Official Serbian name in Latin script (Gaj''s Latin alphabet), co-official constitutional form', 'Constitution of the Republic of Serbia (2006), Article 10');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'Republic of Serbia', 'en', NULL, NULL, 'Standard English designation used by the UN and EU', 'UN Member States list / Wikidata Q403 alias');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'Serbia', 'en', NULL, NULL, 'Common short-form country name', 'Britannica, ''Serbia''');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'République de Serbie', 'fr', NULL, NULL, 'French official form used in diplomatic/UN contexts', 'Wikidata Q403 official name (French)');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 2006, 'Montenegro', 'SECESSION', 'Following the referendum of 21 May 2006 (55.5% in favour), Montenegro declared independence on 3 June 2006. On 5 June 2006 the National Assembly of Serbia declared the Republic of Serbia the legal successor of the State Union, formally dissolving Serbia and Montenegro. The separation was peaceful and referendum-based, brokered under EU mediation (Javier Solana''s threshold of 55%).', 620000, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 2006, 'Serbia', 'FOUNDING', 'Re-emergence of Serbia as a fully sovereign independent state for the first time since 1918. A new constitution — the first as an independent state since the Kingdom of Serbia''s 1903 constitution — was adopted by referendum on 28-29 October 2006 and promulgated on 8 November 2006.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 2008, 'Kosovo', 'SECESSION', 'Kosovo''s Assembly issued a unilateral declaration of independence on 17 February 2008, which Serbia rejects as illegitimate; the Serbian constitution continues to claim Kosovo and Metohija as an inalienable part of Serbia. The ICJ advisory opinion of 22 July 2010 found the declaration did not violate international law. De facto Serbian administrative control was lost after the 1998-1999 war and the NATO bombing of the Federal Republic of Yugoslavia (Milošević era); status remains disputed.', 1800000, 0.9);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'Constitution of the Republic of Serbia (Ustav Republike Srbije), adopted 8 November 2006, Official Gazette RS No. 98/2006 — see Preamble and Article 10 on Kosovo and Metohija and official languages/script.', 'https://www.wipo.int/wipolex/en/legislation/details/7378', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'International Court of Justice, ''Accordance with International Law of the Unilateral Declaration of Independence in Respect of Kosovo'', Advisory Opinion of 22 July 2010, ICJ Reports 2010, p. 403.', 'https://www.icj-cij.org/case/141', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'Sabrina P. Ramet, ''The Three Yugoslavias: State-Building and Legitimation, 1918-2005'', Indiana University Press, 2006.', NULL, 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 'Encyclopaedia Britannica, ''Serbia and Montenegro'' (historical nation, Europe, 2003-2006) and ''Serbia''.', 'https://www.britannica.com/place/Serbia-and-Montenegro', 'secondary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES
  ((SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), '''2006 Montenegrin independence referendum'' and ''International recognition of Kosovo'', Wikipedia (referencing OSCE/ODIHR and government sources on referendum figures and recognition counts).', 'https://en.wikipedia.org/wiki/2006_Montenegrin_independence_referendum', 'secondary');

-- ── catena 34: +3 link (seq 7..9) ──
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (34, (SELECT id FROM geo_entities WHERE name_original = 'Савезна Република Југославија'), 7, 1992, 'DISSOLUTION', true, 'As the SFR Yugoslavia broke up in the 1991-1995 wars (Slovenia, Croatia, Bosnia, Macedonia seceding), Serbia and Montenegro proclaimed the Federal Republic of Yugoslavia on 27 April 1992 as the rump/claimed-continuator state.', 'is_violent=true: the FRY was born from the violent dissolution of the SFRY (Yugoslav wars, including the Srebrenica genocide of 1995 by Bosnian Serb forces, and the 1998-99 Kosovo war and NATO intervention involving FRY forces). Milošević-era Serbia was a principal party; perpetrator roles are named on the relevant entities.');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (34, (SELECT id FROM geo_entities WHERE name_original = 'Државна заједница Србија и Црна Гора'), 8, 2003, 'REFORM', false, 'The Constitutional Charter of 4 February 2003 restructured the FRY into the loose State Union of Serbia and Montenegro, retiring the name ''Yugoslavia'' after 74 years (EU-mediated, the ''Solania'' arrangement).', 'A constitutional restructuring/renaming, not a violent transition. Kosovo remained de iure part of Serbia but under UN administration (UNMIK, UNSC Res 1244).');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES (34, (SELECT id FROM geo_entities WHERE name_original = 'Република Србија'), 9, 2006, 'SECESSION', false, 'Montenegro''s independence referendum of 21 May 2006 (55.5% vs the EU-set 55% threshold) led to Montenegro''s declaration of independence on 3 June 2006; Serbia''s National Assembly declared the Republic of Serbia the successor state on 5 June 2006.', 'Peaceful secession by referendum. Both historiographies on the 55% threshold and the union are recorded on the Serbia-and-Montenegro entity; the unresolved Kosovo dispute (2008 UDI) is recorded on the Republic of Serbia entity, not arbitrated.');
UPDATE dynasty_chains SET name='Serbian state trunk: Raska → Srpsko Carstvo → Српска деспотовина → Ottoman → Кнежевина Србија → Југославија (СХС → СФРЈ → СРЈ → СЦГ) → Република Србија' WHERE id=34;

DO $$ DECLARE n int; bad int;
BEGIN
  SELECT count(*) INTO n FROM geo_entities WHERE name_original IN ('Савезна Република Југославија', 'Државна заједница Србија и Црна Гора', 'Република Србија');
  IF n <> 3 THEN RAISE EXCEPTION 'attese 3 entità, trovate %', n; END IF;
  SELECT count(*) INTO bad FROM (SELECT chain_id FROM chain_links WHERE chain_id=34 GROUP BY chain_id HAVING count(*)<>max(sequence_order)+1 OR min(sequence_order)<>0) t;
  IF bad<>0 THEN RAISE EXCEPTION 'catena 34 sequence non contigua'; END IF;
  SELECT count(*) INTO bad FROM geo_entities WHERE name_original IN ('Савезна Република Југославија', 'Државна заједница Србија и Црна Гора', 'Република Србија') AND (ST_XMax(boundary_geom)-ST_XMin(boundary_geom))>=180;
  IF bad<>0 THEN RAISE EXCEPTION '% confini antimeridiano', bad; END IF;
  -- ETHICS-003: nessun disputed sopra 0.70 tra i nuovi
  SELECT count(*) INTO bad FROM geo_entities WHERE name_original IN ('Савезна Република Југославија', 'Државна заједница Србија и Црна Гора', 'Република Србија') AND status='disputed' AND confidence_score>0.70;
  IF bad<>0 THEN RAISE EXCEPTION '% disputed sopra cap 0.70', bad; END IF;
  RAISE NOTICE 'Task 2c OK: FRY + S&M + Republic of Serbia + catena 34 (10 link)';
END $$;
COMMIT;
