-- v6.99.121 (ETHICS-021) — split Sri Lanka. Backup pg_dump PRIMA.
-- Dual-write: JSON = batch_02/10/18 + batch_38. psql -v ON_ERROR_STOP=1.
BEGIN;

-- guard: le nuove entità non esistono già
DO $$ BEGIN IF EXISTS (SELECT 1 FROM geo_entities WHERE name_original IN ('ගම්පොල රාජධානිය', 'කෝට්ටේ රාජධානිය')) THEN RAISE EXCEPTION 'entità SL già presenti'; END IF; END $$;

-- ── #142 re-scope → Anuradhapura ── (WHERE su PK: i nomi nativi hanno
-- caratteri fragili — zero-width space, ecc.; la PK è la chiave stabile)
UPDATE geo_entities SET name_original = 'අනුරාධපුර රාජධානිය', year_start = -437, year_end = 1017, confidence_score = 0.7, status = 'confirmed' WHERE id = 142 AND name_original <> 'අනුරාධපුර රාජධානිය';
DELETE FROM name_variants WHERE entity_id = 142 AND name IN ('Sinhalese Kingdom', 'Kingdom of Kandy', 'Regno Singalese');
UPDATE name_variants SET period_start = -437, context = 'standard English name of the polity (ETHICS-021)' WHERE entity_id = 142 AND name = 'Anuradhapura Kingdom';
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES
  (142, 'Rajarata', 'si', -437, 1017, 'the dry-zone king''s country core of the Anuradhapura state', 'Gunawardana, Robe and Plough (1979)'),
  (142, 'Regno di Anuradhapura', 'it', -437, 1017, 'denominazione italiana', NULL);
DELETE FROM territory_changes WHERE entity_id = 142 AND year = 1815;
UPDATE territory_changes SET year = -437, region = 'Rajarata (Sri Lanka settentrionale)', change_type = 'INDEPENDENCE', description = 'Convenzione mainstream: Pandukabhaya stabilisce la capitale ad Anuradhapura (~437 a.C.; cronologia corta 377 a.C., dato conteso). L''arrivo di Vijaya (~543 a.C., Mahavamsa) e'' TRADIZIONE fondativa, non confermata archeologicamente.', confidence_score = 0.5 WHERE entity_id = 142 AND year = -543;

-- ── #386 Gajabahu: deprecate + re-home ──
UPDATE geo_entities SET status = 'deprecated', ethical_notes = COALESCE(ethical_notes,'') || ' DEPRECATA (ETHICS-021, v6.99.121): ''ගජබාහු'' era il nome di un RE (Gajabahu I, r. ~113-136), non di uno stato; il suo periodo cade dentro il regno di Anuradhapura (#142). I territory_changes e i siti sono stati ri-homati.' WHERE id = 386 AND status <> 'deprecated';
UPDATE territory_changes SET entity_id = 142 WHERE entity_id = 386;
UPDATE archaeological_sites SET entity_id = 142 WHERE id = 784 AND entity_id = 386;
UPDATE archaeological_sites SET entity_id = 142 WHERE id = 783 AND entity_id = 386;
UPDATE archaeological_sites SET entity_id = 387 WHERE id = 351 AND entity_id = 386;
UPDATE archaeological_sites SET entity_id = 388 WHERE id = 786 AND entity_id = 386;
UPDATE archaeological_sites SET entity_id = 388 WHERE id = 353 AND entity_id = 386;
UPDATE archaeological_sites SET entity_id = NULL WHERE id = 1188 AND entity_id = 386;
UPDATE archaeological_sites SET entity_id = NULL WHERE id = 1189 AND entity_id = 386;
UPDATE archaeological_sites SET entity_id = NULL WHERE id = 352 AND entity_id = 386;

-- ── #600 re-scope → Dambadeniya ──
UPDATE geo_entities SET name_original = 'දඹදෙණිය රාජධානිය', year_end = 1341, wikidata_qid = 'Q3136869' WHERE id = 600 AND name_original <> 'දඹදෙණිය රාජධානිය';
DELETE FROM name_variants WHERE entity_id = 600 AND name = 'Kingdom of Kotte';
DELETE FROM territory_changes WHERE entity_id = 600 AND year IN (1412, 1597);
UPDATE territory_changes SET change_type = 'LIBERATION' WHERE entity_id = 600 AND year = 1232;

-- ── nuove entità Gampola + Kotte ──
-- gampola
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end, capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source, confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('ගම්පොල රාජධානිය', 'si', 'kingdom', 1341, 1412, 'Gampola (Gangasiripura)', 7.16472, 80.57667, '{"type": "Polygon","coordinates": [[[79.85,7.05],[79.8,7.45],[80.2,7.6],[80.65,7.55],[81,7.2],[81.05,6.8],[80.7,6.45],[80.15,6.25],[79.9,6.55],[79.85,7.05]]]}', 'historical_approximation', 0.62, 'confirmed', '1) Ming military intervention, perpetrator named: in 1410-1411 the Ming treasure-fleet forces of the Yongle Emperor under Admiral Zheng He invaded the kingdom''s southwestern core, seized the capital area, and captured king Vira Alakesvara together with his family and retainers, deporting them to Nanjing. This was an armed foreign intervention and forced deportation of a sovereign, not a ''diplomatic escort''. Chinese sources (Ming Shilu, Galle inscription context) frame Alakesvara as the aggressor who ''insulted'' the fleet and preyed on shipping; Sinhala tradition (Rajavaliya) frames the Chinese as acting by stratagem and deceit. The dispute is recorded here, not resolved. Some Chinese accounts also claim the Buddha''s Tooth Relic was carried to China; Sinhala tradition denies this — disputed. 2) Jaffna suzerainty and its violent overthrow: the Arya Chakravarti kings of Jaffna imposed tribute collection over Gampola''s western ports (Colombo, Negombo, Chilaw, Panadura) and highland districts (Matale, Dumbara) from the 1350s; the Alagakkonara magnates of Raigama expelled and — per Sinhala chronicle tradition (Nikaya Sangrahaya) — executed Jaffna tax collectors, then destroyed the Jaffna two-pronged invasion (land army defeated at Matale, naval force at Dematagoda and Panadura). Both the Jaffna extraction and the Sinhalese reprisal killings are stated plainly. 3) The Zheng He voyages are celebrated in modern Chinese historiography as peaceful diplomacy; the 1411 Ceylon episode is the clearest counter-example and is presented as a war (Ming-Kotte War) with a king deposed by foreign force. 4) Parakramabahu VI''s 1412 accession is presented in Ming records as an installation sanctioned by the Yongle court, and in Sinhala tradition as an indigenous restoration — both versions documented.', 'Q6412581', ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[79.85,7.05],[79.8,7.45],[80.2,7.6],[80.65,7.55],[81,7.2],[81.05,6.8],[80.7,6.45],[80.15,6.25],[79.9,6.55],[79.85,7.05]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'ගම්පොල රාජධානිය', 'si', NULL, NULL, 'Modern Sinhala rendering (''Gampola rajadhaniya'' = Gampola Kingdom); attested as the Sinhala Wikipedia article title and Wikidata Sinhala label (fetched 2026-07-04). Modern label for the medieval polity, not a 14th-century attested unit.', 'si.wikipedia.org/wiki/ගම්පොල_රාජධානිය; wikidata.org Q6412581');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'ගම්පොළ', 'si', NULL, NULL, 'Modern standard Sinhala spelling of the town/kingdom name with retroflex ළ; given as the Sinhala form in the English Wikipedia infoboxes for both the kingdom and the town. Spelling varies between ල and ළ across modern sources.', 'en.wikipedia.org/wiki/Kingdom_of_Gampola; en.wikipedia.org/wiki/Gampola');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'Gaṅgāsiripura', 'si', 1341, 1412, 'Contemporaneous 14th-century name attested in Gampola-period inscriptions and chronicles (''resplendent city on the river'', from its position on the Mahaweli Ganga); the closest thing to the polity''s own attested capital name.', 'Gampola-period epigraphy (Lankatilaka inscriptions); Culavamsa; en/si Wikipedia');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'ගංගා ශ්‍රී පුර', 'si', 1341, 1412, 'Sinhala-script form of Gangasiripura as given on Sinhala Wikipedia (also ගඟ සිරි පුර).', 'si.wikipedia.org/wiki/ගම්පොල_රාජධානිය');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'Kingdom of Gampola', 'en', NULL, NULL, 'Standard English historiographic name.', 'en.wikipedia.org; K.M. de Silva, A History of Sri Lanka (1981)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), '錫蘭山國 (Xīlánshān guó)', 'zh', 1405, 1411, 'Ming Chinese name (''Ceylon Mountain country'') for the Sinhala kingdom in Ming Shilu records and the Zheng He voyage accounts (1405-1411). Refers to the island polity the Ming encountered — i.e. the Gampola/Raigama state of Vira Alakesvara — not the town of Gampola specifically.', 'Ming Shilu; Dreyer, Zheng He (2007)');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 1341, 'Central highlands — Gampola/Gangasiripura on the Mahaweli', 'INHERITANCE', 'Bhuvanaikabahu IV of the Dambadeniya-Kurunegala dynastic line moved the royal capital from Kurunegala to Gampola (Gangasiripura), supported by minister Senalankadhikara — a peaceful dynastic capital shift within the ''drifting capitals'' pattern, not a conquest. Sources vary between 1341 and 1344/45 for his consecration.', NULL, 0.75);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 1345, 'Dedigama and the southwestern lowlands (later Raigama)', 'INHERITANCE', 'The kingdom functioned as a divided/co-ruled polity: Parakramabahu V ruled from Dedigama (c. 1344-1359) while Bhuvanaikabahu IV sat at Gampola; from the 1370s effective power over the southwest lay with the Alagakkonara family based at Raigama, with the Gampola king increasingly nominal.', NULL, 0.6);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 1360, 'Western ports (Colombo, Negombo, Chilaw, Panadura) and highland districts (Matale, Dumbara)', 'CESSION_FORCED', 'The Arya Chakravarti rulers of the Jaffna kingdom extended tribute and tax collection over Gampola''s western coastal ports and even highland districts; Vikramabahu III (r. 1357-1374) paid tribute. A forced loss of fiscal sovereignty to Jaffna, imposed from a position of military-naval strength — dating of its onset (1350s-1360s) is approximate.', NULL, 0.55);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 1391, 'Southwestern lowlands and Matale — end of Jaffna suzerainty', 'CONQUEST_MILITARY', 'Nissanka Alagakkonara of Raigama, chief minister under Vikramabahu III, fortified Kotte (c. 1370s), expelled and per the Nikaya Sangrahaya tradition executed the Jaffna tax collectors, and the Gampola-Raigama forces destroyed the Arya Chakravarti''s two-pronged invasion: the land army defeated at Matale, the seaborne force routed at Dematagoda and its ships destroyed at Panadura (dated c. 1391 under Bhuvanaikabahu V; some accounts place the first expulsions from 1369). Perpetrators on both sides named: Jaffna''s armed tax extraction was answered with Sinhalese reprisal killings and open war.', NULL, 0.55);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 1411, 'Southwestern core (Kotte/Raigama and the capital)', 'CONQUEST_MILITARY', 'Ming intervention (Ming-Kotte War, 1410-11): after Vira Alakesvara''s hostile reception of the treasure fleet (first clash 1405-06; the fleet returned via Galle in 1409, where Zheng He''s trilingual inscription — inscribed in Nanjing 15 Feb 1409, in Chinese, Tamil and Persian — was erected), Admiral Zheng He''s forces (~2,000 troops) marched inland, defeated the royal army, seized the capital, and captured Vira Alakesvara, deporting him with his family to Nanjing. Perpetrator: Ming China under the Yongle Emperor. Chinese accounts blame Alakesvara''s aggression; Sinhala tradition alleges Chinese deceit — dispute recorded, not resolved.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 1412, 'Whole kingdom — seat moves to Raigama, then Kotte', 'INHERITANCE', 'With Vira Alakesvara deported, Parakramabahu VI was consecrated at Raigama in 1412 (Ming sources present his installation as sanctioned by the Yongle court; Sinhala tradition presents an indigenous accession) and subsequently moved the royal seat to Sri Jayawardenapura Kotte, closing the Gampola period and opening the Kingdom of Kotte. Vira Alakesvara was later released and returned from China without regaining power.', NULL, 0.7);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'Cūḷavaṃsa: Being the More Recent Part of the Mahāvaṃsa, trans. Wilhelm Geiger (with C. Mabel Rickmers), Pali Text Society / Colombo, 1929-1930 — chapters XC-XCI cover the Gampola kings.', NULL, 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'Nikāya Saṅgrahaya of Devarakkhita Jayabāhu Dharmakīrti (c. 1386) — contemporary Sinhala chronicle of the Gampola period covering the kings and the rise of the Alagakkonara family.', NULL, 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'G.P.V. Somaratne, The Political History of the Kingdom of Kotte, 1400-1521 (Colombo, 1975; based on his SOAS PhD thesis, ''Political History of the Kingdom of Kotte, c. A.D. 1400-1521'', University of London, 1969) — covers the Gampola-Kotte transition and the Chinese invasion.', 'https://eprints.soas.ac.uk/29736/1/10752708.pdf', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'K.M. de Silva, A History of Sri Lanka (London: C. Hurst & Co.; Berkeley: University of California Press, 1981) — the ''drift to the south-west'' chapters on Gampola, Raigama and the Alagakkonara.', NULL, 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'Edward L. Dreyer, Zheng He: China and the Oceans in the Early Ming Dynasty, 1405-1433 (New York: Pearson Longman, 2007) — the 1411 Ceylon campaign and capture of Vira Alakesvara from the Chinese documentary record (Ming Shilu, Ma Huan).', NULL, 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 'S. Paranavitana, ''The Tamil Inscription on the Galle Trilingual Slab'', Epigraphia Zeylanica, Vol. III (1928-1933); first noticed by E.W. Perera, Spolia Zeylanica (1912-13) — the Galle Trilingual Inscription (inscribed Nanjing, 15 February 1409; discovered Galle 1911; now National Museum, Colombo).', NULL, 'archaeological');

-- kotte
INSERT INTO geo_entities (name_original, name_original_lang, entity_type, year_start, year_end, capital_name, capital_lat, capital_lon, boundary_geojson, boundary_source, confidence_score, status, ethical_notes, wikidata_qid, boundary_geom)
VALUES ('කෝට්ටේ රාජධානිය', 'si', 'kingdom', 1412, 1597, 'Sri Jayawardenepura Kotte', 6.9108, 79.8878, '{"type": "Polygon","coordinates": [[[79.78,7.7],[79.83,6.95],[79.95,6.45],[80.2,6],[80.6,5.92],[80.85,6.1],[80.75,6.55],[80.55,6.95],[80.35,7.55],[79.78,7.7]]]}', 'historical_approximation', 0.85, 'confirmed', 'Violence and colonial coercion are explicit in this record. (1) Kotte''s unification of the island was military conquest: in 1450 prince Sapumal (Tamil: Cempaka Perumal), commander for Parakramabahu VI of Kotte, conquered the Tamil kingdom of Jaffna in the second of two invasions; King Kanakasooriya Cinkaiariyan was driven into exile in South India. Tamil historiography (Yalpana Vaipava Malai tradition) records this from the conquered side; Jaffna regained independence in 1467. (2) The 1521 Vijayaba Kollaya (''spoiling of Vijayabahu''): the king''s three sons had their father Vijayabahu VII murdered by a hired assassin and partitioned the kingdom (Kotte/Sitawaka/Raigama). (3) Portugal is the colonial power that destroyed and absorbed this kingdom. Portuguese arrival 1505/06 (Lourenco de Almeida); King Bhuvanekabahu VII was shot dead by a Portuguese soldier at Kelaniya in 1551 (accident or assassination — disputed, not resolved here); his grandson Dharmapala was installed as a client king under Portuguese military tutelage, baptized Dom Joao in 1557, and lived under Portuguese protection in the Colombo fort after Kotte city was abandoned in 1565. His 1580 deed of donation bequeathing the kingdom to the Portuguese crown was a coerced client-state act by a ruler wholly dependent on Portuguese arms — NOT a free gift; it took effect at his death on 27 May 1597, creating Portuguese Ceylon. (4) The sister kingdom Sitawaka (1521-1594) mounted the fiercest armed resistance to Portugal; Portuguese forces sacked Sitawaka city in 1594 after Rajasinha I''s death (1593). Portuguese campaigns in this period included destruction of Buddhist and Hindu temples, documented even in the pro-Portuguese Jesuit chronicle of Queiros. Disputes recorded, not resolved: 1505 vs 1506 arrival date; regnal chronology of Kotte kings c. 1467-1509; Kandy''s secession dated 1469 by most sources (some argue early 1470s); nature of Bhuvanekabahu VII''s death.', 'Q1589163', ST_Multi(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates": [[[79.78,7.7],[79.83,6.95],[79.95,6.45],[80.2,6],[80.6,5.92],[80.85,6.1],[80.75,6.55],[80.55,6.95],[80.35,7.55],[79.78,7.7]]]}')));
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'කෝට්ටේ රාජධානිය', 'si', NULL, NULL, 'Modern Sinhala historiographic name (Kotte Rajadhaniya, ''Kingdom of Kotte''); attested as native_name in Sinhala/English Wikipedia. The Sinhala script form is a modern rendering, not a 15th-century attestation.', 'https://en.wikipedia.org/wiki/Kingdom_of_Kotte');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'Sri Jayawardhanapura Kotte (ජයවර්ධන කෝට්ටේ)', 'si', 1412, 1597, 'Contemporary name of the fortified capital and by extension the polity, attested in Kotte-era sources (Rajavaliya; 15th-c. Sandesha poetry such as Salalihini Sandeshaya); ''Jayawardhana'' = ''victory-increasing'', ''Kotte'' from Malayalam/Tamil kottai = fort.', 'Rajavaliya, ed. B. Gunasekara (1900)');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'Kingdom of Kotte', 'en', NULL, NULL, 'Standard English historiographic name.', 'https://www.wikidata.org/wiki/Q1589163');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'Cota / Reino de Cota', 'pt', 1505, 1658, 'Portuguese colonial-era spelling, used in Portuguese sources including Queiros, Conquista Temporal e Espiritual de Ceylao.', 'F. de Queiros, trans. S.G. Perera (1930)');
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1412, 'Southwestern Sri Lanka (Kotte core)', 'INHERITANCE', 'Parakramabahu VI acceded in 1412 (initially at Raigama; capital moved to the fortress of Kotte c. 1415), founding the kingdom as successor to Gampola. His rise followed the 1411 Ming intervention in which admiral Zheng He''s forces captured the previous strongman Vira Alakeshvara and took him to Nanjing — a non-Western (Chinese) dimension of the founding recorded in both the Rajavaliya and the Ming shi.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1450, 'Jaffna kingdom (northern Sri Lanka)', 'CONQUEST_MILITARY', 'Prince Sapumal (Tamil: Cempaka Perumal), adopted son and commander of Parakramabahu VI, conquered the Tamil Jaffna kingdom in the second of two invasions (the first failed). King Kanakasooriya Cinkaiariyan fled to South India. With Jaffna, the Vanni chiefs and the hill country subdued, Kotte ruled the whole island — the last time a single Sri Lankan polity did so until 1815. Sapumal governed Jaffna 1450-1467.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1467, 'Jaffna kingdom', 'LIBERATION', 'Kanakasooriya Cinkaiariyan returned from Madurai with mercenary forces and retook Jaffna after Sapumal left north to contest the Kotte succession (he took the throne as Bhuvanekabahu VI). Jaffna''s independence from Kotte was restored.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1469, 'Kandy / central highlands', 'REVOLUTION', 'Senasammata Vikramabahu rebelled against Kotte and made the hill country (Kandy) independent — origin of the Kandyan kingdom. Most sources date this 1469; some historians argue the early 1470s.', NULL, 0.7);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1505, 'Colombo coast', 'COLONIZATION', 'First Portuguese arrival: Lourenco de Almeida''s squadron, blown to the island''s southwest coast (late 1505 or 1506 — date disputed), reached the Kotte court. Portugal extracted trade concessions, built a fort at Colombo in 1518, and began the armed intrusion that would consume the kingdom.', NULL, 0.7);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1521, 'Kotte partitioned into Kotte, Sitawaka and Raigama', 'REVOLUTION', 'Vijayaba Kollaya (''spoiling of Vijayabahu''): the king''s three sons — Bhuvanekabahu, Pararajasingha and Mayadunne — mutinied on learning their father intended to make his stepson Devaraja heir, and had King Vijayabahu VII murdered in his chamber by a hired assassin. They split the realm: Bhuvanekabahu VII kept Kotte and the seaboard, Mayadunne took Sitawaka (which became the fiercest anti-Portuguese resistance state, 1521-1594), Pararajasingha took Raigama.', NULL, 0.9);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1551, 'Kotte (client kingship begins)', 'COLONIZATION', 'King Bhuvanekabahu VII was shot dead by a Portuguese soldier at Kelaniya — accident or assassination, disputed to this day. Portugal installed his young grandson Dharmapala under Portuguese military tutelage; he was baptized Dom Joao in 1557, becoming a Catholic client king dependent on Portuguese arms against Sitawaka.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1565, 'Capital: Kotte city abandoned for Colombo', 'CESSION_FORCED', 'Unable to withstand repeated Sitawaka assaults under Mayadunne and Rajasinha I, the Portuguese abandoned the city of Kotte; Dharmapala''s court was moved inside Portuguese-held Colombo, completing his reduction to a protected puppet.', NULL, 0.8);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1580, 'Entire kingdom (deed of donation)', 'CESSION_FORCED', 'Dharmapala, a client king living under Portuguese protection in Colombo, executed a deed of donation bequeathing the whole kingdom of Kotte to the Portuguese crown on his death. A coerced client-state act under military tutelage, not a free gift: the perpetrator-beneficiary was colonial Portugal (from 1580 under the Habsburg Philip II as king of Portugal).', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1594, 'Sitawaka', 'CONQUEST_MILITARY', 'After Rajasinha I of Sitawaka died in 1593, Portuguese forces sacked the city of Sitawaka in 1594 and absorbed its lowland territories, ending the strongest indigenous resistance to Portuguese expansion; their same-year Danture campaign into Kandy was crushed by Vimaladharmasuriya I.', NULL, 0.85);
INSERT INTO territory_changes (entity_id, year, region, change_type, description, population_affected, confidence_score) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 1597, 'Entire Kotte kingdom to Portuguese Ceylon', 'CESSION_FORCED', 'Dharmapala died 27 May 1597 in the Colombo fort. Under the 1580 donation, colonial Portugal annexed the kingdom outright as Portuguese Ceylon — the formal end of Kotte. The absorption was the culmination of a half-century of coercion, client-kingship and war, not a voluntary transfer.', NULL, 0.9);
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'Somaratne, G.P.V. (1975). The Political History of the Kingdom of Kotte, 1400-1521. Nugegoda: Deepanee Printers. (Based on his SOAS PhD thesis, ''Political history of the Kingdom of Kotte, c. A.D. 1400-1521''.)', 'https://eprints.soas.ac.uk/29736/1/10752708.pdf', 'academic');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'Queiros, Fernao de (c. 1687). The Temporal and Spiritual Conquest of Ceylon [Conquista Temporal e Espiritual de Ceylao]. Translated by S.G. Perera, 3 vols. Colombo: Government Printer, 1930. Jesuit chronicle; pro-Portuguese primary source, used critically.', 'https://archive.org/details/temporalspiritua0000quey', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'Gunasekara, B., ed. and trans. (1900). The Rajavaliya: or, A Historical Narrative of Sinhalese Kings from Vijaya to Vimala Dharma Surya II. Colombo: Government Printer. Sinhala chronicle; primary source for the Vijayaba Kollaya and the Kotte period from the Sinhala side.', 'https://archive.org/details/in.ernet.dli.2015.42908', 'primary');
INSERT INTO sources (entity_id, citation, url, source_type) VALUES ((SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 'de Silva, K.M. (1981). A History of Sri Lanka. London: C. Hurst / Berkeley: University of California Press. Standard academic survey covering Kotte, the 1521 partition, Sitawaka resistance and the Portuguese absorption.', NULL, 'academic');

-- ── catena Sinhalese trunk ──
INSERT INTO dynasty_chains (name, name_lang, chain_type, region, description, confidence_score, status, ethical_notes, sources)
VALUES ('Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ', 'en', 'SUCCESSION', 'South Asia / Sri Lanka (Sinhalese heartland)', 'The Sinhalese Buddhist monarchy from the Anuradhapura kingdom (from the 5th c. BCE) through its drifting-capital successors to the Kingdom of Kotte, absorbed by Portugal in 1597. The Kandyan kingdom (a branch from 1469) carried the line to 1815.', 0.75, 'confirmed', 'This is the SINHALESE line only. ETHICS (no false linearity): the northern Tamil Jaffna kingdom (#601) is a PARALLEL polity with its own chain, NOT a subordinate node here; the 1017-1070 occupation of Rajarata is modelled as a FOREIGN Tamil Chola conquest (a node through the existing Chola entity #110), not a Sinhalese succession; the Kandyan kingdom (#388) is a branch, not the trunk terminus. Kalinga Magha''s invasion (1215) preceded the Dambadeniya consolidation (1232). The 1597 Portuguese absorption was a coerced client-state annexation at Dharmapala''s death, not a voluntary bequest.', '[{"citation": "K.M. de Silva, A History of Sri Lanka, University of California Press, 1981", "url": null, "source_type": "academic"}, {"citation": "R.A.L.H. Gunawardana, Robe and Plough: Monasticism and Economic Interest in Early Medieval Sri Lanka, University of Arizona Press, 1979", "url": null, "source_type": "academic"}]');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ'), (SELECT id FROM geo_entities WHERE name_original = 'අනුරාධපුර රාජධානිය'), 0, NULL, NULL, false, 'The Anuradhapura kingdom (c. 437 BCE - 1017 CE), the long first phase of the Sinhalese state, centred on the dry-zone irrigation civilisation of Rajarata.', NULL);
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ'), (SELECT id FROM geo_entities WHERE name_original = 'சோழ நாடு'), 1, 1017, 'CONQUEST', true, 'FOREIGN Tamil Chola conquest: Rajaraja I sacked Anuradhapura (993) and Rajendra I annexed the whole of Rajarata by 1017, administering it as the province Mummudi-sola-mandalam from Polonnaruwa (renamed Jananathamangalam). King Mahinda V was captured and died in exile in India (1029).', 'This link is a FOREIGN occupation, NOT a Sinhalese succession: the Chola entity #110 is a South Indian Tamil empire. Recorded here to represent the 1017-1070 interruption honestly, per the no-false-linearity principle.');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ'), (SELECT id FROM geo_entities WHERE name_original = 'පොළොන්නරුව'), 2, 1070, 'RESTORATION', true, 'Vijayabahu I expelled the Cholas by war (from Ruhuna in the south) and was crowned at Polonnaruwa (1070; formal consecration 1076-77), restoring Sinhalese sovereignty over Rajarata. Polonnaruwa became the new capital.', 'The 1055/56-1070 overlap is real: Vijayabahu I ruled from Ruhuna while the Cholas still held Rajarata.');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ'), (SELECT id FROM geo_entities WHERE name_original = 'දඹදෙණිය රාජධානිය'), 3, 1215, 'CONQUEST', true, 'Kalinga Magha''s invasion (1215) with a brutal occupation of Rajarata forced the Sinhalese polity to relocate to the southwestern wet zone; Vijayabahu III established the kingdom at Dambadeniya (1232), securing the Tooth Relic and re-founding Buddhist kingship.', 'The trigger is the 1215 invasion; 1232 is the Dambadeniya consolidation. The dry-zone irrigation civilisation of Rajarata was permanently abandoned after this.');
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ'), (SELECT id FROM geo_entities WHERE name_original = 'ගම්පොල රාජධානිය'), 4, 1341, 'SUCCESSION', false, 'Peaceful dynastic capital shift to Gampola (Gangasiripura) under Bhuvanaikabahu IV.', NULL);
INSERT INTO chain_links (chain_id, entity_id, sequence_order, transition_year, transition_type, is_violent, description, ethical_notes)
VALUES ((SELECT id FROM dynasty_chains WHERE name = 'Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ'), (SELECT id FROM geo_entities WHERE name_original = 'කෝට්ටේ රාජධානිය'), 5, 1412, 'SUCCESSION', true, 'Parakramabahu VI acceded (1412) and moved the capital to Kotte, reunifying most of the island by 1450. The transition followed the 1410-11 Ming intervention that captured and deported the previous king Vira Alakesvara.', 'Ming China''s armed intervention (1411) is documented on the Gampola entity; the Ming and Sinhala accounts of the 1412 accession (installation vs indigenous restoration) are both recorded, not arbitrated.');

-- ── validazione ──
DO $$
DECLARE n int; bad int;
BEGIN
  SELECT count(*) INTO n FROM geo_entities WHERE name_original IN ('ගම්පොල රාජධානිය', 'කෝට්ටේ රාජධානිය');
  IF n <> 2 THEN RAISE EXCEPTION 'attese 2 nuove entità, trovate %', n; END IF;
  SELECT count(*) INTO n FROM geo_entities WHERE id = 142 AND name_original = 'අනුරාධපුර රාජධානිය' AND year_end = 1017;
  IF n <> 1 THEN RAISE EXCEPTION '#142 re-scope fallito'; END IF;
  SELECT count(*) INTO n FROM geo_entities WHERE id = 600 AND name_original = 'දඹදෙණිය රාජධානිය';
  IF n <> 1 THEN RAISE EXCEPTION '#600 re-scope fallito'; END IF;
  SELECT count(*) INTO n FROM geo_entities WHERE id = 386 AND status = 'deprecated';
  IF n <> 1 THEN RAISE EXCEPTION '#386 non deprecata'; END IF;
  SELECT count(*) INTO bad FROM archaeological_sites WHERE entity_id = 386;
  IF bad <> 0 THEN RAISE EXCEPTION '% siti ancora su #386', bad; END IF;
  -- contiguità catena
  SELECT count(*) INTO bad FROM (SELECT chain_id FROM chain_links WHERE chain_id = (SELECT id FROM dynasty_chains WHERE name = 'Sinhalese kingdom trunk: අනුරාධපුර → පොළොන්නරුව → දඹදෙණිය → ගම්පොල → කෝට්ටේ') GROUP BY chain_id HAVING count(*) <> max(sequence_order)+1 OR min(sequence_order) <> 0) t;
  IF bad <> 0 THEN RAISE EXCEPTION 'catena non contigua'; END IF;
  -- antimeridian guard
  SELECT count(*) INTO bad FROM geo_entities WHERE name_original IN ('ගම්පොල රාජධානිය', 'කෝට්ටේ රාජධානිය') AND (ST_XMax(boundary_geom) - ST_XMin(boundary_geom)) >= 180;
  IF bad <> 0 THEN RAISE EXCEPTION '% boundary attraversano antimeridiano', bad; END IF;
  RAISE NOTICE 'ETHICS-021 OK: #142/#600 re-scope, #386 deprecata, Gampola+Kotte, catena Sinhalese';
END $$;

COMMIT;
