-- v6.99.124 (M4) — aggiunge la variante latina (romanizzazione) su prod
-- per simmetria fresh-seed ≡ prod. Idempotente (NOT EXISTS). Nessun rename
-- prod (il name_original nativo è già corretto). psql -v ON_ERROR_STOP=1.
BEGIN;

INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 405, 'Mamlakat Fas al-Wattasiyya', 'ar-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 405 AND name = 'Mamlakat Fas al-Wattasiyya');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 406, 'Al-Dawla al-Sa''diyya', 'ar-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 406 AND name = 'Al-Dawla al-Sa''diyya');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 410, 'Saltanat Sinnar', 'ar-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 410 AND name = 'Saltanat Sinnar');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 411, 'Taqali', 'ar-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 411 AND name = 'Taqali');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 420, 'Rus'' Kyivska', 'uk-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 420 AND name = 'Rus'' Kyivska');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 430, 'Sakartvelos samepo', 'ka-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 430 AND name = 'Sakartvelos samepo');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 434, 'Vtoro Balgarsko Tsarstvo', 'bg-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 434 AND name = 'Vtoro Balgarsko Tsarstvo');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 435, 'Srpsko Carstvo', 'sr-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 435 AND name = 'Srpsko Carstvo');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 436, 'Despotaton tou Moreos', 'grc-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 436 AND name = 'Despotaton tou Moreos');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 438, 'Autokratoria tis Trapezountas', 'el-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 438 AND name = 'Autokratoria tis Trapezountas');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 440, 'Halytsko-Volynske knyazivstvo', 'uk-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 440 AND name = 'Halytsko-Volynske knyazivstvo');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 658, 'Medri Bahri', 'ti-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 658 AND name = 'Medri Bahri');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 664, 'Tsarstvo Vidinsko', 'bg-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 664 AND name = 'Tsarstvo Vidinsko');
INSERT INTO name_variants (entity_id, name, lang, period_start, period_end, context, source) SELECT 736, 'Dawla al-Mahdiyya', 'ar-Latn', NULL, NULL, 'romanizzazione (ETHICS-001; ex name_original latino, sync M4 v6.99.124)', 'M4 reconciliation' WHERE NOT EXISTS (SELECT 1 FROM name_variants WHERE entity_id = 736 AND name = 'Dawla al-Mahdiyya');

-- validazione: ogni entità ha ora la variante latina
DO $$ DECLARE bad int; BEGIN
  SELECT count(*) INTO bad FROM (VALUES (405, 'Mamlakat Fas al-Wattasiyya'),(406, 'Al-Dawla al-Sa''diyya'),(410, 'Saltanat Sinnar'),(411, 'Taqali'),(420, 'Rus'' Kyivska'),(430, 'Sakartvelos samepo'),(434, 'Vtoro Balgarsko Tsarstvo'),(435, 'Srpsko Carstvo'),(436, 'Despotaton tou Moreos'),(438, 'Autokratoria tis Trapezountas'),(440, 'Halytsko-Volynske knyazivstvo'),(658, 'Medri Bahri'),(664, 'Tsarstvo Vidinsko'),(736, 'Dawla al-Mahdiyya')) v(eid, nm) WHERE NOT EXISTS (SELECT 1 FROM name_variants nv WHERE nv.entity_id = v.eid AND nv.name = v.nm);
  IF bad <> 0 THEN RAISE EXCEPTION '% varianti latine mancanti', bad; END IF;
  RAISE NOTICE 'M4 v6.99.124 OK: 14 varianti latine sincronizzate';
END $$;

COMMIT;
